#!/usr/bin/env python3
"""Build a compact Unicode-16 native-v7 companion from exact official UCD bytes.

No network, corpus, source normalization or publication side effects. Download
the four pinned files separately; --check verifies an existing generated file.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import unicodedata

VERSION = "16.0.0"
FILES = {
    "UnicodeData": "ff58e5823bd095166564a006e47d111130813dcf8bf234ef79fa51a870edb48f",
    "SpecialCasing": "8d5de354eef79f2395a54c9c7dcebbaf3d30fc962d0f85611ea97aa973a0c451",
    "DerivedCoreProperties": "39d35161f2954497f69e08bdb9e701493f476a3d30222de20028feda36c1dabd",
    "CaseFolding": "6f1f9c588eb4a5c718d9e8f93b782685e5c7fec872cf05e8e6878053599e09bb",
}


def ranges(points):
    result = []
    for point in sorted(points):
        if result and point == result[-1][1] + 1:
            result[-1][1] = point
        else:
            result.append([point, point])
    return result


def build(directory: Path) -> str:
    if unicodedata.unidata_version != VERSION:
        raise ValueError("native oracle must use Unicode " + VERSION)
    texts = {}
    for name, digest in FILES.items():
        raw = (directory / f"{name}-{VERSION}.txt").read_bytes()
        if hashlib.sha256(raw).hexdigest() != digest:
            raise ValueError("UCD source digest differs: " + name)
        texts[name] = raw.decode("utf-8")
    lower, printable, decimal, interval = {}, set(), {}, None
    for line in texts["UnicodeData"].splitlines():
        row = line.split(";")
        point, name, category = int(row[0], 16), row[1], row[2]
        if row[13]:
            lower[point] = chr(int(row[13], 16))
        if row[6]:
            decimal[point] = row[6]
        if name.endswith(", First>"):
            interval = point
        elif name.endswith(", Last>"):
            if category[0] not in "CZ":
                printable.update(range(interval, point + 1))
            interval = None
        elif category[0] not in "CZ":
            printable.add(point)
    printable.add(0x20)
    conditions = []
    for line in texts["SpecialCasing"].splitlines():
        content = line.split("#")[0].strip()
        if not content:
            continue
        row = [field.strip() for field in content.split(";")]
        if row[4]:
            if not any(language in row[4].split() for language in ("tr", "az", "lt")):
                conditions.append((row[0], row[1], row[4]))
            continue
        lower[int(row[0], 16)] = "".join(chr(int(code, 16)) for code in row[1].split())
    if conditions != [("03A3", "03C2", "Final_Sigma")]:
        raise ValueError("unhandled default contextual lowercase rule")
    properties = {"Cased": set(), "Case_Ignorable": set()}
    for line in texts["DerivedCoreProperties"].splitlines():
        content = line.split("#")[0].strip()
        if not content:
            continue
        field, name, *_ = [part.strip() for part in content.split(";")]
        if name in properties:
            bounds = [int(value, 16) for value in field.split("..")]
            properties[name].update(range(bounds[0], bounds[-1] + 1))
    lower = {point: value for point, value in lower.items() if chr(point) != value}
    fold = {}
    for line in texts['CaseFolding'].splitlines():
        row = [part.strip() for part in line.split('#')[0].split(';')]
        if len(row) > 2 and row[1] in {'C', 'F'}:
            fold[int(row[0], 16)] = ''.join(chr(int(code, 16)) for code in row[2].split())
    for point in range(0x110000):
        char = chr(point)
        if lower.get(point, char) != char.lower() or (point in printable) != char.isprintable():
            raise ValueError(f"UCD differs from native Python at U+{point:04X}")
        if fold.get(point, char) != char.casefold():
            raise ValueError(f"UCD casefold differs from native Python at U+{point:04X}")
        expected_decimal = unicodedata.decimal(char, None)
        if decimal.get(point) != (str(expected_decimal) if expected_decimal is not None else None):
            raise ValueError(f"UCD decimal differs from native Python at U+{point:04X}")
    compact = lambda value: json.dumps(value, ensure_ascii=True, separators=(",", ":"))
    provenance = [{"url": f"https://www.unicode.org/Public/{VERSION}/ucd/{name}.txt", "sha256": digest}
                  for name, digest in FILES.items()]
    return "\n".join([
        "// Generated by build_native_unicode.py. Do not edit. Unicode data: UNICODE-LICENSE.txt.",
        f"export const nativeUnicodeVersion = {compact(VERSION)};",
        'export const nativeUnicodeAlgorithm = "tos-python-native-unicode-v1";',
        "export const nativeUnicodeSources = " + compact(provenance) + " as const;",
        "export const nativeLowerMappings: ReadonlyArray<readonly [number, string]> = " + compact(sorted(lower.items())) + ";",
        "export const nativeCasefoldMappings: ReadonlyArray<readonly [number, string]> = " + compact(sorted(fold.items())) + ";",
        "export const nativeDecimalMappings: ReadonlyArray<readonly [number, string]> = " + compact(sorted(decimal.items())) + ";",
        "export const nativeCasedRanges: ReadonlyArray<readonly [number, number]> = " + compact(ranges(properties["Cased"])) + ";",
        "export const nativeCaseIgnorableRanges: ReadonlyArray<readonly [number, number]> = " + compact(ranges(properties["Case_Ignorable"])) + ";",
        "export const nativePrintableRanges: ReadonlyArray<readonly [number, number]> = " + compact(ranges(printable)) + ";", "",
    ])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ucd-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("native-unicode.generated.ts"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = build(args.ucd_dir)
    if args.check:
        if args.output.read_text(encoding="utf-8") != text:
            raise SystemExit("generated Unicode companion differs")
    else:
        args.output.write_text(text, encoding="utf-8")
    print(f"Unicode {VERSION}: exact UCD provenance and all 1114112 code-point probes pass; {len(text.encode())} bytes")
