#!/usr/bin/env python3
"""Build the public synthetic provenance-event-v2 A/B/C laboratory.

The three variant commands are intentionally independent. Variant C returns a
non-zero exit code after preserving its deterministic failure byproduct and
event record. ``--finalize`` binds the exact generated bytes into the tracked
laboratory manifest; it does not attest that the self-reported events are true.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import platform
import sys
import time
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
LAB_ROOT = REPO_ROOT / (
    "ToS/research-packets/foundation-laboratory-2026-07/"
    "provenance-event-v2-abc"
)
LAB_REF = LAB_ROOT.relative_to(REPO_ROOT).as_posix()
SCHEMA_REF = "ToS/contracts/provenance-event-v2.schema.json"
SCRIPT_REF = "scripts/build_provenance_event_v2_lab.py"
PLAN_REF = f"{LAB_REF}/plan.json"
INPUT_FIXTURE_REF = f"{LAB_REF}/input-fixture.txt"
ENVIRONMENT_REF = f"{LAB_REF}/environment-profile.json"
MANIFEST_REF = f"{LAB_REF}/lab.manifest.json"

OUTPUT_REFS = {
    "A": f"{LAB_REF}/variant-a.copy.txt",
    "B": f"{LAB_REF}/variant-b.nfc.txt",
}
BYPRODUCT_REFS = {"C": f"{LAB_REF}/variant-c.failure.log"}
EVENT_REFS = {
    variant: f"{LAB_REF}/variant-{variant.lower()}.event.v2.json"
    for variant in ("A", "B", "C")
}
OPERATIONS = {
    "A": "identity-copy",
    "B": "unicode-nfc",
    "C": "ascii-strict-negative-control",
}
EXPECTED_STATUS = {"A": "completed", "B": "completed", "C": "failed"}
EXPECTED_RELATION = {"A": "identity_copy_of", "B": "revision_of", "C": None}
FAILURE_BYTES = b"status=failed\nreason=non_ascii_input\nexit_code=7\n"

CLAIMS_NOT_ESTABLISHED = [
    "execution_truth",
    "content_truth",
    "source_fidelity",
    "translation_quality",
    "semantic_correctness",
    "rights_clearance",
    "human_review",
    "publication_authority",
    "canon_authority",
]

NEGATIVE_CONTROLS = [
    "event_record_digest_drift",
    "input_fixity_drift",
    "command_digest_drift",
    "completed_without_output",
    "failed_with_authoritative_output",
    "identity_copy_content_drift",
    "derivation_endpoint_escape",
    "model_event_without_invocation",
    "replay_ready_with_withheld_command",
    "unsigned_claimed_signature_verification",
    "publication_without_authority",
    "unattested_human_review",
    "manual_change_without_receipt",
    "self_supersession",
]


def _sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def _sha256(path: Path) -> str:
    return _sha256_bytes(path.read_bytes())


def _write_json(path: Path, payload: dict[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def _iso_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="microseconds")


def _canonical_argv_sha256(argv: list[str]) -> str:
    payload = json.dumps(
        argv,
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")
    return _sha256_bytes(payload)


def _repo_path(ref: str) -> Path:
    return REPO_ROOT / ref


def _binding(ref: str) -> dict[str, str]:
    return {"ref": ref, "sha256": _sha256(_repo_path(ref))}


def _prepare_environment() -> int:
    executable = Path(sys.executable).resolve()
    payload = {
        "schema_version": "tos_provenance_environment_profile_v1",
        "profile_id": "tos.environment.provenance-event-v2.synthetic-abc",
        "captured_at": _iso_now(),
        "runtime": {
            "implementation": platform.python_implementation(),
            "version": platform.python_version(),
            "executable_sha256": _sha256(executable),
            "unicode_version": unicodedata.unidata_version,
        },
        "platform": {
            "system": platform.system(),
            "release": platform.release(),
            "machine": platform.machine(),
            "hardware_target": "cpu",
        },
        "capture_boundary": {
            "absolute_paths_recorded": False,
            "environment_variables_recorded": False,
            "packages_enumerated": False,
            "reason": "The lab uses only CPython standard-library byte and Unicode operations.",
        },
    }
    _write_json(_repo_path(ENVIRONMENT_REF), payload)
    print(f"prepared {ENVIRONMENT_REF}")
    return 0


def _entity(ref: str, role: str, verified_at: str) -> dict[str, Any]:
    path = _repo_path(ref)
    return {
        "entity_ref": ref,
        "role": role,
        "sha256": _sha256(path),
        "size_bytes": path.stat().st_size,
        "media_type": "text/plain; charset=utf-8",
        "availability": "tracked",
        "content_disclosure": "synthetic_public",
        "fixity_verified": True,
        "fixity_verified_at": verified_at,
    }


def _event(
    *,
    variant: str,
    argv: list[str],
    started_at: str,
    ended_at: str,
    duration_ms: float,
    status: str,
    exit_code: int,
    terminal_reason: str | None,
    output_ref: str | None,
    byproduct_ref: str | None,
) -> dict[str, Any]:
    environment = json.loads(_repo_path(ENVIRONMENT_REF).read_text(encoding="utf-8"))
    input_fixture = _entity(INPUT_FIXTURE_REF, "public-synthetic-input", ended_at)
    outputs = (
        [_entity(output_ref, "authoritative-synthetic-output", ended_at)]
        if output_ref
        else []
    )
    byproducts = (
        [_entity(byproduct_ref, "failure-diagnostic-byproduct", ended_at)]
        if byproduct_ref
        else []
    )
    relation = EXPECTED_RELATION[variant]
    derivations = []
    if output_ref is not None and relation is not None:
        derivations.append(
            {
                "derivation_id": f"tos.derivation.provenance-v2.synthetic-{variant.lower()}",
                "input_entity_ref": INPUT_FIXTURE_REF,
                "output_entity_ref": output_ref,
                "relation": relation,
                "influence_asserted": True,
                "description": (
                    "Byte-identical copy into a distinct entity."
                    if variant == "A"
                    else "Unicode NFC normalization of the exact UTF-8 input entity."
                ),
            }
        )

    output_size = _repo_path(output_ref).stat().st_size if output_ref else None
    event_type = {
        "A": "identity_copy",
        "B": "normalization",
        "C": "synthetic_negative_control",
    }[variant]
    warnings = (
        ["The failed path produced a diagnostic byproduct but no authoritative output."]
        if variant == "C"
        else []
    )
    return {
        "$schema": "https://tree-of-sophia.local/ToS/contracts/provenance-event-v2.schema.json",
        "schema_version": "tos_provenance_event_v2",
        "event_id": f"tos.event.provenance-v2.synthetic-{variant.lower()}.2026-08-11",
        "event_version": 1,
        "supersedes_event_ref": None,
        "record_binding": {
            "manifest_ref": MANIFEST_REF,
            "digest_algorithm": "sha256",
            "digest_scope": "exact_event_record_bytes",
        },
        "activity": {
            "event_type": event_type,
            "started_at": started_at,
            "ended_at": ended_at,
            "status": status,
            "terminal_reason": terminal_reason,
            "exit_code": exit_code,
            "warnings": warnings,
        },
        "entities": {
            "inputs": [input_fixture],
            "outputs": outputs,
            "byproducts": byproducts,
        },
        "derivations": derivations,
        "responsibility": [
            {
                "agent_ref": "software:tos-provenance-event-v2-lab-builder",
                "agent_kind": "software",
                "role": "executor",
                "responsibility_posture": "performed",
                "evidence_binding": _binding(SCRIPT_REF),
                "human_evidence_status": "not_applicable",
            }
        ],
        "method": {
            "procedure": {
                "name": OPERATIONS[variant],
                "version": "1",
                "purpose": "Public synthetic provenance mechanics and negative-control exercise.",
            },
            "command_capture": {
                "disclosure": "inline",
                "argv": argv,
                "argv_sha256": _canonical_argv_sha256(argv),
                "withholding_reason": None,
            },
            "configuration_binding": _binding(PLAN_REF),
            "software_components": [
                {
                    "name": "Tree of Sophia provenance v2 laboratory builder",
                    "version": "1",
                    "role": "transformation-runner",
                    "artifact_ref": SCRIPT_REF,
                    "artifact_sha256": _sha256(_repo_path(SCRIPT_REF)),
                    "verification_status": "verified",
                },
                {
                    "name": environment["runtime"]["implementation"],
                    "version": environment["runtime"]["version"],
                    "role": "language-runtime",
                    "artifact_ref": "runtime:cpython-executable",
                    "artifact_sha256": environment["runtime"]["executable_sha256"],
                    "verification_status": "verified",
                },
            ],
            "model_invocations": [],
            "environment": {
                "runtime": environment["runtime"]["implementation"],
                "runtime_version": environment["runtime"]["version"],
                "runtime_artifact_sha256": environment["runtime"]["executable_sha256"],
                "backend": "python-standard-library",
                "hardware_target": environment["platform"]["hardware_target"],
                "unicode_version": environment["runtime"]["unicode_version"],
                "environment_profile_binding": _binding(ENVIRONMENT_REF),
            },
        },
        "manual_changes": {
            "status": "none_declared",
            "change_receipts": [],
            "statement": "No manual edit occurred between input read and output or failure capture.",
        },
        "measurements": [
            {
                "metric": "wall_duration_ms",
                "status": "measured",
                "value": duration_ms,
                "unit": "ms",
                "method": "time.perf_counter_ns around the bounded variant operation",
                "evidence_binding": None,
            },
            {
                "metric": "input_bytes",
                "status": "measured",
                "value": _repo_path(INPUT_FIXTURE_REF).stat().st_size,
                "unit": "bytes",
                "method": "filesystem stat after exact input read",
                "evidence_binding": None,
            },
            {
                "metric": "output_bytes",
                "status": "measured" if output_size is not None else "not_applicable",
                "value": output_size,
                "unit": "bytes" if output_size is not None else None,
                "method": (
                    "filesystem stat after exact output write"
                    if output_size is not None
                    else "No authoritative output exists for the failed event"
                ),
                "evidence_binding": None,
            },
        ],
        "evidence_authentication": {
            "capture_posture": "tool_captured",
            "signature_status": "unsigned",
            "signature_bindings": [],
            "verification_status": "unverified",
            "producer_control_boundary": (
                "The same local script executed the operation and wrote this unsigned record; "
                "later byte validation checks closure but does not authenticate execution truth."
            ),
        },
        "rights_and_visibility": {
            "rights_record_bindings": [],
            "intended_uses": ["synthetic_contract_test"],
            "content_visibility": "public_synthetic",
            "publication_authorized": False,
            "publication_authority_bindings": [],
        },
        "review_and_authority": {
            "mechanical_validation": "not_run",
            "human_review_status": "not_performed",
            "review_bindings": [],
            "accepted_uses": [],
            "promotion_authorized": False,
            "competence_evidence_bindings": [],
        },
        "reproducibility": {
            "classification": (
                "replay_ready_negative_control" if variant == "C" else "replay_ready"
            ),
            "known_gaps": [
                "The execution receipt is unsigned and self-reported by the transformation runner."
            ],
            "replay_scope": (
                "Exact synthetic bytes, tracked plan, builder digest, CPython executable digest, "
                "Unicode version, argv, terminal status, and expected output or failure byproduct."
            ),
        },
        "authority_boundary": {
            "validator_role": "mechanics_and_closure_only_not_truth",
            "claims_not_established": CLAIMS_NOT_ESTABLISHED,
        },
    }


def _run_variant(variant: str) -> int:
    environment_path = _repo_path(ENVIRONMENT_REF)
    if not environment_path.is_file():
        raise SystemExit("environment profile is absent; run --prepare first")

    argv = ["python", SCRIPT_REF, "--variant", variant]
    started_at = _iso_now()
    started_ns = time.perf_counter_ns()
    status = "completed"
    exit_code = 0
    terminal_reason: str | None = None
    output_ref: str | None = None
    byproduct_ref: str | None = None

    input_bytes = _repo_path(INPUT_FIXTURE_REF).read_bytes()
    if variant == "A":
        output_ref = OUTPUT_REFS[variant]
        _repo_path(output_ref).write_bytes(input_bytes)
    elif variant == "B":
        output_ref = OUTPUT_REFS[variant]
        source = input_bytes.decode("utf-8")
        _repo_path(output_ref).write_text(
            unicodedata.normalize("NFC", source),
            encoding="utf-8",
        )
    else:
        try:
            input_bytes.decode("utf-8").encode("ascii", errors="strict")
        except UnicodeEncodeError:
            status = "failed"
            exit_code = 7
            terminal_reason = "ascii_strict_rejected_non_ascii_input"
            byproduct_ref = BYPRODUCT_REFS[variant]
            _repo_path(byproduct_ref).write_bytes(FAILURE_BYTES)
        else:
            raise RuntimeError("negative control unexpectedly accepted the non-ASCII input fixture")

    duration_ms = round((time.perf_counter_ns() - started_ns) / 1_000_000, 6)
    ended_at = _iso_now()
    event = _event(
        variant=variant,
        argv=argv,
        started_at=started_at,
        ended_at=ended_at,
        duration_ms=duration_ms,
        status=status,
        exit_code=exit_code,
        terminal_reason=terminal_reason,
        output_ref=output_ref,
        byproduct_ref=byproduct_ref,
    )
    _write_json(_repo_path(EVENT_REFS[variant]), event)
    print(f"{variant}: status={status} exit_code={exit_code}")
    return exit_code


def _finalize() -> int:
    variants: list[dict[str, Any]] = []
    for variant in ("A", "B", "C"):
        event_ref = EVENT_REFS[variant]
        event = json.loads(_repo_path(event_ref).read_text(encoding="utf-8"))
        output_ref = OUTPUT_REFS.get(variant)
        byproduct_ref = BYPRODUCT_REFS.get(variant)
        variants.append(
            {
                "variant_id": variant,
                "operation": OPERATIONS[variant],
                "expected_status": EXPECTED_STATUS[variant],
                "expected_relation": EXPECTED_RELATION[variant],
                "expected_exit_code": 7 if variant == "C" else 0,
                "event_ref": event_ref,
                "event_sha256": _sha256(_repo_path(event_ref)),
                "input_ref": INPUT_FIXTURE_REF,
                "input_sha256": _sha256(_repo_path(INPUT_FIXTURE_REF)),
                "output_ref": output_ref,
                "output_sha256": _sha256(_repo_path(output_ref)) if output_ref else None,
                "byproduct_ref": byproduct_ref,
                "byproduct_sha256": (
                    _sha256(_repo_path(byproduct_ref)) if byproduct_ref else None
                ),
                "captured_command": event["method"]["command_capture"]["argv"],
            }
        )

    manifest = {
        "schema_version": "tos_provenance_event_v2_lab_v1",
        "lab_id": "tos.lab.provenance-event-v2.synthetic-abc",
        "contract": _binding(SCHEMA_REF),
        "plan": _binding(PLAN_REF),
        "builder": _binding(SCRIPT_REF),
        "environment_profile": _binding(ENVIRONMENT_REF),
        "input_fixture": _binding(INPUT_FIXTURE_REF),
        "authority_posture": "public_synthetic_mechanics_only",
        "authority_limits": {
            "private_source_used": False,
            "model_invoked": False,
            "human_evidence_created": False,
            "execution_truth_established": False,
            "content_truth_established": False,
            "rights_clearance_established": False,
            "semantic_claim_created": False,
            "canon_effect": False,
        },
        "variants": variants,
        "negative_controls": NEGATIVE_CONTROLS,
    }
    _write_json(_repo_path(MANIFEST_REF), manifest)
    print(f"finalized {MANIFEST_REF}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--prepare", action="store_true")
    group.add_argument("--variant", choices=("A", "B", "C"))
    group.add_argument("--finalize", action="store_true")
    args = parser.parse_args()
    if args.prepare:
        return _prepare_environment()
    if args.variant:
        return _run_variant(args.variant)
    return _finalize()


if __name__ == "__main__":
    raise SystemExit(main())
