import {installClientInspectionRules} from './observatory/client-inspection-rules.mjs';
import {installKnowledgeSearchRules} from './knowledge-search';
import {installClaimReadingRules} from './observatory/claim-reading-rules.mjs';
import {installRecordContextRules} from './observatory/record-context.mjs';
// Both browser presentations use the same initialized Rust workspace machine.
// Generated bytes are admitted with the Worker bundle by the build owner.
import {installBrowserWorkspaceMachine} from './research-workspace-rust';
import {installWorkspaceCopyRules} from './observatory/workspace-copy-rust.mjs';
import {installInterfaceRules} from './observatory/interface-model-rust.mjs';
import {installPoseRules} from './observatory/view-state-rust.mjs';
import {installClaimReferenceRules} from './observatory/claim-reference-rust.mjs';
import {installHumanFormRules} from './observatory/human-form-rules.mjs';
import {installReadingRules} from './observatory/reading-resume-rust.mjs';
import {installResearchShelfRules} from './research-shelf/rules.mjs';
import {installConditionRules} from './observatory/lens-conditions-rust.mjs';
import {installDraftRules} from './observatory/lens-draft-rust.mjs';
import initRules,* as rules from '../../deploy/cloudflare-worker/generated/tos_web_rules.js';
await initRules(new URL('../../deploy/cloudflare-worker/generated/tos_web_rules_bg.wasm',import.meta.url));
installBrowserWorkspaceMachine(rules.BrowserWorkspaceSession);
installWorkspaceCopyRules(rules);
installInterfaceRules(rules);
installPoseRules(rules);
installClaimReferenceRules(rules);
installHumanFormRules(rules);
installRecordContextRules(rules);
installKnowledgeSearchRules(rules);
installClaimReadingRules(rules);
installClientInspectionRules(rules);
installConditionRules(rules);
installDraftRules(rules);
installReadingRules(rules);
installResearchShelfRules(rules);

// Existing published research links remain reloadable during the UI migration.
const params = new URLSearchParams(location.search);
if (params.get("workspace") === "classic" || params.has("mode") || params.has("view")) {
  void import("./main");
} else {
  void import("./observatory/app.mjs").then(({mountObservatory}) => mountObservatory());
}
