// Both browser presentations use the same initialized Rust workspace machine.
// Generated bytes are admitted with the Worker bundle by the build owner.
import {installBrowserWorkspaceMachine} from './research-workspace-rust';
import initRules,{BrowserWorkspaceSession} from '../../deploy/cloudflare-worker/generated/tos_web_rules.js';
await initRules(new URL('../../deploy/cloudflare-worker/generated/tos_web_rules_bg.wasm',import.meta.url));
installBrowserWorkspaceMachine(BrowserWorkspaceSession);

// Existing published research links remain reloadable during the UI migration.
const params = new URLSearchParams(location.search);
if (params.get("workspace") === "classic" || params.has("mode") || params.has("view")) {
  void import("./main");
} else {
  void import("./observatory/app.mjs").then(({mountObservatory}) => mountObservatory());
}
