//! Maintained decision-record validation and lookup-index generation.
//! Decision notes own rationale; generated Markdown remains a read model.
use crate::route_cards::{RouteSources, python_space, splitlines};
use regex::Regex;
use std::{
    collections::{BTreeMap, BTreeSet},
    io,
    path::{Component, Path},
    sync::atomic::{AtomicI32, Ordering},
};
use tos_foundation::python_lower_unicode16_v1;
use unicode_general_category::{GeneralCategory, get_general_category};
pub type Issue = (String, String);
pub const DECISIONS_DIR: &str = "docs/decisions";
pub const CONTRACT: &str = "docs/decisions/indexes/index_contract.yaml";
pub const INDEX_PATHS: &[&str] = &[
    "docs/decisions/indexes/README.md",
    "docs/decisions/indexes/by-number.md",
    "docs/decisions/indexes/by-date.md",
    "docs/decisions/indexes/by-surface.md",
    "docs/decisions/indexes/by-tos-layer.md",
    "docs/decisions/indexes/by-tree-class.md",
    "docs/decisions/indexes/by-guard.md",
];
const STATIC: &[&str] = &["AGENTS.md", "README.md", "TEMPLATE.md"];
const NOTE: &str =
    "<!-- Generated by tos-ops-mechanics-plan --decision-index-build; do not edit by hand. -->";
const MAX_ISSUES: usize = 4096;
const MAX_OUTPUT: usize = 16 * 1024 * 1024;
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DecisionRecord {
    pub decision_id: String,
    pub number: String,
    pub title: String,
    pub path: String,
    pub original_date: String,
    pub surface_classes: Vec<String>,
    pub tos_layers: Vec<String>,
    pub tree_classes: Vec<String>,
    pub guard_families: Vec<String>,
    pub posture: String,
}
fn invalid(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, message.into())
}
fn check(s: &RouteSources, cancel: &AtomicI32) -> io::Result<()> {
    s.check()?;
    if cancel.load(Ordering::Relaxed) != 0 {
        return Err(io::Error::new(
            io::ErrorKind::Interrupted,
            "decision operation cancelled",
        ));
    }
    Ok(())
}
fn issue(out: &mut Vec<Issue>, path: &str, message: impl Into<String>) -> io::Result<()> {
    let message = message.into();
    if out.len() >= MAX_ISSUES
        || out.iter().map(|(p, m)| p.len() + m.len()).sum::<usize>() + path.len() + message.len()
            > MAX_OUTPUT
    {
        return Err(invalid("decision diagnostic output bound exceeded"));
    }
    out.push((path.into(), message));
    Ok(())
}
fn strip(text: &str) -> &str {
    text.trim_matches(python_space)
}
fn split_values(value: &str) -> Vec<String> {
    let mut items = value
        .split(',')
        .map(strip)
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .collect::<Vec<_>>();
    if items.is_empty() {
        items.push("none".into());
    }
    items
}
fn decision_re() -> Regex {
    Regex::new(r"^TOS-D-(\d{4})-[a-z0-9][a-z0-9-]*\.md$").expect("literal decision filename regex")
}
fn metadata(text: &str, path: &str, out: &mut Vec<Issue>) -> io::Result<BTreeMap<String, String>> {
    let lines = splitlines(text);
    let Some(start) = lines.iter().position(|l| *l == "## Index Metadata") else {
        issue(out, path, "missing '## Index Metadata' block")?;
        return Ok(BTreeMap::new());
    };
    let mut result = BTreeMap::new();
    for line in &lines[start + 1..] {
        if line.starts_with("## ") {
            break;
        }
        if let Some(line) = line.strip_prefix("- ") {
            if let Some((key, value)) = line.split_once(':') {
                result.insert(strip(key).into(), strip(value).into());
            }
        }
    }
    Ok(result)
}
fn required(
    meta: &BTreeMap<String, String>,
    key: &str,
    path: &str,
    out: &mut Vec<Issue>,
) -> io::Result<String> {
    let value = meta.get(key).map(|s| strip(s)).unwrap_or("");
    if value.is_empty() {
        issue(out, path, format!("missing Index Metadata field '{key}'"))?;
    }
    Ok(value.into())
}
fn leap(y: u32) -> bool {
    y % 4 == 0 && (y % 100 != 0 || y % 400 == 0)
}
fn calendar(y: u32, m: u32, d: u32) -> bool {
    if y == 0 || y > 9999 || !(1..=12).contains(&m) {
        return false;
    }
    let days = match m {
        2 => {
            if leap(y) {
                29
            } else {
                28
            }
        }
        4 | 6 | 9 | 11 => 30,
        _ => 31,
    };
    d >= 1 && d <= days
}
fn ascii_number(s: &str) -> Option<u32> {
    if s.is_empty() || !s.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    s.parse().ok()
}
/// Python date.fromisoformat accepts extended/basic calendar and ISO week dates.
fn iso_date(value: &str) -> bool {
    if !value.is_ascii() {
        return false;
    }
    let bytes = value.as_bytes();
    if bytes.len() < 4 {
        return false;
    }
    let Some(year) = ascii_number(&value[..4]).filter(|y| *y > 0) else {
        return false;
    };
    if bytes.len() == 10 && bytes[4] == b'-' && bytes[7] == b'-' {
        return ascii_number(&value[5..7])
            .zip(ascii_number(&value[8..]))
            .is_some_and(|(m, d)| calendar(year, m, d));
    }
    if bytes.len() == 8 && bytes[4].is_ascii_digit() {
        return ascii_number(&value[4..6])
            .zip(ascii_number(&value[6..]))
            .is_some_and(|(m, d)| calendar(year, m, d));
    }
    let (week, day) = if matches!(bytes.len(), 8 | 10) && bytes[4] == b'-' && bytes[5] == b'W' {
        let Some(w) = ascii_number(&value[6..8]) else {
            return false;
        };
        if bytes.len() == 10 {
            if bytes[8] != b'-' {
                return false;
            }
            let Some(d) = ascii_number(&value[9..]) else {
                return false;
            };
            (w, d)
        } else {
            (w, 1)
        }
    } else if matches!(bytes.len(), 7 | 8) && bytes[4] == b'W' {
        let Some(w) = ascii_number(&value[5..7]) else {
            return false;
        };
        if bytes.len() == 8 {
            let Some(d) = ascii_number(&value[7..]) else {
                return false;
            };
            (w, d)
        } else {
            (w, 1)
        }
    } else {
        return false;
    };
    let before = year - 1;
    let jan1 = (before * 365 + before / 4 - before / 100 + before / 400) % 7;
    let max_week = if jan1 == 3 || (jan1 == 2 && leap(year)) {
        53
    } else {
        52
    };
    if week < 1 || week > max_week || day < 1 || day > 7 {
        return false;
    } // Final week can extend beyond Python's maximum calendar year.
    let ordinal = (week - 1) * 7 + day;
    let jan4_day = (jan1 + 3) % 7;
    let relative = ordinal as i32 + 3 - jan4_day as i32;
    if year == 9999 && relative > 365 {
        return false;
    }
    true
}
fn decimal(c: char) -> Option<u32> {
    if get_general_category(c) != GeneralCategory::DecimalNumber {
        return None;
    }
    let mut start = c as u32;
    while start > 0
        && char::from_u32(start - 1)
            .is_some_and(|c| get_general_category(c) == GeneralCategory::DecimalNumber)
    {
        start -= 1;
    }
    Some((c as u32 - start) % 10)
}
fn number(s: &str) -> io::Result<u32> {
    s.chars().try_fold(0u32, |n, c| {
        decimal(c)
            .map(|d| n * 10 + d)
            .ok_or_else(|| invalid("decision number is not decimal"))
    })
}
pub fn collect_decision_records(
    s: &mut RouteSources,
    cancel: &AtomicI32,
) -> io::Result<(Vec<DecisionRecord>, Vec<Issue>)> {
    let mut records = Vec::new();
    let mut out = Vec::new();
    check(s, cancel)?;
    if !s.is_dir(DECISIONS_DIR)? {
        return Ok((
            records,
            vec![(DECISIONS_DIR.into(), "decision directory is missing".into())],
        ));
    }
    let paths = s.paths(DECISIONS_DIR)?;
    let top = paths
        .into_iter()
        .filter(|p| Path::new(p).parent() == Some(Path::new(DECISIONS_DIR)) && p.ends_with(".md"))
        .collect::<Vec<_>>();
    let re = decision_re();
    let id_re = Regex::new(r"^TOS-D-\d{4}$").expect("literal decision ID regex");
    for path in &top {
        check(s, cancel)?;
        let name = Path::new(path).file_name().unwrap().to_str().unwrap();
        if !STATIC.contains(&name) && !name.starts_with("TOS-D-") {
            issue(
                &mut out,
                path,
                "top-level decision markdown must use TOS-D-####-slug.md",
            )?;
        }
    }
    for path in top.iter().filter(|p| {
        Path::new(p)
            .file_name()
            .unwrap()
            .to_str()
            .unwrap()
            .starts_with("TOS-D-")
    }) {
        check(s, cancel)?;
        let name = Path::new(path).file_name().unwrap().to_str().unwrap();
        let Some(captures) = re.captures(name) else {
            issue(&mut out, path, "filename must match TOS-D-####-slug.md")?;
            continue;
        };
        let text = s.text(path)?.ok_or_else(|| {
            invalid(format!(
                "decision source is not a readable regular file: {path}"
            ))
        })?;
        let title = splitlines(&text)
            .into_iter()
            .find_map(|l| l.strip_prefix("# ").map(strip))
            .unwrap_or("")
            .to_string();
        if title.is_empty() {
            issue(&mut out, path, "missing H1 title")?;
        }
        let meta = metadata(&text, path, &mut out)?;
        let id = required(&meta, "Decision ID", path, &mut out)?;
        let date = required(&meta, "Original date", path, &mut out)?;
        let surface = required(&meta, "Surface classes", path, &mut out)?;
        let layers = required(&meta, "ToS layers", path, &mut out)?;
        let tree = required(&meta, "Tree classes", path, &mut out)?;
        let guard = required(&meta, "Guard families", path, &mut out)?;
        let posture = required(&meta, "Posture", path, &mut out)?;
        let number = captures[1].to_string();
        let expected = format!("TOS-D-{number}");
        if !id.is_empty() && id != expected {
            issue(
                &mut out,
                path,
                format!("Decision ID must match filename prefix '{expected}'"),
            )?;
        }
        if !id.is_empty() && !id_re.is_match(&id) {
            issue(&mut out, path, "Decision ID must match TOS-D-####")?;
        }
        if !date.is_empty() && !iso_date(&date) {
            issue(&mut out, path, "Original date must use YYYY-MM-DD")?;
        }
        if !id.is_empty() && !date.is_empty() && !title.is_empty() {
            records.push(DecisionRecord {
                decision_id: id,
                number,
                title,
                path: path.clone(),
                original_date: date,
                surface_classes: split_values(&surface),
                tos_layers: split_values(&layers),
                tree_classes: split_values(&tree),
                guard_families: split_values(&guard),
                posture: if posture.is_empty() {
                    "unknown".into()
                } else {
                    posture
                },
            });
        }
    }
    if records.is_empty() {
        issue(
            &mut out,
            DECISIONS_DIR,
            "no canonical decision records found",
        )?;
    }
    let mut seen = BTreeMap::new();
    for r in &records {
        if let Some(previous) = seen.get(&r.decision_id) {
            issue(
                &mut out,
                &r.path,
                format!("duplicate Decision ID also used by {previous}"),
            )?;
        }
        seen.insert(r.decision_id.clone(), r.path.clone());
    }
    let mut numbers = records
        .iter()
        .map(|r| number(&r.number))
        .collect::<io::Result<Vec<_>>>()?;
    numbers.sort();
    if let Some(max) = numbers.last() {
        if numbers != (1..=*max).collect::<Vec<_>>() {
            issue(
                &mut out,
                DECISIONS_DIR,
                "decision numbers must be contiguous from TOS-D-0001",
            )?;
        }
    }
    Ok((records, out))
}
pub fn validate_index_contract(s: &mut RouteSources) -> io::Result<Vec<Issue>> {
    let mut out = Vec::new();
    let Some(text) = s.text(CONTRACT)? else {
        return Ok(vec![(CONTRACT.into(), "index contract is missing".into())]);
    };
    for snippet in [
        "schema_version: tos_decision_index_contract_v1",
        "authority: docs/decisions/AGENTS.md",
        "source_records: docs/decisions/TOS-D-*.md",
        "generated_by: rust/crates/tos-ops-mechanics-plan/src/decision_records.rs",
        "pattern: TOS-D-####",
        "path_mode: full_canonical_id_filename",
    ] {
        if !text.contains(snippet) {
            issue(
                &mut out,
                CONTRACT,
                format!("missing contract snippet '{snippet}'"),
            )?;
        }
    }
    for path in INDEX_PATHS {
        if !text.contains(&format!("- {path}")) {
            issue(
                &mut out,
                CONTRACT,
                format!("missing generated index path {path}"),
            )?;
        }
    }
    Ok(out)
}
fn contract_list(
    s: &mut RouteSources,
    key: &str,
    out: &mut Vec<Issue>,
) -> io::Result<BTreeSet<String>> {
    let Some(text) = s.text(CONTRACT)? else {
        return Ok(BTreeSet::new());
    };
    let (mut in_list, mut seen) = (false, false);
    let mut values = BTreeSet::new();
    for line in splitlines(&text) {
        if line == format!("{key}: []") {
            return Ok(values);
        }
        if line == format!("{key}:") {
            seen = true;
            in_list = true;
            continue;
        }
        if in_list && line.starts_with("  - ") {
            values.insert(strip(&line[4..]).trim_matches(['\'', '"']).into());
            continue;
        }
        if in_list && !line.is_empty() && !line.starts_with(' ') {
            break;
        }
    }
    if !seen {
        issue(
            out,
            CONTRACT,
            format!("{key} must be a top-level list; use [] when empty"),
        )?;
    } else if values.is_empty() {
        issue(
            out,
            CONTRACT,
            format!("{key} must be a list, not null; use [] when empty"),
        )?;
    }
    Ok(values)
}
fn modeled(s: &mut RouteSources, out: &mut Vec<Issue>) -> io::Result<BTreeSet<String>> {
    let mut allowed = BTreeSet::new();
    let re = decision_re();
    for item in contract_list(s, "modeled_surfaces", out)? {
        let path = Path::new(&item);
        if path.is_absolute() || path.components().any(|c| matches!(c, Component::ParentDir)) {
            issue(
                out,
                CONTRACT,
                format!(
                    "modeled_surfaces entry must be a normalized repo-relative path under {DECISIONS_DIR}: {item}"
                ),
            )?;
            continue;
        }
        // pathlib removes redundant separators and current-directory parts
        // before inspecting the owner boundary; retain the authored item in
        // the allow-set, matching the maintained contract's exact membership.
        let normalized = path
            .components()
            .filter_map(|c| match c {
                Component::Normal(v) => v.to_str(),
                _ => None,
            })
            .collect::<Vec<_>>()
            .join("/");
        let path = Path::new(&normalized);
        if !path.starts_with(DECISIONS_DIR) {
            issue(
                out,
                CONTRACT,
                format!("modeled_surfaces entry must live under {DECISIONS_DIR}: {item}"),
            )?;
            continue;
        }
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if path.parent() == Some(Path::new(DECISIONS_DIR))
            && path.extension().is_some_and(|e| e == "md")
            && !STATIC.contains(&name)
            && !re.is_match(name)
        {
            issue(
                out,
                CONTRACT,
                format!("modeled_surfaces must not include root non-record Markdown: {item}"),
            )?;
            continue;
        }
        if !s.is_file(&item)? {
            issue(
                out,
                CONTRACT,
                format!("modeled_surfaces entry does not exist: {item}"),
            )?;
            continue;
        }
        allowed.insert(item);
    }
    Ok(allowed)
}
pub fn validate_decision_lane_surfaces(
    s: &mut RouteSources,
    cancel: &AtomicI32,
) -> io::Result<Vec<Issue>> {
    if !s.is_dir(DECISIONS_DIR)? {
        return Ok(vec![(
            DECISIONS_DIR.into(),
            "decision directory is missing".into(),
        )]);
    }
    let mut out = Vec::new();
    let mut allowed = modeled(s, &mut out)?;
    allowed.extend(INDEX_PATHS.iter().map(|p| p.to_string()));
    allowed.insert(CONTRACT.into());
    allowed.extend(STATIC.iter().map(|p| format!("{DECISIONS_DIR}/{p}")));
    let re = decision_re();
    for path in s.paths(DECISIONS_DIR)? {
        check(s, cancel)?;
        if !s.is_file(&path)? || allowed.contains(&path) {
            continue;
        }
        let p = Path::new(&path);
        if p.parent() == Some(Path::new(DECISIONS_DIR))
            && p.file_name()
                .and_then(|n| n.to_str())
                .is_some_and(|n| re.is_match(n))
        {
            continue;
        }
        issue(
            &mut out,
            &path,
            "unmodeled decision-lane surface; add it to modeled_surfaces in docs/decisions/indexes/index_contract.yaml or move it outside docs/decisions",
        )?;
    }
    Ok(out)
}
fn append(out: &mut Vec<Issue>, more: Vec<Issue>) -> io::Result<()> {
    for (p, m) in more {
        issue(out, &p, m)?;
    }
    Ok(())
}
pub fn run_validation(
    _root: &Path,
    s: &mut RouteSources,
    cancel: &AtomicI32,
) -> io::Result<Vec<Issue>> {
    let (records, mut out) = collect_decision_records(s, cancel)?;
    append(&mut out, validate_index_contract(s)?)?;
    append(&mut out, validate_decision_lane_surfaces(s, cancel)?)?;
    if records.is_empty() {
        issue(
            &mut out,
            DECISIONS_DIR,
            "no decision records available for validation",
        )?;
    }
    check(s, cancel)?;
    Ok(out)
}
fn add(text: &mut String, part: &str) -> io::Result<()> {
    if text
        .len()
        .checked_add(part.len())
        .is_none_or(|n| n > MAX_OUTPUT)
    {
        return Err(invalid("decision index output byte bound exceeded"));
    }
    text.push_str(part);
    Ok(())
}
fn link(r: &DecisionRecord) -> String {
    format!(
        "[{} - {}](../{})",
        r.decision_id,
        r.title,
        Path::new(&r.path)
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("")
    )
}
fn bullet(r: &DecisionRecord) -> String {
    format!("- {} (`{}`)", link(r), r.path)
}
fn grouped(
    title: &str,
    records: &[DecisionRecord],
    field: fn(&DecisionRecord) -> &[String],
) -> io::Result<String> {
    let mut groups: Vec<(String, Vec<&DecisionRecord>)> = Vec::new();
    let mut positions = BTreeMap::new();
    for r in records {
        for value in field(r) {
            let index = if let Some(i) = positions.get(value) {
                *i
            } else {
                let i = groups.len();
                positions.insert(value.clone(), i);
                groups.push((value.clone(), Vec::new()));
                i
            };
            groups[index].1.push(r);
        }
    }
    let mut keys = groups
        .into_iter()
        .map(|(name, records)| {
            let key =
                python_lower_unicode16_v1(&name, 65536, 65536, 262144).map_err(io::Error::other)?;
            Ok((key, name, records))
        })
        .collect::<io::Result<Vec<_>>>()?;
    keys.sort_by(|a, b| a.0.cmp(&b.0));
    let mut text = format!("# {title}\n\n{NOTE}");
    if text.len() > MAX_OUTPUT {
        return Err(invalid("decision index output byte bound exceeded"));
    }
    for (_, name, mut group) in keys {
        add(&mut text, &format!("\n\n## {name}\n"))?;
        group.sort_by(|a, b| a.decision_id.cmp(&b.decision_id));
        for r in group {
            add(&mut text, "\n")?;
            add(&mut text, &bullet(r))?;
        }
    }
    let len = text.trim_end_matches(python_space).len();
    text.truncate(len);
    add(&mut text, "\n")?;
    Ok(text)
}
/// Pure generated-companion seam, in the maintained builder's insertion order.
pub fn render_index_files(records: &[DecisionRecord]) -> io::Result<Vec<(String, String)>> {
    if records.len() > 4096 {
        return Err(invalid("decision record render count bound exceeded"));
    }
    let mut by_number = records.iter().collect::<Vec<_>>();
    by_number.sort_by(|a, b| a.number.cmp(&b.number));
    let mut by_date = records.iter().collect::<Vec<_>>();
    by_date.sort_by(|a, b| {
        (&a.original_date, &a.decision_id).cmp(&(&b.original_date, &b.decision_id))
    });
    let readme = format!(
        "# Decision Lookup Indexes\n\n{NOTE}\n\nThese files are generated read models from decision-note `Index Metadata`.\nDecision notes own rationale; these indexes only make lookup cheaper for agents.\n\n## Indexes\n\n- [By number](by-number.md)\n- [By date](by-date.md)\n- [By surface class](by-surface.md)\n- [By ToS layer](by-tos-layer.md)\n- [By tree class](by-tree-class.md)\n- [By validation or guard family](by-guard.md)\n"
    );
    let mut numbers = format!(
        "# Decisions By Number\n\n{NOTE}\n\n| Decision ID | Date | Decision | Path | Surface classes | ToS layers | Tree classes | Guard families | Posture |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n"
    );
    for r in by_number {
        let row = format!(
            "| {} | {} | {} | `{}` | {} | {} | {} | {} | {} |\n",
            r.decision_id,
            r.original_date,
            link(r),
            r.path,
            r.surface_classes.join(", "),
            r.tos_layers.join(", "),
            r.tree_classes.join(", "),
            r.guard_families.join(", "),
            r.posture
        );
        add(&mut numbers, &row)?;
    }
    let mut dates = format!("# Decisions By Date\n\n{NOTE}\n\n");
    let mut body = String::new();
    let days = by_date
        .iter()
        .map(|r| r.original_date.as_str())
        .collect::<BTreeSet<_>>();
    for day in days {
        add(&mut body, &format!("## {day}\n\n"))?;
        for r in by_date.iter().filter(|r| r.original_date == day) {
            add(&mut body, &bullet(r))?;
            add(&mut body, "\n")?;
        }
        add(&mut body, "\n")?;
    }
    add(&mut dates, body.trim_end_matches(python_space))?;
    add(&mut dates, "\n")?;
    let values = vec![
        readme,
        numbers,
        dates,
        grouped("Decisions By Surface Class", records, |r| {
            &r.surface_classes
        })?,
        grouped("Decisions By ToS Layer", records, |r| &r.tos_layers)?,
        grouped("Decisions By Tree Class", records, |r| &r.tree_classes)?,
        grouped("Decisions By Validation Or Guard Family", records, |r| {
            &r.guard_families
        })?,
    ];
    if values.iter().map(String::len).sum::<usize>() > MAX_OUTPUT {
        return Err(invalid(
            "decision index aggregate output byte bound exceeded",
        ));
    }
    Ok(INDEX_PATHS
        .iter()
        .zip(values)
        .map(|(p, t)| (p.to_string(), t))
        .collect())
}
/// The maintained native `--decision-index-build --check` validation seam.
pub fn run_index_validation(
    _root: &Path,
    s: &mut RouteSources,
    cancel: &AtomicI32,
) -> io::Result<Vec<Issue>> {
    let (records, mut out) = collect_decision_records(s, cancel)?;
    append(&mut out, validate_decision_lane_surfaces(s, cancel)?)?;
    append(&mut out, validate_index_contract(s)?)?;
    if !out.is_empty() {
        return Ok(out);
    }
    for (path, expected) in render_index_files(&records)? {
        check(s, cancel)?;
        if !s.is_file(&path)? {
            issue(&mut out, &path, "generated index is missing")?;
        } else if s.text(&path)?.as_deref() != Some(&expected) {
            issue(&mut out, &path, "generated index is stale")?;
        }
    }
    Ok(out)
}
/// Return reviewed builder inputs and generated bytes without mutating files.
/// The caller's owned builder route decides writing/checking and CLI framing.
pub fn build_indexes(
    s: &mut RouteSources,
    cancel: &AtomicI32,
) -> io::Result<(Vec<(String, String)>, Vec<Issue>)> {
    let (records, mut out) = collect_decision_records(s, cancel)?;
    append(&mut out, validate_decision_lane_surfaces(s, cancel)?)?;
    append(&mut out, validate_index_contract(s)?)?;
    check(s, cancel)?;
    if !out.is_empty() {
        return Ok((Vec::new(), out));
    }
    Ok((render_index_files(&records)?, out))
}
#[cfg(test)]
mod tests {
    use super::*;
    fn record() -> DecisionRecord {
        DecisionRecord {
            decision_id: "TOS-D-0001".into(),
            number: "0001".into(),
            title: "Example".into(),
            path: "docs/decisions/TOS-D-0001-example.md".into(),
            original_date: "2026-06-04".into(),
            surface_classes: vec!["Alpha".into(), "alpha".into()],
            tos_layers: vec!["docs".into()],
            tree_classes: vec!["none".into()],
            guard_families: vec!["source-first authority".into()],
            posture: "accepted".into(),
        }
    }
    #[test]
    fn iso_calendar_basic_and_week_contract() {
        for s in [
            "2026-06-04",
            "20260604",
            "2026-W23-4",
            "2026W234",
            "2026-W23",
            "2026W23",
            "2000-02-29",
            "2020-W53-7",
            "2026-W53",
        ] {
            assert!(iso_date(s), "{s}");
        }
        for s in [
            "2026-02-29",
            "1900-02-29",
            "0000-01-01",
            "2025-W53",
            "2026-W23-8",
            "9999-W52-7",
            "2026-154",
        ] {
            assert!(!iso_date(s), "{s}");
        }
    }
    #[test]
    fn generated_format_and_stable_lowercase_groups() {
        let records = vec![record()];
        let files = render_index_files(&records).unwrap();
        assert_eq!(files.len(), 7);
        assert!(
            files[1]
                .1
                .contains("| Decision ID | Date | Decision | Path |")
        );
        assert!(
            files[1]
                .1
                .contains("[TOS-D-0001 - Example](../TOS-D-0001-example.md)")
        );
        assert_eq!(
            files[2].1,
            format!(
                "# Decisions By Date\n\n{NOTE}\n\n## 2026-06-04\n\n- [TOS-D-0001 - Example](../TOS-D-0001-example.md) (`docs/decisions/TOS-D-0001-example.md`)\n"
            )
        );
        assert!(files[3].1.find("## Alpha").unwrap() < files[3].1.find("## alpha").unwrap());
        assert!(!files[3].1.contains("| Decision |"));
    }
    #[test]
    fn duplicate_metadata_keeps_last_and_python_whitespace() {
        let mut out = Vec::new();
        let meta=metadata("# X\n## Index Metadata\n- Decision ID: A\n- Decision ID: \u{a0}B\u{a0}\n## End\n- Decision ID: C\n","record",&mut out).unwrap();
        assert_eq!(meta["Decision ID"], "B");
        assert!(out.is_empty());
        assert_eq!(
            split_values(", \u{85}docs\u{85}, none,"),
            vec!["docs", "none"]
        );
    }
}
