//! Explicit native candidates for maintained route currentness and nested-card checks.
//! Authored inventory/cards retain authority; generated bytes prove no semantic admission.
use crate::executor::{self, Limits};
use regex::Regex;
use serde_json::{Value, json};
use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File};
use std::io::{self, Read, Write};
use std::path::{Component, Path, PathBuf};
use std::sync::{Arc, atomic::AtomicI32};
use std::time::{Duration, Instant};
use tos_foundation::{
    Digest256, JsonLimits, JsonMode, emit_python_compact_json, parse_json,
    python_lower_unicode16_v1,
};
use unicode_general_category::{GeneralCategory, get_general_category};

pub const INVENTORY: &str = "docs/validation/agents_route_inventory.json";
const MAX_FILE: usize = 8 * 1024 * 1024;
const MAX_INPUT: usize = 64 * 1024 * 1024;
const MAX_OUTPUT: usize = 16 * 1024 * 1024;
const MAX_ENTRIES: usize = 10_000;
const MAX_OPERATIONS: usize = 100_000;
const MAX_ISSUES: usize = 4096;
const DEFAULT_ROOTS: &[&str] = &[
    ".github",
    "ToS",
    "docs",
    "mechanics",
    "scripts",
    "tests",
    "evals",
    "memo",
    "kag",
    "stats",
    "manifests",
    ".agents",
];
pub type Issue = (String, String);
fn invalid(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, message.into())
}
pub fn sha256_bytes(bytes: &[u8]) -> String {
    Digest256::of_bytes(bytes).to_hex()
}
pub fn python_space(c: char) -> bool {
    matches!(c, '\u{9}'..='\u{d}' | '\u{1c}'..='\u{20}' | '\u{85}' | '\u{a0}' | '\u{1680}' | '\u{2000}'..='\u{200a}' | '\u{2028}' | '\u{2029}' | '\u{202f}' | '\u{205f}' | '\u{3000}')
}
pub fn whitespace_tokens(text: &str) -> usize {
    text.split(python_space).filter(|s| !s.is_empty()).count()
}
pub fn splitlines(text: &str) -> Vec<&str> {
    let mut out = Vec::new();
    let mut start = 0;
    let mut chars = text.char_indices().peekable();
    while let Some((i, c)) = chars.next() {
        if matches!(
            c,
            '\n' | '\r'
                | '\u{b}'
                | '\u{c}'
                | '\u{1c}'
                | '\u{1d}'
                | '\u{1e}'
                | '\u{85}'
                | '\u{2028}'
                | '\u{2029}'
        ) {
            out.push(&text[start..i]);
            start = i + c.len_utf8();
            if c == '\r' && chars.peek().is_some_and(|(_, c)| *c == '\n') {
                let (j, c) = chars.next().unwrap();
                start = j + c.len_utf8();
            }
        }
    }
    if start < text.len() {
        out.push(&text[start..]);
    }
    out
}
fn strings(value: &Value) -> io::Result<Vec<String>> {
    value
        .as_array()
        .filter(|a| a.len() <= 4096)
        .ok_or_else(|| invalid("expected bounded route array"))?
        .iter()
        .map(|v| {
            v.as_str()
                .filter(|s| s.len() <= 4096)
                .map(str::to_owned)
                .ok_or_else(|| invalid("expected bounded route string"))
        })
        .collect()
}
fn field<'a>(value: &'a Value, name: &str) -> io::Result<&'a str> {
    value
        .get(name)
        .and_then(Value::as_str)
        .ok_or_else(|| invalid(format!("expected route string: {name}")))
}
fn validate_relative(value: &str) -> io::Result<()> {
    if value.is_empty()
        || value.len() > 4096
        || value.contains('\0')
        || value.contains('\n')
        || Path::new(value).components().count() > 128
        || Path::new(value)
            .components()
            .any(|c| !matches!(c, Component::Normal(_) | Component::CurDir))
    {
        return Err(invalid(
            "route path must be bounded and repository relative",
        ));
    }
    Ok(())
}
struct SourceFile {
    raw: Vec<u8>,
    text: String,
    digest: String,
    raw_lines: usize,
    raw_tokens: usize,
    text_lines: usize,
    text_tokens: usize,
}
/// One operation's cached raw/text inputs and cumulative discovery/read deadline.
/// Raw cache is <=64MiB; normalized UTF-8 text occupies at most another64MiB.
/// Consumers copying bytes/text or constructing output must account for those copies.
pub struct RouteSources {
    root_dir: File,
    started: Instant,
    operations: usize,
    entries: usize,
    bytes_read: usize,
    files: BTreeMap<String, Arc<SourceFile>>,
}
impl RouteSources {
    pub fn new(root: &Path) -> io::Result<Self> {
        if root.as_os_str().len() > 4096
            || root.components().count() > 128
            || !root.is_absolute()
            || fs::canonicalize(root)? != root
            || !root.is_dir()
        {
            return Err(invalid("repository root must be absolute without symlinks"));
        }
        Ok(Self {
            root_dir: open_root(root)?,
            started: Instant::now(),
            operations: 0,
            entries: 0,
            bytes_read: 0,
            files: BTreeMap::new(),
        })
    }
    pub fn check(&self) -> io::Result<()> {
        if self.started.elapsed() > Duration::from_secs(30) {
            Err(invalid("route operation deadline exceeded"))
        } else {
            Ok(())
        }
    }
    fn charge(&mut self, value: &str) -> io::Result<()> {
        self.check()?;
        validate_relative(value)?;
        self.operations += 1;
        if self.operations > MAX_OPERATIONS {
            return Err(invalid("route lookup operation bound exceeded"));
        }
        Ok(())
    }
    // Each component is opened relative to a retained parent descriptor. The
    // final nofollow/nonblock open prevents FIFO waits and symlink races.
    #[cfg(target_os = "linux")]
    fn open(&mut self, value: &str) -> io::Result<Option<File>> {
        use std::os::fd::{AsRawFd, FromRawFd};
        self.charge(value)?;
        let parts: Vec<_> = Path::new(value)
            .components()
            .filter_map(|c| match c {
                Component::Normal(s) => Some(s),
                _ => None,
            })
            .collect();
        let mut dir = self.root_dir.try_clone()?;
        for (index, part) in parts.iter().enumerate() {
            use std::os::unix::ffi::OsStrExt;
            let name = std::ffi::CString::new(part.as_bytes()).map_err(|_| invalid("NUL path"))?;
            let flags = libc::O_RDONLY
                | libc::O_NOFOLLOW
                | libc::O_CLOEXEC
                | libc::O_NONBLOCK
                | if index + 1 < parts.len() {
                    libc::O_DIRECTORY
                } else {
                    0
                };
            let fd = unsafe { libc::openat(dir.as_raw_fd(), name.as_ptr(), flags) };
            if fd < 0 {
                let e = io::Error::last_os_error();
                if e.kind() == io::ErrorKind::NotFound {
                    return Ok(None);
                }
                return Err(e);
            }
            let next = unsafe { File::from_raw_fd(fd) };
            let meta = next.metadata()?;
            if !meta.is_file() && !meta.is_dir() {
                return Err(invalid("route input is not a regular file or directory"));
            }
            dir = next;
        }
        Ok(Some(dir))
    }
    #[cfg(not(target_os = "linux"))]
    fn open(&mut self, _value: &str) -> io::Result<Option<File>> {
        Err(io::Error::new(
            io::ErrorKind::Unsupported,
            "route reader requires Linux descriptor nofollow custody",
        ))
    }
    pub fn exists(&mut self, value: &str) -> io::Result<bool> {
        Ok(self.open(value)?.is_some())
    }
    pub fn is_file(&mut self, value: &str) -> io::Result<bool> {
        match self.open(value)? {
            Some(file) => Ok(file.metadata()?.is_file()),
            None => Ok(false),
        }
    }
    pub fn is_dir(&mut self, value: &str) -> io::Result<bool> {
        match self.open(value)? {
            Some(file) => Ok(file.metadata()?.is_dir()),
            None => Ok(false),
        }
    }
    fn source(&mut self, value: &str) -> io::Result<Option<Arc<SourceFile>>> {
        self.charge(value)?;
        if let Some(file) = self.files.get(value) {
            return Ok(Some(file.clone()));
        }
        let Some(file) = self.open(value)? else {
            return Ok(None);
        };
        let meta = file.metadata()?;
        if !meta.is_file() {
            return Ok(None);
        }
        if self.files.len() >= MAX_ENTRIES {
            return Err(invalid("route input file count exceeded"));
        }
        let cap = MAX_FILE.min(MAX_INPUT - self.bytes_read);
        if meta.len() > cap as u64 {
            return Err(invalid("route input byte bound exceeded"));
        }
        let mut raw = Vec::with_capacity(meta.len() as usize);
        file.take(cap as u64 + 1).read_to_end(&mut raw)?;
        if raw.len() > cap || raw.len() as u64 != meta.len() {
            return Err(invalid("route input changed or exceeded byte bound"));
        }
        self.bytes_read += raw.len();
        let text = std::str::from_utf8(&raw)
            .map_err(|_| invalid("route input is not UTF-8"))?
            .replace("\r\n", "\n")
            .replace('\r', "\n");
        if value.ends_with("AGENTS.md")
            && (line_count(&text) > 65_536
                || text.split(is_line_separator).any(|line| line.len() > 8192))
        {
            return Err(invalid("route card line byte bound exceeded"));
        }
        let raw_text = std::str::from_utf8(&raw).map_err(io::Error::other)?;
        let raw_lines = line_count(raw_text);
        let raw_tokens = whitespace_tokens(raw_text);
        let text_lines = line_count(&text);
        let text_tokens = whitespace_tokens(&text);
        let digest = sha256_bytes(&raw);
        let file = Arc::new(SourceFile {
            raw,
            text,
            digest,
            raw_lines,
            raw_tokens,
            text_lines,
            text_tokens,
        });
        self.files.insert(value.into(), file.clone());
        Ok(Some(file))
    }
    pub fn text(&mut self, value: &str) -> io::Result<Option<String>> {
        Ok(self.source(value)?.map(|v| v.text.clone()))
    }
    pub fn bytes(&mut self, value: &str) -> io::Result<Vec<u8>> {
        self.source(value)?
            .map(|v| v.raw.clone())
            .ok_or_else(|| invalid(format!("missing route file: {value}")))
    }
    /// Byte-only read for an explicit consumer-owned operand profile. This
    /// reuses descriptor custody without admitting bytes into the route text
    /// cache. The caller owns the local aggregate budget and operand fixity.
    pub fn bounded_bytes(
        &mut self,
        value: &str,
        max_file_bytes: usize,
        read_bytes: &mut usize,
        max_total_bytes: usize,
    ) -> io::Result<Vec<u8>> {
        let remaining = max_total_bytes
            .checked_sub(*read_bytes)
            .ok_or_else(|| invalid("operand aggregate byte accounting exceeded"))?;
        let cap = max_file_bytes.min(remaining);
        let file = self
            .open(value)?
            .ok_or_else(|| invalid(format!("missing operand file: {value}")))?;
        let meta = file.metadata()?;
        if !meta.is_file() {
            return Err(invalid("operand input is not a regular file"));
        }
        if meta.len() > cap as u64 {
            return Err(invalid("operand input byte bound exceeded"));
        }
        let mut raw = Vec::with_capacity(meta.len() as usize);
        let read_cap = u64::try_from(cap)
            .map_err(|_| invalid("operand read limit overflow"))?
            .checked_add(1)
            .ok_or_else(|| invalid("operand read limit overflow"))?;
        file.take(read_cap).read_to_end(&mut raw)?;
        if raw.len() > cap || raw.len() as u64 != meta.len() {
            return Err(invalid("operand input changed or exceeded byte bound"));
        }
        *read_bytes = read_bytes
            .checked_add(raw.len())
            .ok_or_else(|| invalid("operand aggregate byte accounting overflow"))?;
        self.check()?;
        Ok(raw)
    }
    pub fn inventory(&mut self) -> io::Result<Value> {
        let source = self
            .source(INVENTORY)?
            .ok_or_else(|| invalid("route inventory is missing"))?;
        json_preflight(&source.text)?;
        serde_json::from_str(&source.text)
            .map_err(|e| invalid(format!("route inventory is unreadable or malformed: {e}")))
    }
    fn walk(
        &mut self,
        rel: &str,
        paths: &mut BTreeSet<String>,
        all_descendants: bool,
    ) -> io::Result<()> {
        let Some(dir) = self.open(rel)? else {
            return Ok(());
        };
        if !dir.metadata()?.is_dir() {
            return Ok(());
        }
        // /proc/self/fd resolves our retained directory, not an authored pathname.
        #[cfg(target_os = "linux")]
        let path = {
            use std::os::fd::AsRawFd;
            PathBuf::from(format!("/proc/self/fd/{}", dir.as_raw_fd()))
        };
        #[cfg(not(target_os = "linux"))]
        let path: PathBuf = return Err(io::Error::new(
            io::ErrorKind::Unsupported,
            "route discovery requires Linux descriptor custody",
        ));
        let mut children = Vec::new();
        for entry in fs::read_dir(path)? {
            self.check()?;
            self.entries += 1;
            if self.entries > MAX_ENTRIES {
                return Err(invalid("route discovery entry bound exceeded"));
            }
            let entry = entry?;
            let kind = entry.file_type()?;
            if kind.is_symlink() {
                return Err(invalid("route discovery refuses symlinks"));
            }
            let name = entry
                .file_name()
                .into_string()
                .map_err(|_| invalid("non-UTF-8 route path"))?;
            let name = format!("{rel}/{name}");
            validate_relative(&name)?;
            children.push((name, kind.is_dir(), kind.is_file()));
        }
        children.sort_by(|a, b| a.0.cmp(&b.0));
        for (name, directory, file) in children {
            if all_descendants {
                paths.insert(name.clone());
            }
            if directory {
                self.walk(&name, paths, all_descendants)?;
            } else if !all_descendants
                && file
                && Path::new(&name)
                    .file_name()
                    .is_some_and(|n| n == "AGENTS.md")
            {
                paths.insert(name);
            }
        }
        Ok(())
    }
    /// Sorted descendants of one held directory, including files and directories.
    /// Enumeration reads no payload bytes and uses the same custody and limits as
    /// route-card discovery; the supplied directory itself is excluded.
    pub fn paths(&mut self, relative: &str) -> io::Result<Vec<String>> {
        let mut paths = BTreeSet::new();
        self.walk(relative, &mut paths, true)?;
        Ok(paths.into_iter().collect())
    }
    pub fn discover(&mut self, inventory: &Value) -> io::Result<Vec<String>> {
        let discovery = &inventory["route_card_discovery"];
        let mut cards = BTreeSet::new();
        for card in strings(&discovery["root_cards"])? {
            if self.is_file(&card)? {
                cards.insert(card);
            }
        }
        for root in strings(&discovery["route_roots"])? {
            self.walk(&root, &mut cards, false)?;
        }
        Ok(cards.into_iter().collect())
    }
    pub fn target_stack(
        &mut self,
        target: &str,
        discovered: &BTreeSet<String>,
    ) -> io::Result<Vec<String>> {
        let directory = self
            .open(target)?
            .is_some_and(|f| f.metadata().is_ok_and(|m| m.is_dir()));
        Ok(stack(target, directory, discovered, false))
    }
}
pub fn load_inventory(root: &Path) -> io::Result<Value> {
    RouteSources::new(root)?.inventory()
}
pub fn discover_route_cards(root: &Path, inventory: &Value) -> io::Result<Vec<String>> {
    RouteSources::new(root)?.discover(inventory)
}
pub fn target_inheritance_stack(
    root: &Path,
    target: &str,
    discovered: &BTreeSet<String>,
) -> io::Result<Vec<String>> {
    RouteSources::new(root)?.target_stack(target, discovered)
}
fn stack(
    target: &str,
    directory: bool,
    discovered: &BTreeSet<String>,
    include_card: bool,
) -> Vec<String> {
    let mut cursor = if directory {
        Path::new(target)
    } else {
        Path::new(target).parent().unwrap_or(Path::new(""))
    };
    let mut out = Vec::new();
    loop {
        let value = if cursor.as_os_str().is_empty() {
            "AGENTS.md".into()
        } else {
            format!("{}/AGENTS.md", cursor.to_string_lossy())
        };
        if discovered.contains(&value) {
            out.push(value);
        }
        let Some(parent) = cursor.parent() else { break };
        cursor = parent;
    }
    out.reverse();
    if include_card && !out.iter().any(|p| p == target) {
        out.push(target.into());
    }
    out
}
fn tracked(root: &Path, cancel: &AtomicI32) -> io::Result<Option<BTreeSet<String>>> {
    let limits = Limits {
        command_wall: Duration::from_secs(10),
        lane_wall: Duration::from_secs(10),
        cleanup_grace: Duration::from_secs(1),
        output_bytes: 4 * 1024 * 1024,
    };
    let (code, out, err) = executor::capture_ci_git(
        root,
        vec!["git".into(), "ls-files".into(), "--".into(), "*.md".into()],
        limits,
        cancel,
    )?;
    if code != 0 {
        let _ = err;
        return Ok(None);
    }
    let text = String::from_utf8(out).map_err(|_| invalid("Git output is not UTF-8"))?;
    let mut names = BTreeSet::new();
    for name in text.lines() {
        if name.len() > 4096 {
            return Err(invalid("Git path byte bound exceeded"));
        }
        if Path::new(name)
            .file_name()
            .is_some_and(|n| n == "AGENTS.md")
        {
            validate_relative(name)?;
            names.insert(name.into());
            if names.len() > MAX_ENTRIES {
                return Err(invalid("tracked route count exceeded"));
            }
        }
    }
    Ok(Some(names))
}
fn record(
    sources: &mut RouteSources,
    path: &str,
    role: &str,
    budget: &mut OutputBudget,
) -> io::Result<Value> {
    budget.reserve(1024)?;
    budget.text(path)?;
    budget.text(role)?;
    match sources.source(path)? {
        None => Ok(json!({"path":path,"role":role,"exists":false})),
        Some(file) => Ok(
            json!({"path":path,"role":role,"exists":true,"bytes":file.raw.len(),"lines":file.raw_lines,"whitespace_tokens":file.raw_tokens,"sha256":file.digest}),
        ),
    }
}
fn records(
    sources: &mut RouteSources,
    values: &Value,
    role: &str,
    budget: &mut OutputBudget,
) -> io::Result<Vec<Value>> {
    strings(values)?
        .iter()
        .map(|p| record(sources, p, role, budget))
        .collect()
}
fn entry_records(
    sources: &mut RouteSources,
    values: &Value,
    budget: &mut OutputBudget,
) -> io::Result<Vec<Value>> {
    values
        .as_array()
        .ok_or_else(|| invalid("expected entry array"))?
        .iter()
        .map(|e| record(sources, field(e, "path")?, field(e, "role")?, budget))
        .collect()
}
pub fn build_currentness(root: &Path, cancel: &AtomicI32) -> io::Result<Value> {
    let mut sources = RouteSources::new(root)?;
    let inventory = sources.inventory()?;
    let tracked = tracked(root, cancel)?.ok_or_else(|| invalid("git ls-files failed"))?;
    build_from_sources(&mut sources, &inventory, &tracked)
}
fn build_from_sources(
    s: &mut RouteSources,
    inventory: &Value,
    tracked: &BTreeSet<String>,
) -> io::Result<Value> {
    let mut budget = OutputBudget::new();
    budget.reserve(4096)?;
    for key in [
        "route_card_discovery",
        "context_budget",
        "scope_duplication_policy",
    ] {
        budget.value(&inventory[key])?;
    }
    for name in tracked {
        budget.text(name)?;
    }
    let cards = s.discover(inventory)?;
    let discovered: BTreeSet<_> = cards.iter().cloned().collect();
    let mut card_records = Vec::new();
    for path in &cards {
        let file = s
            .source(path)?
            .ok_or_else(|| invalid("discovered card disappeared"))?;
        budget.reserve(1024)?;
        budget.text(path)?;
        for ancestor in stack(path, false, &discovered, true) {
            budget.text(&ancestor)?;
        }
        card_records.push(json!({"path":path,"tracked":tracked.contains(path),"bytes":file.raw.len(),"lines":file.text_lines,"whitespace_tokens":file.text_tokens,"sha256":file.digest,"inheritance_stack":stack(path,false,&discovered,true)}));
    }
    let tasks = inventory["task_routes"]
        .as_array()
        .ok_or_else(|| invalid("expected task routes"))?;
    if tasks.len() > 4096 {
        return Err(invalid("route task bound exceeded"));
    }
    let mut task_records = Vec::new();
    for task in tasks {
        s.check()?;
        let target = field(task, "target")?;
        let owner = field(task, "owner_route")?;
        let inheritance = s.target_stack(target, &discovered)?;
        let mut inherited = 0;
        for p in &inheritance {
            if let Some(file) = s.source(p)? {
                inherited += file.text_tokens;
            }
        }
        budget.reserve(1024)?;
        budget.value(&task["id"])?;
        budget.text(target)?;
        budget.text(owner)?;
        for ancestor in &inheritance {
            budget.text(ancestor)?;
        }
        let owner_record = record(s, owner, "owner_handoff", &mut budget)?;
        let additional = records(s, &task["on_demand_surfaces"], "on_demand", &mut budget)?;
        task_records.push(json!({"id":task["id"],"target":target,"target_exists":s.is_file(target)?,"owner_route":owner,"owner_exists":s.is_file(owner)?,"inheritance_stack":inheritance,"inherited_context_tokens":inherited,"owner_in_inheritance_stack":inheritance.iter().any(|p|p==owner),"owner_handoff_context_tokens":if inheritance.iter().any(|p|p==owner){0}else{owner_record["whitespace_tokens"].as_u64().unwrap_or(0)},"owner_handoff":owner_record,"additional_context_tokens":additional.iter().map(|v|v["whitespace_tokens"].as_u64().unwrap_or(0)).sum::<u64>(),"on_demand_surfaces":additional,"validation_paths":records(s,&task["validation_paths"],"validation", &mut budget)?,"completion_evidence":records(s,&task["completion_evidence"],"completion", &mut budget)?}));
    }
    let value = json!({"schema_version":"tos_agents_route_currentness_v1","source_inventory":INVENTORY,"source_inventory_sha256":s.source(INVENTORY)?.ok_or_else(||invalid("route inventory disappeared"))?.digest,"generated_by":"scripts/build_agents_route_currentness.py","route_card_counts":{"tracked_exact_basename":tracked.len(),"discovered_by_inventory":discovered.len(),"tracked_only":tracked.difference(&discovered).collect::<Vec<_>>(),"discovered_untracked":discovered.difference(tracked).collect::<Vec<_>>()},"route_card_discovery":inventory["route_card_discovery"],"cards":card_records,"preserved_non_cards":entry_records(s,&inventory["route_card_discovery"]["preserved_non_cards"], &mut budget)?,"influencing_surfaces":entry_records(s,&inventory["influencing_surfaces"], &mut budget)?,"task_routes":task_records,"context_budget":inventory["context_budget"],"scope_duplication_policy":inventory["scope_duplication_policy"]});
    s.check()?;
    Ok(value)
}
struct BoundedOutput(Vec<u8>);
impl Write for BoundedOutput {
    fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
        if self.0.len().saturating_add(bytes.len()) > MAX_OUTPUT {
            return Err(invalid("route output byte bound exceeded"));
        }
        self.0.extend_from_slice(bytes);
        Ok(bytes.len())
    }
    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}
/// Python ensure_ascii=False, sort_keys=True, indent=2, including empty containers.
pub fn render_currentness(value: &Value) -> io::Result<String> {
    fn emit(w: &mut BoundedOutput, v: &Value, depth: usize) -> io::Result<()> {
        if depth > 128 {
            return Err(invalid("route output depth exceeded"));
        }
        let indent = |w: &mut BoundedOutput, n: usize| w.write_all(&vec![b' '; n * 2]);
        match v {
            Value::Object(m) if !m.is_empty() => {
                w.write_all(b"{\n")?;
                let mut keys: Vec<_> = m.keys().collect();
                keys.sort();
                for (i, k) in keys.iter().enumerate() {
                    indent(w, depth + 1)?;
                    serde_json::to_writer(&mut *w, k).map_err(io::Error::other)?;
                    w.write_all(b": ")?;
                    emit(w, &m[*k], depth + 1)?;
                    w.write_all(if i + 1 == keys.len() { b"\n" } else { b",\n" })?;
                }
                indent(w, depth)?;
                w.write_all(b"}")
            }
            Value::Array(a) if !a.is_empty() => {
                w.write_all(b"[\n")?;
                for (i, v) in a.iter().enumerate() {
                    indent(w, depth + 1)?;
                    emit(w, v, depth + 1)?;
                    w.write_all(if i + 1 == a.len() { b"\n" } else { b",\n" })?;
                }
                indent(w, depth)?;
                w.write_all(b"]")
            }
            Value::Number(n) => {
                let raw = n.to_string();
                let parsed = parse_json(
                    raw.as_bytes(),
                    JsonMode::RequestLastWins,
                    JsonLimits::default(),
                )
                .map_err(|e| invalid(format!("route JSON number: {e:?}")))?;
                let raw = emit_python_compact_json(parsed.root(), JsonLimits::default())
                    .map_err(|e| invalid(format!("route JSON number: {e:?}")))?;
                w.write_all(&raw)
            }
            _ => serde_json::to_writer(w, v).map_err(io::Error::other),
        }
    }
    let mut preflight = OutputBudget::new();
    preflight.value(value)?;
    let mut out = BoundedOutput(Vec::new());
    emit(&mut out, value, 0)?;
    out.write_all(b"\n")?;
    String::from_utf8(out.0).map_err(io::Error::other)
}

const BANNED_ROUTE_SECTION_MARKERS: &[&str] = &["## Stop Lines", "## Hard no"];

const ROLE_HEADINGS: &[&str] = &["## Role", "## Local role", "## What lives here"];

const ORIENTATION_HEADINGS: &[&str] = &[
    "## Read First",
    "## Read first",
    "## Read Before Editing",
    "## Read before editing",
    "## Applies To",
    "## Applies to",
    "This file applies",
    "This card applies",
];

const ROUTE_HEADINGS: &[&str] = &[
    "## Operating Card",
    "## Boundary Routes",
    "## Boundary Law",
    "## Boundaries",
    "## Boundary",
    "## Authority",
    "## Editing posture",
    "## Validation",
    "## Verify",
];

const README_INVENTORY_HEADINGS: &[&str] = &[
    "route inventory",
    "read first",
    "required reading",
    "route stack",
    "reading order",
    "start here",
    "read before editing",
];

const REQUIRED_REFERENCES: &[(&str, &[&str])] = &[
    (
        "AGENTS.md",
        &[
            "README.md",
            "VALIDATION.md",
            "ROADMAP.md",
            "BOUNDARIES.md",
            "ToS/",
            "mechanics/",
        ],
    ),
    (
        "ToS/AGENTS.md",
        &[
            "ToS/source_home.manifest.json",
            "ToS/doctrine/KNOWLEDGE_MODEL.md",
            "ToS/doctrine/NODE_CONTRACT.md",
        ],
    ),
    (
        "ToS/philosophy/AGENTS.md",
        &[
            "ToS/philosophy/",
            "ToS/research-packets/deep-research/philosophy/",
            "ToS/candidate-intake/",
            "ToS/canon/",
        ],
    ),
    (
        "docs/AGENTS.md",
        &[
            "docs/decisions/",
            "docs/RELEASING.md",
            "docs/AGENTS_ROOT_REFERENCE.md",
        ],
    ),
    (
        "docs/decisions/AGENTS.md",
        &[
            "TOS-D-####",
            "## Index Metadata",
            "docs/decisions/indexes/index_contract.yaml",
        ],
    ),
    (
        "mechanics/AGENTS.md",
        &[
            "mechanics/topology.json",
            "PARTS.md",
            "PROVENANCE.md",
            "ROADMAP.md",
        ],
    ),
    (
        "scripts/AGENTS.md",
        &[
            "docs/validation/validation_lanes.json",
            "scripts/release_check.py",
        ],
    ),
    (
        "tests/AGENTS.md",
        &["tests/test_inventory.json", "tests/VALIDATION.md"],
    ),
    ("evals/AGENTS.md", &["aoa-evals"]),
    (
        "stats/AGENTS.md",
        &["stats/port.manifest.json", "aoa-stats"],
    ),
];
const SPACE: &str = r"\x09-\x0D\x1C-\x20\x{85}\x{A0}\x{1680}\x{2000}-\x{200A}\x{2028}\x{2029}\x{202F}\x{205F}\x{3000}";
struct Patterns {
    fence: Regex,
    command: Regex,
    environment: Regex,
    inline: Regex,
    readme: Regex,
    condition: Regex,
    procedural: Regex,
    heading: Regex,
    bullet: Regex,
    script: Regex,
}
impl Patterns {
    fn new() -> io::Result<Self> {
        let re = |p: &str| {
            Regex::new(&p.replace(r"\s", &format!("[{SPACE}]"))).map_err(io::Error::other)
        };
        let tokens = r"(?:python(?:\d+(?:\.\d+)*)?|pytest|uv(?:[ \t]+run)?|pip(?:\d+)?|npm|npx|node|cargo|go|git|make|bash|sh|zsh|fish|powershell|pwsh|systemctl|journalctl|curl|wget|jq|rg|grep|sed|awk|find|chmod|mkdir|cp|mv|rm|docker|podman|env)";
        // Consumed boundary replaces Python lookahead. The special source
        // branch only needs the following argument's first character.
        let token = format!(r#"(?:{tokens}(?:[ \t`]|$)|source[ \t]+[./~$"'])"#);
        let assignment = r#"(?:[A-Z_][A-Z0-9_]*=(?:"[^"]*"|'[^']*'|[^\s]+)[ \t]+)"#;
        let lead = r"^[ \t]*(?:(?:[-*+][ \t]+|\d+[.)][ \t]+))?(?:`)?";
        Ok(Self {
            fence: re(r"^ {0,3}```")?,
            command: re(&format!(r"(?i){lead}(?:\$[ \t]+)?{assignment}*{token}"))?,
            environment: re(&format!(r"(?i){lead}{assignment}+{token}"))?,
            inline: re(&format!(r"(?i)^(?:\$[ \t]+)?{assignment}*{token}"))?,
            readme: re(r"(?i)(?:read|open|review|start\s+with|use)")?,
            condition: re(
                r"(?i)(?:(?:when|if|where|after|only|touched)|(?:as|when|if)\s+needed|(?:relevant|selected|known|target|named))",
            )?,
            procedural: re(
                r"(?i)^#{1,6}\s+(?:validation|verify|verification|checks?|testing|procedure|smoke)(?:\s|$)",
            )?,
            heading: re(r"^(#{1,6})\s+(.+?)\s*$")?,
            bullet: re(r"^(\s*)(?:[-*+]|\d+[.)])\s+")?,
            script: re(r#"((?:scripts|mechanics|\.agents)/[^\s`)'\"]+\.py)"#)?,
        })
    }
}

fn fold_ascii(text: &str) -> String {
    text.chars()
        .map(|c| match c {
            'İ' | 'ı' => 'i',
            'ſ' => 's',
            'K' => 'k',
            _ => c,
        })
        .collect()
}
fn strip(text: &str) -> &str {
    text.trim_matches(python_space)
}
fn normalize(text: &str) -> io::Result<String> {
    Ok(lower(text)?
        .split(python_space)
        .filter(|s| !s.is_empty())
        .collect::<Vec<_>>()
        .join(" "))
}
fn python_repr(text: &str) -> String {
    let quote = if text.contains('\'') && !text.contains('"') {
        '"'
    } else {
        '\''
    };
    let mut out = String::new();
    out.push(quote);
    for c in text.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if c == quote => {
                out.push('\\');
                out.push(c);
            }
            c if !python_printable(c) => {
                let point = c as u32;
                out.push_str(&if point < 256 {
                    format!("\\x{point:02x}")
                } else if point <= 0xffff {
                    format!("\\u{point:04x}")
                } else {
                    format!("\\U{point:08x}")
                });
            }
            c => out.push(c),
        }
    }
    out.push(quote);
    out
}
fn issue(issues: &mut Vec<Issue>, path: &str, message: impl Into<String>) -> io::Result<()> {
    let message = message.into();
    let previous = issues
        .iter()
        .try_fold(0usize, |total, (path, message)| {
            total.checked_add(path.len() + message.len() + 5)
        })
        .ok_or_else(|| invalid("route diagnostic byte overflow"))?;
    if issues.len() >= MAX_ISSUES
        || message.len() > 8192
        || previous.saturating_add(path.len() + message.len() + 5) > MAX_OUTPUT
    {
        return Err(invalid("route diagnostic bound exceeded"));
    }
    issues.push((path.into(), message));
    Ok(())
}
fn procedural_issues(
    path: &str,
    text: &str,
    inherited_validation: bool,
    p: &Patterns,
    issues: &mut Vec<Issue>,
) -> io::Result<()> {
    let lines = splitlines(text);
    let mut seen = BTreeSet::new();
    for (index, line) in lines.iter().enumerate() {
        let number = index + 1;
        let folded = fold_ascii(line);
        if p.fence.is_match(line) {
            issue(
                issues,
                path,
                format!("line {number}: fenced procedure/example is not allowed"),
            )?;
        }
        if p.environment.is_match(&folded) {
            issue(
                issues,
                path,
                format!("line {number}: environment-assignment command is not allowed"),
            )?;
        } else if p.command.is_match(&folded) {
            issue(
                issues,
                path,
                format!("line {number}: runnable command line is not allowed"),
            )?;
        }
        // Python's pattern can start at every backtick, including the closing
        // backtick of a preceding span. Keep each adjacent delimiter pair.
        let ticks: Vec<_> = folded.match_indices('`').map(|(i, _)| i).collect();
        if ticks
            .windows(2)
            .any(|pair| p.inline.is_match(&folded[pair[0] + 1..pair[1]]))
        {
            issue(
                issues,
                path,
                format!("line {number}: inline runnable command is not allowed"),
            )?;
        }
        if let Some(h) = p.heading.captures(line) {
            if !seen.insert((h[1].len(), normalize(&h[2])?)) {
                issue(
                    issues,
                    path,
                    format!("line {number}: repeated heading {}", python_repr(&h[2])),
                )?;
            }
        }
    }
    for (index, line) in lines.iter().enumerate() {
        if !p.procedural.is_match(&fold_ascii(line)) {
            continue;
        }
        let mut end = index + 1;
        while end < lines.len() && !p.heading.is_match(lines[end]) {
            end += 1;
        }
        if !lines[index + 1..end].iter().any(|s| !strip(s).is_empty()) {
            issue(
                issues,
                path,
                format!(
                    "line {}: empty procedural section {}",
                    index + 1,
                    python_repr(strip(line.trim_start_matches('#')))
                ),
            )?;
        }
    }
    for (index, line) in lines.iter().enumerate() {
        if !strip(line).ends_with(':') {
            continue;
        }
        let mut next = index + 1;
        while next < lines.len() && strip(lines[next]).is_empty() {
            next += 1;
        }
        if next == lines.len() {
            issue(
                issues,
                path,
                format!("line {}: orphan extraction lead-in before EOF", index + 1),
            )?;
            continue;
        }
        if p.heading.is_match(lines[next]) || p.fence.is_match(lines[next]) {
            issue(
                issues,
                path,
                format!(
                    "line {}: orphan extraction lead-in before structure",
                    index + 1
                ),
            )?;
        }
        if strip(lines[next]).ends_with(':') {
            issue(
                issues,
                path,
                format!("line {}: stacked colon lead-ins are not allowed", index + 1),
            )?;
        }
        if let (Some(a), Some(b)) = (p.bullet.captures(line), p.bullet.captures(lines[next])) {
            if a[1].chars().count() == b[1].chars().count() {
                issue(
                    issues,
                    path,
                    format!("line {}: same-level bullet lead-in has no body", index + 1),
                )?;
            }
        }
    }
    for (index, line) in lines.iter().enumerate() {
        let folded = fold_ascii(line);
        if has_readme_route(p, &folded) && !word_match(&p.condition, &folded) {
            issue(
                issues,
                path,
                format!("line {}: unconditional README inventory", index + 1),
            )?;
        }
    }
    for (index, line) in lines.iter().enumerate() {
        let Some(h) = p.heading.captures(line) else {
            continue;
        };
        if !README_INVENTORY_HEADINGS.contains(&strip(&lower(&h[2])?)) {
            continue;
        }
        let mut end = index + 1;
        while end < lines.len() && !p.heading.is_match(lines[end]) {
            end += 1;
        }
        let section = &lines[index + 1..end];
        let mut includes_readme = false;
        for item in section {
            includes_readme |= lower(item)?.contains("readme");
        }
        if includes_readme
            && !section
                .iter()
                .any(|s| word_match(&p.condition, &fold_ascii(s)))
        {
            issue(
                issues,
                path,
                format!("line {}: unconditional README inventory section", index + 1),
            )?;
        }
    }
    if !inherited_validation && !text.contains("VALIDATION.md") {
        issue(issues, path, "missing nearest validation route")?;
    }
    Ok(())
}
fn card_issues(
    s: &mut RouteSources,
    path: &str,
    text: &str,
    issues: &mut Vec<Issue>,
) -> io::Result<()> {
    if !strip(text).starts_with("# AGENTS.md") {
        issue(issues, path, "missing '# AGENTS.md' heading")?;
    }
    let compact = !splitlines(text).iter().any(|s| s.starts_with("## "))
        && (text.contains("This file applies") || text.contains("This card applies"));
    if !compact {
        for (headings, message) in [
            (ROLE_HEADINGS, "missing role or local scope heading"),
            (
                ORIENTATION_HEADINGS,
                "missing read/apply orientation heading",
            ),
            (
                ROUTE_HEADINGS,
                "missing route, boundary, or validation heading",
            ),
        ] {
            if !headings.iter().any(|h| text.contains(h)) {
                issue(issues, path, message)?;
            }
        }
    }
    for marker in BANNED_ROUTE_SECTION_MARKERS {
        if text.contains(marker) {
            issue(
                issues,
                path,
                format!("use Operating Card/Boundary Routes instead of {marker}"),
            )?;
        }
    }
    if text.contains("## Operating Card") {
        let mut fields = BTreeSet::new();
        for line in splitlines(text) {
            let line = strip(line);
            if !line.starts_with('|') || line.contains("---") {
                continue;
            }
            let cells: Vec<_> = line
                .trim_matches('|')
                .split('|')
                .map(|c| lower(strip(c).trim_matches('`')))
                .collect::<io::Result<Vec<_>>>()?;
            if cells.len() >= 2 && cells[0] != "field" {
                fields.insert(cells[0].clone());
            }
        }
        for field in ["input", "output", "owner", "next route"] {
            if !fields.contains(field) {
                issue(
                    issues,
                    path,
                    format!("Operating Card missing field: {field}"),
                )?;
            }
        }
        if !["check", "validation", "tools"]
            .iter()
            .any(|v| fields.contains(*v))
        {
            issue(
                issues,
                path,
                "Operating Card needs check, validation, or tools field",
            )?;
        }
    }
    if let Some((_, refs)) = REQUIRED_REFERENCES.iter().find(|(name, _)| *name == path) {
        for reference in *refs {
            if !text.contains(reference) {
                issue(
                    issues,
                    path,
                    format!("missing stable route reference: {reference}"),
                )?;
                continue;
            }
            if reference.ends_with('/')
                || matches!(*reference, "TOS-D-####" | "## Index Metadata" | "aoa-evals")
                || (!reference.contains('/') && !reference.starts_with('.'))
                || reference.starts_with("python ")
            {
                continue;
            }
            if !s.exists(reference)? {
                issue(
                    issues,
                    path,
                    format!("stable route reference points to missing path: {reference}"),
                )?;
            }
        }
    }
    Ok(())
}
fn inventory_issues(
    s: &mut RouteSources,
    inventory: &Value,
    cards: &[String],
    tracked: Option<&BTreeSet<String>>,
    issues: &mut Vec<Issue>,
) -> io::Result<()> {
    let required = [
        "schema_version",
        "owner_repo",
        "owner_surface",
        "validator",
        "currentness",
        "harness",
        "route_card_discovery",
        "influencing_surfaces",
        "context_budget",
        "scope_duplication_policy",
        "task_routes",
    ];
    let mut missing: Vec<_> = required
        .iter()
        .filter(|k| inventory.get(**k).is_none())
        .copied()
        .collect();
    missing.sort();
    if !missing.is_empty() {
        issue(
            issues,
            INVENTORY,
            format!("inventory missing fields: {}", missing.join(", ")),
        )?;
        return Ok(());
    }
    if inventory["schema_version"] != "tos_agents_route_inventory_v1" {
        issue(issues, INVENTORY, "unsupported route inventory schema")?;
    }
    for key in ["owner_surface", "validator", "currentness", "harness"] {
        let value = field(inventory, key)?;
        if !s.is_file(value)? {
            issue(
                issues,
                INVENTORY,
                format!("inventory reference points to missing path: {value}"),
            )?;
        }
    }
    let discovered: BTreeSet<_> = cards.iter().cloned().collect();
    let discovery = &inventory["route_card_discovery"];
    if let Some(tracked) = tracked {
        for value in tracked.difference(&discovered) {
            issue(
                issues,
                value,
                "tracked AGENTS.md is outside route-card inventory roots",
            )?;
        }
        for value in discovered.difference(tracked) {
            issue(issues, value, "discovered AGENTS.md is not tracked")?;
        }
    }
    if !strings(&discovery["root_cards"])?
        .iter()
        .any(|s| s == "AGENTS.md")
    {
        issue(
            issues,
            INVENTORY,
            "route inventory must name the root AGENTS.md",
        )?;
    }
    if !strings(&discovery["route_roots"])?
        .iter()
        .any(|s| s == ".github")
    {
        issue(
            issues,
            INVENTORY,
            "route inventory must include .github for tracked card parity",
        )?;
    }
    for card in cards {
        let ancestry = stack(card, false, &discovered, true);
        if ancestry.first().map(String::as_str) != Some("AGENTS.md") {
            issue(
                issues,
                card,
                "inheritance stack must begin at root AGENTS.md",
            )?;
        }
    }
    for card in cards {
        let ancestry = stack(card, false, &discovered, true);
        for ancestor in &ancestry[..ancestry.len().saturating_sub(1)] {
            if s.source(card)?.unwrap().raw == s.source(ancestor)?.unwrap().raw {
                issue(
                    issues,
                    card,
                    format!("byte-identical nested card duplicates {ancestor}"),
                )?;
            }
        }
    }
    for entry in discovery["preserved_non_cards"]
        .as_array()
        .ok_or_else(|| invalid("expected preserved array"))?
    {
        let value = entry.get("path").and_then(Value::as_str).unwrap_or("");
        if !s.is_file(value)? {
            issue(
                issues,
                INVENTORY,
                format!("preserved non-card is missing: {value}"),
            )?;
            continue;
        }
        let text = s.text(value)?.unwrap();
        if value == "docs/AGENTS_ROOT_REFERENCE.md"
            && (!text.contains("../AGENTS.md") || !text.contains("competing root"))
        {
            issue(
                issues,
                value,
                "preserved root reference must point to live root and reject competing-root authority",
            )?;
        }
    }
    for entry in inventory["influencing_surfaces"]
        .as_array()
        .ok_or_else(|| invalid("expected influencing array"))?
    {
        let value = field(entry, "path")?;
        if !s.exists(value)? {
            issue(
                issues,
                INVENTORY,
                format!("influencing surface is missing: {value}"),
            )?;
        }
    }
    let mut ids = BTreeSet::new();
    let tasks = inventory["task_routes"]
        .as_array()
        .ok_or_else(|| invalid("expected tasks"))?;
    if tasks.len() > 4096 {
        return Err(invalid("route task bound exceeded"));
    }
    for task in tasks {
        let id = task.get("id").and_then(Value::as_str).unwrap_or("");
        if id.len() > 4096 {
            return Err(invalid("route task ID byte bound exceeded"));
        }
        if id.is_empty() || !ids.insert(id) {
            issue(
                issues,
                INVENTORY,
                format!(
                    "task route id is missing or duplicated: {}",
                    if id.is_empty() { "<empty>" } else { id }
                ),
            )?;
        }
        for key in [
            "target",
            "owner_route",
            "on_demand_surfaces",
            "validation_paths",
            "completion_evidence",
            "handoff_routes",
        ] {
            let values = match task.get(key) {
                None => Vec::new(),
                Some(Value::String(v)) => vec![v.clone()],
                Some(v) => strings(v)?,
            };
            for value in values {
                if !value.is_empty() && !value.starts_with("aoa-") && !s.exists(&value)? {
                    issue(
                        issues,
                        INVENTORY,
                        format!("task {id} {key} points to missing path: {value}"),
                    )?;
                }
            }
        }
    }
    let current = field(inventory, "currentness")?;
    if !s.is_file(current)? {
        issue(
            issues,
            current,
            "generated AGENTS route currentness is missing",
        )?;
    } else {
        let expected = tracked
            .ok_or_else(|| invalid("Git unavailable for currentness"))
            .and_then(|t| build_from_sources(s, inventory, t))
            .and_then(|v| render_currentness(&v));
        match expected {
            Ok(expected) => {
                if s.text(current)?.as_deref() != Some(&expected) {
                    issue(
                        issues,
                        current,
                        "generated AGENTS route currentness is stale",
                    )?;
                }
            }
            Err(e) => issue(
                issues,
                current,
                format!("cannot verify generated currentness: {e}"),
            )?,
        }
    }
    Ok(())
}
/// The maintained diagnostic order: card shape, inventory/currentness, script refs,
/// then procedural structure. Malformed inventory falls back only for discovery.
pub fn run_validation(root: &Path, cancel: &AtomicI32) -> io::Result<Vec<Issue>> {
    let mut s = RouteSources::new(root)?;
    let inventory = s.inventory();
    if let Err(error) = &inventory {
        let message = error.to_string();
        if !message.starts_with("route inventory is missing")
            && !message.starts_with("route inventory is unreadable or malformed")
            && message != "route input is not UTF-8"
        {
            return Err(invalid(message));
        }
    }
    let discovery = inventory
        .as_ref()
        .ok()
        .filter(|v| v["route_card_discovery"]["route_roots"].is_array());
    let fallback =
        json!({"route_card_discovery":{"root_cards":["AGENTS.md"],"route_roots":DEFAULT_ROOTS}});
    // Validator uses fixed root AGENTS.md even if inventory root_cards differs.
    let mut discovery = match discovery {
        Some(value) => {
            let roots = strings(&value["route_card_discovery"]["route_roots"])?;
            json!({"route_card_discovery":{"root_cards":["AGENTS.md"],"route_roots":roots}})
        }
        None => fallback,
    };
    discovery["route_card_discovery"]["root_cards"] = json!(["AGENTS.md"]);
    let cards = s.discover(&discovery)?;
    let mut issues = Vec::new();
    let p = Patterns::new()?;
    for card in &cards {
        let text = s.text(card)?.ok_or_else(|| invalid("card disappeared"))?;
        card_issues(&mut s, card, &text, &mut issues)?;
    }
    match inventory {
        Ok(inventory) => {
            let tracked = tracked(root, cancel)?;
            inventory_issues(&mut s, &inventory, &cards, tracked.as_ref(), &mut issues)?;
        }
        Err(_) => {
            let message = if s.is_file(INVENTORY)? {
                "route inventory is unreadable or malformed"
            } else {
                "route inventory is missing"
            };
            issue(&mut issues, INVENTORY, message)?;
        }
    }
    for card in &cards {
        let text = s.text(card)?.unwrap();
        for m in p.script.find_iter(&text) {
            let before = text[..m.start()].chars().next_back();
            if before.is_some_and(|c| python_word(c) || matches!(c, '.' | '/')) {
                continue;
            }
            let reference = m.as_str().trim_end_matches(['.', ',', ':', ';']);
            if !s.is_file(reference)? {
                issue(
                    &mut issues,
                    card,
                    format!("local executable reference points to missing path: {reference}"),
                )?;
            }
        }
    }
    let discovered = cards.iter().cloned().collect();
    for card in &cards {
        let mut inherited = false;
        for ancestor in stack(card, false, &discovered, true) {
            inherited |= s
                .text(&ancestor)?
                .is_some_and(|t| t.contains("VALIDATION.md"));
        }
        procedural_issues(card, &s.text(card)?.unwrap(), inherited, &p, &mut issues)?;
        s.check()?;
    }
    Ok(issues)
}
/// Explicit bounded output destination, retaining nofollow directory descriptors.
/// Missing parents are created only under the caller's chosen destination.
pub fn write_output(root: &Path, path: &Path, rendered: &str) -> io::Result<()> {
    if rendered.len() > MAX_OUTPUT {
        return Err(invalid("route output byte bound exceeded"));
    }
    let path = if path.is_absolute() {
        path.to_owned()
    } else {
        root.join(path)
    };
    if path.as_os_str().len() > 4096
        || path
            .components()
            .any(|c| !matches!(c, Component::RootDir | Component::Normal(_)))
    {
        return Err(invalid("invalid route output path"));
    }
    #[cfg(target_os = "linux")]
    {
        use std::os::fd::{AsRawFd, FromRawFd};
        use std::os::unix::ffi::OsStrExt;
        use std::os::unix::fs::MetadataExt;
        let parts: Vec<_> = path
            .components()
            .filter_map(|c| {
                if let Component::Normal(s) = c {
                    Some(s)
                } else {
                    None
                }
            })
            .collect();
        if parts.is_empty() || parts.len() > 128 {
            return Err(invalid("invalid route output depth"));
        }
        let mut dir = File::open("/")?;
        for part in &parts[..parts.len() - 1] {
            let name =
                std::ffi::CString::new(part.as_bytes()).map_err(|_| invalid("NUL output path"))?;
            let mut fd = unsafe {
                libc::openat(
                    dir.as_raw_fd(),
                    name.as_ptr(),
                    libc::O_RDONLY | libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC,
                )
            };
            if fd < 0 && io::Error::last_os_error().kind() == io::ErrorKind::NotFound {
                if unsafe { libc::mkdirat(dir.as_raw_fd(), name.as_ptr(), 0o755) } < 0
                    && io::Error::last_os_error().kind() != io::ErrorKind::AlreadyExists
                {
                    return Err(io::Error::last_os_error());
                }
                fd = unsafe {
                    libc::openat(
                        dir.as_raw_fd(),
                        name.as_ptr(),
                        libc::O_RDONLY | libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC,
                    )
                };
            }
            if fd < 0 {
                return Err(io::Error::last_os_error());
            }
            dir = unsafe { File::from_raw_fd(fd) };
        }
        let name = std::ffi::CString::new(parts.last().unwrap().as_bytes())
            .map_err(|_| invalid("NUL output path"))?;
        let fd = unsafe {
            libc::openat(
                dir.as_raw_fd(),
                name.as_ptr(),
                libc::O_WRONLY
                    | libc::O_CREAT
                    | libc::O_NOFOLLOW
                    | libc::O_NONBLOCK
                    | libc::O_CLOEXEC,
                0o644,
            )
        };
        if fd < 0 {
            return Err(io::Error::last_os_error());
        }
        let mut file = unsafe { File::from_raw_fd(fd) };
        let meta = file.metadata()?;
        if !meta.is_file() || meta.len() > MAX_OUTPUT as u64 || meta.nlink() > 1 {
            return Err(invalid(
                "route output must be a bounded unshared regular file",
            ));
        }
        file.set_len(0)?;
        file.write_all(rendered.as_bytes())?;
        file.flush()
    }
    #[cfg(not(target_os = "linux"))]
    {
        let _ = path;
        Err(io::Error::new(
            io::ErrorKind::Unsupported,
            "route output requires Linux descriptor custody",
        ))
    }
}
/// Read an explicit external/relative output without following any component.
pub fn read_output(path: &Path) -> io::Result<Option<String>> {
    if !path.is_absolute() {
        return Err(invalid("output read requires absolute path"));
    }
    let relative = path
        .strip_prefix("/")
        .map_err(io::Error::other)?
        .to_str()
        .ok_or_else(|| invalid("non-UTF-8 output path"))?;
    let mut sources = RouteSources::new(Path::new("/"))?;
    let Some(file) = sources.open(relative)? else {
        return Ok(None);
    };
    let metadata = file.metadata()?;
    if !metadata.is_file() {
        return Ok(None);
    }
    if metadata.len() > MAX_OUTPUT as u64 {
        return Err(invalid("route output read byte bound exceeded"));
    }
    let mut raw = Vec::with_capacity(metadata.len() as usize);
    file.take(MAX_OUTPUT as u64 + 1).read_to_end(&mut raw)?;
    if raw.len() > MAX_OUTPUT || raw.len() as u64 != metadata.len() {
        return Err(invalid("route output changed or exceeded byte bound"));
    }
    let text = String::from_utf8(raw).map_err(io::Error::other)?;
    Ok(Some(text.replace("\r\n", "\n").replace('\r', "\n")))
}
#[cfg(target_os = "linux")]
fn open_root(root: &Path) -> io::Result<File> {
    use std::os::fd::{AsRawFd, FromRawFd};
    use std::os::unix::ffi::OsStrExt;
    let mut dir = File::open("/")?;
    for part in root.components() {
        if let Component::Normal(part) = part {
            let name =
                std::ffi::CString::new(part.as_bytes()).map_err(|_| invalid("NUL root path"))?;
            let fd = unsafe {
                libc::openat(
                    dir.as_raw_fd(),
                    name.as_ptr(),
                    libc::O_RDONLY | libc::O_DIRECTORY | libc::O_NOFOLLOW | libc::O_CLOEXEC,
                )
            };
            if fd < 0 {
                return Err(io::Error::last_os_error());
            }
            dir = unsafe { File::from_raw_fd(fd) };
        }
    }
    Ok(dir)
}
#[cfg(not(target_os = "linux"))]
fn open_root(_root: &Path) -> io::Result<File> {
    Err(io::Error::new(
        io::ErrorKind::Unsupported,
        "route source requires Linux descriptor custody",
    ))
}
/// Conservative pre-copy accounting for pretty JSON fields and containers.
/// The byte bound covers constructed logical output, not allocator/RSS overhead.
pub struct OutputBudget {
    used: usize,
}
impl Default for OutputBudget {
    fn default() -> Self {
        Self::new()
    }
}
impl OutputBudget {
    pub fn new() -> Self {
        Self { used: 0 }
    }
    pub fn reserve(&mut self, bytes: usize) -> io::Result<()> {
        self.used = self
            .used
            .checked_add(bytes)
            .filter(|n| *n <= MAX_OUTPUT)
            .ok_or_else(|| invalid("route pre-copy output budget exceeded"))?;
        Ok(())
    }
    pub fn text(&mut self, text: &str) -> io::Result<()> {
        self.reserve(
            text.len()
                .checked_mul(6)
                .and_then(|n| n.checked_add(258))
                .ok_or_else(|| invalid("route text size overflow"))?,
        )
    }
    pub fn value(&mut self, value: &Value) -> io::Result<()> {
        fn walk(b: &mut OutputBudget, v: &Value, depth: usize) -> io::Result<()> {
            if depth > 128 {
                return Err(invalid("route pre-copy output depth exceeded"));
            }
            b.reserve(258)?;
            match v {
                Value::String(s) => b.text(s)?,
                Value::Object(m) => {
                    for (k, v) in m {
                        b.text(k)?;
                        walk(b, v, depth + 1)?;
                    }
                }
                Value::Array(a) => {
                    for v in a {
                        walk(b, v, depth + 1)?;
                    }
                }
                Value::Number(n) => b.reserve(n.as_str().len().saturating_mul(6))?,
                _ => b.reserve(8)?,
            }
            Ok(())
        }
        walk(self, value, 0)
    }
}
fn is_line_separator(c: char) -> bool {
    matches!(
        c,
        '\n' | '\r'
            | '\u{b}'
            | '\u{c}'
            | '\u{1c}'
            | '\u{1d}'
            | '\u{1e}'
            | '\u{85}'
            | '\u{2028}'
            | '\u{2029}'
    )
}
fn line_count(text: &str) -> usize {
    let mut count = 0;
    let mut chars = text.chars().peekable();
    let mut trailing = false;
    while let Some(c) = chars.next() {
        trailing = is_line_separator(c);
        if trailing {
            count += 1;
            if c == '\r' && chars.peek() == Some(&'\n') {
                chars.next();
            }
        }
    }
    count + usize::from(!text.is_empty() && !trailing)
}
fn python_word(c: char) -> bool {
    c == '_'
        || matches!(
            get_general_category(c),
            GeneralCategory::UppercaseLetter
                | GeneralCategory::LowercaseLetter
                | GeneralCategory::TitlecaseLetter
                | GeneralCategory::ModifierLetter
                | GeneralCategory::OtherLetter
                | GeneralCategory::DecimalNumber
                | GeneralCategory::LetterNumber
                | GeneralCategory::OtherNumber
        )
}
fn word_boundary(text: &str, start: usize, end: usize) -> bool {
    !text[..start].chars().next_back().is_some_and(python_word)
        && !text[end..].chars().next().is_some_and(python_word)
}
fn word_match(pattern: &Regex, text: &str) -> bool {
    pattern
        .find_iter(text)
        .any(|m| word_boundary(text, m.start(), m.end()))
}
fn has_readme_route(p: &Patterns, text: &str) -> bool {
    let lower = text.to_ascii_lowercase();
    p.readme.find_iter(text).any(|action| {
        word_boundary(text, action.start(), action.end())
            && lower[action.end()..]
                .match_indices("readme")
                .any(|(index, _)| {
                    let start = action.end() + index;
                    word_boundary(text, start, start + 6)
                })
    })
}

fn lower(text: &str) -> io::Result<String> {
    python_lower_unicode16_v1(text, 8192, 16384, 32768)
        .map_err(|e| invalid(format!("route lowercase: {e:?}")))
}
fn python_printable(c: char) -> bool {
    c == ' '
        || !matches!(
            get_general_category(c),
            GeneralCategory::Control
                | GeneralCategory::Format
                | GeneralCategory::Surrogate
                | GeneralCategory::PrivateUse
                | GeneralCategory::Unassigned
                | GeneralCategory::LineSeparator
                | GeneralCategory::ParagraphSeparator
                | GeneralCategory::SpaceSeparator
        )
}
fn json_preflight(text: &str) -> io::Result<()> {
    let mut quoted = false;
    let mut escaped = false;
    let mut punctuation = 0usize;
    for byte in text.bytes() {
        if quoted {
            if escaped {
                escaped = false;
            } else if byte == b'\\' {
                escaped = true;
            } else if byte == b'"' {
                quoted = false;
            }
        } else if byte == b'"' {
            quoted = true;
        } else if matches!(byte, b'{' | b'}' | b'[' | b']' | b',' | b':') {
            punctuation += 1;
            if punctuation > 100_000 {
                return Err(invalid("route inventory structural token bound exceeded"));
            }
        }
    }
    Ok(())
}
