import {describe,it,expect} from 'vitest';
import {makeLensView,shortestPath} from './atlas-view.mjs';
const state={nodes:[{id:'a',materialId:'aa',kind:'fragment',position:[1,2,3]},{id:'b',materialId:'bb',kind:'concept',position:[10,20,3]},{id:'c',materialId:'cc',kind:'interpretation',position:[25,50,0]},{id:'d',materialId:'dd',kind:'question',position:[-20,30,2]}],edges:[{id:'e1',from:'a',to:'b',kind:'supports'},{id:'e2',from:'b',to:'c',kind:'interprets'},{id:'e3',from:'c',to:'d',kind:'contrasts'},{id:'e4',from:'d',to:'b',kind:'questions'}]};
const library={nodes:state.nodes.map(n=>({id:n.materialId,kind:n.kind,position:n.position,cluster:'one'})),atlas:{clusters:[{id:'one',color:'#cccccc'}]}};
describe('prepared tree view boundaries',()=>{
 it('changes the visible language of relations without mutating the saved graph',()=>{const before=JSON.stringify(state),view=makeLensView(state,library,{lens:'tensions'});expect(new Set(view.edges.map(e=>e.kind))).toEqual(new Set(['questions','contrasts']));expect(view.nodes.some(n=>n.id==='a')).toBe(false);expect(JSON.stringify(state)).toBe(before);expect(makeLensView(state,library).nodes).toHaveLength(4);});
 it('keeps a user position offset when another arrangement is selected',()=>{const moved=structuredClone(state);moved.nodes[1].position[0]+=39;const before=makeLensView(state,library,{lens:'sources'}).nodes.find(n=>n.id==='b');const after=makeLensView(moved,library,{lens:'sources'}).nodes.find(n=>n.id==='b');expect(after.position[0]-before.position[0]).toBe(39);});
 it('keeps an original draft position in a grouping lens',()=>{const withDraft=structuredClone(state);withDraft.nodes.push({id:'draft:one',kind:'question',position:[101,55,20],title:'My question'});const v=makeLensView(withDraft,library,{lens:'tensions'});expect(v.nodes.find(n=>n.id==='draft:one').position).toEqual([101,55,20]);});
 it('restricts a saved collection and neighborhood to their actual existing nodes',()=>{const view=makeLensView(state,library,{assembly:{nodeIds:['aa','bb','cc']},neighborhood:'b'});expect(view.nodes.map(n=>n.id)).toEqual(['a','b','c']);expect(view.edges.map(e=>e.id)).toEqual(['e1','e2']);});
 it('finds a real shortest traversal and honors selected relationship types',()=>{const path=shortestPath(state,'a','d');expect(path.nodeIds).toEqual(['a','b','d']);expect(path.edgeIds).toEqual(['e1','e4']);expect(shortestPath(state,'a','d',new Set(['interprets','contrasts']))).toBe(null);});
 it('never invents an endpoint when no graph path exists',()=>{expect(shortestPath(state,'a','missing')).toBe(null);const view=makeLensView(state,library,{path:shortestPath(state,'a','d')});expect(view.nodes.map(n=>n.id)).toEqual(['a','b','d']);expect(view.edges.every(e=>view.nodes.some(n=>n.id===e.from)&&view.nodes.some(n=>n.id===e.to))).toBe(true);});
 it('shows only the named transitions of a guided route without discarding adjacent saved edges',()=>{const before=JSON.stringify(state),view=makeLensView(state,library,{path:{nodeIds:['b','c','d'],edgeIds:['e2','e3'],restrictEdges:true}});expect(view.edges.map(e=>e.id)).toEqual(['e2','e3']);expect(view.edges.every(e=>e.highlight)).toBe(true);expect(JSON.stringify(state)).toBe(before);});
});
