import { NODE_CONTENT } from './atlas-content.mjs';
import { RESEARCH_ROUTES } from './atlas-routes.mjs';
import { bindInquiryLayer } from './inquiry-layer.mjs';
import { INQUIRY_FOUNDATION, LENS_INQUIRY } from './inquiry-foundation.mjs';
import { PRIMARY_SOURCES } from './source-references.mjs';

/**
 * A prepared, authored demonstration atlas. These annotations and comparisons
 * are not quotations, source admission, canon, or evidence of historical influence.
 * Original library nodes are retained; source text comes only from that library.
 */
const bi = (ru, en) => ({ ru, en });
const demoId = (slug) => 'demo:' + slug;
const sourceIds = ['work', 'chapter-p3.r2', 'moment', 'chapter-p3.r13', 'all-things', 'same-life', 'dossier'];
const clusterData = [
  ['sources', 'Источники', 'Sources', 'Текст, голоса и соседние строки', 'Text, voices and surrounding passages', '#c5ba92', [-300, -155, -35]],
  ['images', 'Образы', 'Images', 'Ворота, круг, укус и смех', 'Gateway, circle, bite and laughter', '#d99b6c', [0, -165, 25]],
  ['concepts', 'Понятия', 'Concepts', 'Время, необходимость и утверждение', 'Time, necessity and affirmation', '#b6abd8', [290, -120, -10]],
  ['readings', 'Прочтения', 'Readings', 'Несколько входов в один текст', 'Several ways into one text', '#77b8ab', [-280, 120, 40]],
  ['tensions', 'Вопросы', 'Questions', 'Места, где мысль сопротивляется', 'Where thought meets resistance', '#d4899d', [0, 130, -15]],
  ['echoes', 'Переклички', 'Resonances', 'Сопоставления через границы учений', 'Comparisons across philosophical traditions', '#82aacc', [300, 135, 30]],
];
const sourceNote = bi(
  'Демонстрационный материал: авторское толкование, пересказ или сопоставление для макета. Не цитата и не принятый источник или канон ToS.',
  'Demonstration material: an authored interpretation, paraphrase or comparison for this mockup. Not a quotation or an admitted ToS source or canon.',
);


function makeNodes() {
  // Node identity and placement live here; authored prose lives in NODE_CONTENT.
  const rows = [
    ["narrated-voices","note","sources","Кто здесь говорит?","Who is speaking?",[]],
    ["source-neighbor","note","sources","Прочитать соседние строки","Read the surrounding passage",[]],
    ["local-return","excerpt","sources","Возвращение к людям","Returning to people",[]],
    ["gateway","symbol","images","Ворота «Мгновенье»","The gateway “Moment”",[]],
    ["two-paths","symbol","images","Две дороги","Two paths",[]],
    ["dwarf","character","images","Карлик у ворот","The dwarf at the gateway",[]],
    ["circle","symbol","images","Круг времени","The circle of time",[]],
    ["wheel","symbol","images","Колесо","The wheel",[]],
    ["animals","character","images","Звери и их песня","The animals and their song",[]],
    ["nausea","symbol","images","Отвращение","Nausea",[]],
    ["shepherd","character","images","Пастух и змея","The shepherd and the serpent",[]],
    ["bite","symbol","images","Укус","The bite",[]],
    ["laughter","symbol","images","Преображённый смех","Transformed laughter",[]],
    ["ring","symbol","images","Кольцо","The ring",[]],
    ["dance","symbol","images","Танец","Dance",[]],
    ["recurrence","concept","concepts","Вечное возвращение","Eternal recurrence",[]],
    ["becoming","concept","concepts","Становление","Becoming",[]],
    ["present","concept","concepts","Настоящий миг","The present moment",[]],
    ["affirmation","concept","concepts","Утверждение жизни","Affirmation of life",[]],
    ["identity","concept","concepts","Та же самая жизнь","The very same life",[]],
    ["fate","concept","concepts","Судьба","Fate",[]],
    ["agency","concept","concepts","Способность действовать","Agency",[]],
    ["necessity","concept","concepts","Необходимость","Necessity",[]],
    ["creation","concept","concepts","Созидание","Creation",[]],
    ["memory","concept","concepts","Память","Memory",[]],
    ["difference","concept","concepts","Различие","Difference",[]],
    ["amor-fati","concept","concepts","Amor fati · любовь к судьбе","Amor fati · love of fate",["https://projekt-gutenberg.org/authors/friedrich-wilhelm-nietzsche/books/die-froehliche-wissenschaft/chapter/7/"]],
    ["cosmological","interpretation","readings","Гипотеза о мире","A hypothesis about the world",[]],
    ["existential","interpretation","readings","Испытание собственной жизни","Testing one’s own life",[]],
    ["poetic","interpretation","readings","Мыслить образами","Thinking through images",[]],
    ["temporal-knot","interpretation","readings","Миг как узел времени","The moment as a knot of time",[]],
    ["voice-reading","interpretation","readings","Чтение по голосам","Reading by voice",[]],
    ["performative","interpretation","readings","Мысль как способ жить","Thought as a way of living",[]],
    ["selective","interpretation","readings","Повторить только счастливое?","Repeat only the happy parts?",[]],
    ["small-human","interpretation","readings","Возвращение малого человека","The return of the small human",[]],
    ["nonlinear","interpretation","readings","Время без прямой линии","Time without a straight line",[]],
    ["form-content","interpretation","readings","Форма несёт мысль","Form carries thought",[]],
    ["task","interpretation","readings","Трудность учительства","The difficulty of teaching",[]],
    ["open-reading","interpretation","readings","Удержать несколько прочтений","Keep several readings open",[]],
    ["fatalism","question","tensions","Принятие — это бездействие?","Does acceptance mean inaction?",[]],
    ["same-new","question","tensions","Как возможно новое?","How is novelty possible?",[]],
    ["circle-change","question","tensions","Круг отменяет изменение?","Does the circle cancel change?",[]],
    ["free-necessary","question","tensions","Свобода внутри необходимости","Freedom within necessity",[]],
    ["joy-pain","question","tensions","Можно ли принять целое с болью?","Can a whole be affirmed with its pain?",[]],
    ["teach-live","question","tensions","Сказать или выдержать?","To say it or to endure it?",[]],
    ["human-overcoming","question","tensions","Что значит преодолеть человека?","What does overcoming the human mean?",[]],
    ["proposition-poem","question","tensions","Тезис или поэма?","Thesis or poem?",[]],
    ["character-author","question","tensions","Персонаж говорит за автора?","Does a character speak for the author?",[]],
    ["again-memory","question","tensions","Кто узнает возвращение?","Who would recognise the return?",[]],
    ["whole-part","question","tensions","Целое и выбранный миг","The whole and the chosen moment",[]],
    ["cosmos-evidence","question","tensions","Что могло бы служить основанием?","What could provide grounds?",[]],
    ["heraclitus","figure","echoes","Гераклит","Heraclitus",["https://en.wikisource.org/wiki/Fragments_of_Heraclitus"]],
    ["stoics","tradition","echoes","Стоическая перспектива","A Stoic perspective",["https://classics.mit.edu/Epictetus/epicench.html","https://classics.mit.edu/Antoninus/meditations.6.six.html"]],
    ["providence","concept","echoes","Промысл и порядок","Providence and order",["https://classics.mit.edu/Antoninus/meditations.6.six.html"]],
    ["epictetus","figure","echoes","Эпиктет","Epictetus",["https://classics.mit.edu/Epictetus/epicench.html"]],
    ["spinoza","figure","echoes","Спиноза","Spinoza",["https://www.gutenberg.org/files/3800/3800-h/3800-h.htm"]],
    ["conatus","concept","echoes","Conatus · стремление существовать","Conatus · striving to persist",["https://www.gutenberg.org/files/3800/3800-h/3800-h.htm"]],
    ["leibniz","figure","echoes","Лейбниц","Leibniz",["https://www.earlymoderntexts.com/assets/pdfs/leibniz1714b.pdf"]],
    ["possible-worlds","concept","echoes","Другие возможные миры","Other possible worlds",["https://www.earlymoderntexts.com/assets/pdfs/leibniz1714b.pdf"]],
    ["kierkegaard","figure","echoes","Кьеркегор","Kierkegaard",["https://classiques.uqam.ca/classiques/Kierkegaard_Soren/La_repetition/Repetition.pdf"]],
    ["repetition","concept","echoes","Повторение и возобновление","Repetition and renewal",["https://classiques.uqam.ca/classiques/Kierkegaard_Soren/La_repetition/Repetition.pdf"]],
    ["camus","figure","echoes","Камю","Camus",["https://thephilosopher.net/camus/wp-content/uploads/sites/94/2024/11/The-Myth-Of-Sisyphus-And-Other-Essays-Albert-Camus.pdf"]],
    ["sisyphus","symbol","echoes","Камень Сизифа","Sisyphus’s stone",["https://thephilosopher.net/camus/wp-content/uploads/sites/94/2024/11/The-Myth-Of-Sisyphus-And-Other-Essays-Albert-Camus.pdf"]],
    ["deleuze","figure","echoes","Делёз","Deleuze",["https://blogs.law.columbia.edu/nietzsche1313/files/2016/11/Deleuze-complet.pdf"]],
    ["return-difference","interpretation","echoes","Возвращение различия","The return of difference",["https://blogs.law.columbia.edu/nietzsche1313/files/2016/11/Deleuze-complet.pdf"]],
    ["decision","question","tensions","Решение внутри заданного","A decision within given conditions",[]],
    ["counterfactual","concept","concepts","«Я мог бы иначе»","“I could have done otherwise”",[]],
    ["responsibility","question","tensions","Ответственность за ответ","Responsibility for a response",[]],
    ["lived-rhythm","interpretation","readings","Проживаемый ритм","Lived rhythm",[]],
    ["body-resistance","question","images","Тело не согласно","The body resists",[]],
    ["return-practice","note","readings","Вернуться к тому же абзацу","Return to the same paragraph",[]],
    ["remembered-return","question","concepts","Повтор или узнавание?","Repetition or recognition?",[]],
    ["attention","concept","concepts","Внимание меняет встречу","Attention changes the encounter",[]],
    ["shared-world","question","tensions","Чья жизнь входит в целое?","Whose life belongs to the whole?",[]],
  ];
  return rows.map(([slug, kind, cluster, ru, en, sourceRefs]) => ({ id: demoId(slug), kind, parentId: null, title: bi(ru, en), demo: true, cluster, sourceRefs, sourceNote }));
}

const resolveId = (id) => sourceIds.includes(id) ? id : demoId(id);
function makeEdges() {
  const rows = [
    ["dossier","work","interprets","Собрать места вместе","Bring passages together","Вопросы у ворот и речь зверей после болезни дают возвращению разные положения внутри книги. Подборка делает их сопоставимыми в одном чтении.","The gateway questions and the animals’ speech after illness place recurrence differently within the book. The dossier brings them into one reading."],
    ["moment","gateway","supports","От строки к образу","From passage to image","Надпись «Мгновение» принадлежит воротам с двумя лицами. Настоящее сначала появляется как место встречи направлений.","The inscription “Moment” belongs to a gateway with two faces. The present first appears as a meeting place of directions."],
    ["moment","two-paths","supports","Развернуть сцену","Unfold the scene","Обе дороги уходят в вечность. Вопрос Заратустры о том, что произойдёт при дальнейшем движении, превращает их встречу в загадку возвращения.","Both paths extend into eternity. Zarathustra’s question about following them further turns their meeting into recurrence’s enigma."],
    ["chapter-p3.r2","dwarf","supports","Кто отвечает","Who answers","Карлик давит предсказанием падения и отвечает формулой кругового времени. Возражение Заратустры связывает эти два появления духа тяжести.","The dwarf weighs down with a prediction of falling and answers with circular time. Zarathustra’s objection connects these appearances of the spirit of gravity."],
    ["chapter-p3.r2","shepherd","supports","Загадка становится сценой","The riddle becomes a scene","Между воротами и пастухом находятся вой собаки и детское воспоминание. Рассказчик просит разгадать видение: переход ещё требует прочтения.","A dog’s howl and childhood recollection intervene between gateway and shepherd. The narrator asks that the vision be interpreted; the transition still calls for a reading."],
    ["shepherd","bite","develops","Прервать удушье","Break the choking","Рука Заратустры не вытягивает змею, но его крик побуждает пастуха укусить. Помощь меняет форму в момент передачи самого действия.","Zarathustra’s hand cannot extract the snake, but his cry moves the shepherd to bite. Help changes form as the act passes to the shepherd."],
    ["bite","laughter","develops","Переход к преображению","A passage to transformation","После укуса пастух назван преображённым. Его неслыханный смех становится собственным желанием рассказчика и меняет финальный вопрос о жизни и смерти.","After the bite, the shepherd is called transformed. His unprecedented laughter becomes the narrator’s own longing and changes the closing question about life and death."],
    ["chapter-p3.r13","animals","supports","Различить голос зверей","Distinguish the animals’ voice","Звери заботятся о выздоравливающем, поют о мире и называют его учителем возвращения. Их объяснение принадлежит этой встрече.","The animals care for the convalescent, sing of the world and name him recurrence’s teacher. Their explanation belongs to this encounter."],
    ["chapter-p3.r13","nausea","supports","Предмет отвращения","Disgust’s object","Заратустра называет предмет отвращения: возвращение малого человека. Рассказ о болезни раскрывает конкретную трудность всеобщей формулы.","Zarathustra names disgust’s object: the small human’s return. The illness account reveals the universal formula’s particular difficulty."],
    ["all-things","recurrence","supports","Текстовый вход","A textual entry","Умирание, расцвет, распад и соединение образуют ход песни зверей. Возвращение целого охватывает в ней сами изменения.","Dying, blossoming, dissolution and reunion form the animals’ song. The whole’s recurrence encompasses changes themselves."],
    ["same-life","identity","supports","Именно эта жизнь","This very life","Звери исключают новую, лучшую и лишь похожую жизнь. Эти исключения задают строгость возвращения к той же жизни в большом и малом.","The animals exclude a new, better or merely similar life. These exclusions specify the same life’s return in large and small details."],
    ["same-life","whole-part","develops","Без изъятия эпизодов","Without removing episodes","В §341 возвращаются не только главные события, но мысли, вздохи и их порядок. Полнота жизни включает её подробности и последовательность.","In §341, thoughts, sighs and their order return alongside major events. Life’s completeness includes its details and sequence."],
    ["all-things","animals","supports","Проверить говорящего","Check the speaker","После песни следует ответ Заратустры о шарманке и рассказ об отвращении. Возврат к говорящим возвращает формуле её место в разговоре.","The song is followed by Zarathustra’s barrel-organ reply and disgust account. Restoring the speakers restores the formula’s conversational place."],
    ["narrated-voices","character-author","develops","Реплика или позиция?","Line or position?","Звери воображают будущую предсмертную речь Заратустры; герой остаётся молчать. Авторская атрибуция должна объяснить именно эту речевую рамку.","The animals imagine Zarathustra’s future dying speech; he remains silent. Authorial attribution must explain this particular speech frame."],
    ["source-neighbor","voice-reading","supports","Услышать ответ","Hear the response","Соседняя реплика показывает, к кому обращена формула и как она услышана. В «Выздоравливающем» ответ о песне меняет чтение уверенных слов зверей.","The neighbouring reply shows whom a formula addresses and how it is heard. In “The Convalescent,” the reply about song changes the animals’ assured words."],
    ["local-return","recurrence","contrasts","Два смысла возвращения","Two senses of return","Возвращение к людям в «Предисловии» рождается из изменившегося сердца и потребности отдавать. Та же жизнь в речи зверей задаёт другой объём повторения.","Returning to people in the Prologue arises from a changed heart and a need to give. The animals’ same life specifies another scope of recurrence."],
    ["work","local-return","supports","От избытка к нисхождению","From abundance to descent","Обращение к солнцу, избыток мёда и чаша, желающая опустеть, направляют Заратустру к людям. Начало книги связывает нисхождение с отдачей.","The address to the sun, surplus honey and a cup wanting to empty direct Zarathustra toward people. The book’s opening connects descent with giving."],
    ["dossier","open-reading","develops","От подборки к сравнению","From collection to comparison","Формула карлика, вопросы Заратустры и песня зверей дают общие места для разных прочтений. Их сопоставление начинается с различий между этими речами.","The dwarf’s formula, Zarathustra’s questions and the animals’ song give different readings shared passages. Comparison begins from differences between these speeches."],
    ["narrated-voices","source-neighbor","develops","Вернуться к контексту","Return to context","После слов о возвращении нужно прочитать ответ героя и переход к его рассказу. Атрибуция ведёт к отношениям между репликами.","After recurrence’s words, read the protagonist’s reply and the transition to his account. Attribution leads into relations between speeches."],
    ["gateway","present","develops","Место встречи времён","Where times meet","Два лица ворот обращены к противоположным вечным дорогам. Надпись «Мгновение» помещает настоящее внутри вопроса об их связи.","The gateway’s two faces turn toward opposed eternal paths. “Moment” places the present within the question of their connection."],
    ["two-paths","temporal-knot","supports","Пересечение как узел","A crossing as a knot","Заратустра спрашивает, связаны ли все вещи так крепко, что мгновение влечёт всё грядущее. Образ узла развивается из этого вопроса о связанности.","Zarathustra asks whether things are bound so firmly that the moment draws all future things after it. The knot image develops from this question of connection."],
    ["dwarf","circle","develops","Краткий ответ","A compact answer","Карлик называет само время кругом. Заратустра возражает против лёгкости ответа и продолжает спрашивать о конкретном мгновении.","The dwarf calls time itself a circle. Zarathustra objects to the answer’s ease and continues asking about this particular moment."],
    ["circle","cosmological","supports","Представить повтор мира","Imagine world repetition","После круга времени появляются вопросы о пауке, лунном свете и возвращении самих собеседников. Космологический вопрос получает конкретный состав.","After circular time come questions about the spider, moonlight and the interlocutors’ own return. The cosmological question acquires particular contents."],
    ["dwarf","voice-reading","supports","Учитывать дистанцию","Attend to distance","Формулу круга произносит карлик, а её лёгкость отвергает Заратустра. Это различие голосов участвует в том, как глава ставит вопрос.","The dwarf utters the circle formula and Zarathustra rejects its ease. This difference of voices participates in how the chapter poses its question."],
    ["wheel","recurrence","interprets","Движение с повтором","Movement with repetition","Колесо существования катится в песне между умиранием и новым расцветом. Оно изображает возвращение через движение становления.","Existence’s wheel rolls in the song between dying and renewed blossoming. It figures recurrence through becoming’s movement."],
    ["animals","cosmological","develops","Мир в песенной формуле","A world in a sung formula","Звери объясняют великий год и одинаковую последовательность больших и малых событий. Затем они воображают возвращение самого Заратустры.","The animals explain the great year and the same sequence of large and small events. They then imagine Zarathustra’s own return."],
    ["nausea","joy-pain","develops","Отвращение и желание всего","Disgust and desire for everything","Отвращение направлено на возвращение малого человека; в «Песни опьянения» радость хочет вечности всего. Сравнение спрашивает о ходе от этой трудности к такому желанию.","Disgust concerns the small human’s return; in “The Drunken Song,” joy wants everything’s eternity. Comparison asks after the movement from this difficulty to that desire."],
    ["bite","creation","interprets","Действие меняет форму","Action changes form","Укус завершает невозможную для протянутой руки помощь и открывает преображение. Рядом с ребёнком из «Трёх превращений» он ставит вопрос о действии, начинающем новое.","The bite completes what the outstretched hand cannot and opens transformation. Beside the child in “The Three Metamorphoses,” it asks about an act beginning anew."],
    ["laughter","affirmation","interprets","Изменение отношения","A changed relation","Смех преображённого пастуха вызывает у Заратустры желание услышать его снова. Утверждение прочитывается через эту перемену желания рассказчика.","The transformed shepherd’s laughter makes Zarathustra long to hear it again. Affirmation is read through this change in the narrator’s desire."],
    ["ring","whole-part","interprets","Связность целого","The whole’s connection","Семь разных условных строф сходятся в признании любви к вечности. Возвращающийся припев связывает их в одно повторяемое желание.","Seven different conditional stanzas converge on love for eternity. The returning refrain connects them in one repeated desire."],
    ["dance","performative","supports","Понимать движением","Understand through movement","Шестая печать делает тяжёлое лёгким через добродетель танцора; седьмая переводит речь в пение. Форма участвует в выражении желания вечности.","The sixth seal makes heaviness light through the dancer’s virtue; the seventh turns speech into singing. Form participates in expressing desire for eternity."],
    ["gateway","nonlinear","supports","Выйти из прямой","Leave the straight line","От надписи «Мгновение» чтение расходится к двум дорогам, затем возвращается к их связанности. Сама сцена задаёт несколько направлений внимания.","From “Moment,” reading branches toward two paths and returns to their connectedness. The scene itself gives attention several directions."],
    ["wheel","circle","compares","Форма и движение","Form and movement","Карлик отвечает кругом времени, звери поют о катящемся колесе. Родственные формы получают различие через говорящего и движение речи.","The dwarf answers with circular time; the animals sing of a rolling wheel. Related forms differ through their speakers and their speech’s movement."],
    ["ring","circle","compares","Замкнутость и связь","Closure and connection","Круг карлика отвечает на загадку дорог, брачное кольцо «Семи печатей» обращено к любимой вечности. Замкнутая форма меняет задачу между объяснением и желанием.","The dwarf’s circle answers the paths’ enigma; the marriage ring of “The Seven Seals” addresses beloved eternity. Closed form changes its task between explanation and desire."],
    ["ring","affirmation","interprets","Кольцо повторяемого желания","The ring of repeated desire","После каждого «если когда-нибудь» возвращается любовь к вечности. Кольцо связывает названные возможности говорящего повторением одного утверждения.","Love for eternity returns after every “if ever.” The ring connects the speaker’s named possibilities through one affirmation’s repetition."],
    ["nausea","small-human","supports","Трудный предмет возврата","A difficult object of return","Возвращение малого человека названо прямо. Заратустра встречает в мысли о целом повторение того, что презирает и стремится преодолеть.","The small human’s return is named directly. Within the thought of the whole, Zarathustra encounters the recurrence of what he despises and seeks to overcome."],
    ["dance","form-content","supports","Ритм участвует в смысле","Rhythm participates in meaning","Танцор, дух-птица и переход к пению меняют способ выражения мысли в последних печатях. Их последовательность входит в смысл обращения к вечности.","Dancer, bird-spirit and the passage to singing change thought’s expression in the final seals. Their sequence enters the address to eternity’s meaning."],
    ["cosmological","recurrence","interprets","Буквальный масштаб","A literal scale","Великий год зверей повторяет весь ход событий в большом и малом. Космологическое чтение исследует этот объём и его основания.","The animals’ great year repeats events’ entire course in large and small details. Cosmological reading examines this scope and its grounds."],
    ["existential","same-life","interprets","Обратить к живущему","Address the living person","Демон в §341 обращает точное повторение к слушающему и спрашивает о его желании. Та же жизнь становится условием испытания собственного отношения к ней.","The demon in §341 addresses exact recurrence to the hearer and asks about desire. The same life becomes the condition for examining one’s relation to it."],
    ["poetic","ring","interprets","Исследовать через образ","Inquire through an image","Кольцо возвращения в «Семи печатях» названо брачным, а вечность — любимой. Поэтическое чтение спрашивает, как этот союз выражает желание повторения.","Recurrence’s ring in “The Seven Seals” is a marriage ring, and eternity is beloved. Poetic reading asks how this union expresses recurrence’s desire."],
    ["temporal-knot","necessity","develops","Связь требует уточнения","Connection needs clarification","У ворот связанность мгновения ведёт к вопросу «не должны ли мы вернуться?». В «Об избавлении» необходимость открывается через волю, которая не может хотеть назад.","At the gateway, the moment’s connectedness leads to “must we not return?” In “Redemption,” necessity appears through willing’s inability to will backward."],
    ["voice-reading","animals","interprets","Вернуть песне голос","Return a voice to the song","Песня зверей одновременно утешает, объясняет и вызывает ответ героя. Чтение по голосам удерживает эти действия рядом с содержанием формулы.","The animals’ song consoles, explains and elicits the protagonist’s reply. Reading voices preserves these acts beside the formula’s contents."],
    ["performative","affirmation","develops","Как совершается утверждение","How affirmation is enacted","В §341 вопрос о повторении должен сопровождать каждое действие; в «Семи печатях» желание возвращается в припеве. Утверждение исследуется через формы его совершения.","In §341, recurrence’s question is to accompany every action; in “The Seven Seals,” desire returns in the refrain. Affirmation is examined through the forms of its enactment."],
    ["selective","whole-part","questions","Граница отбора","The limit of selection","Демон возвращает боли, радости и малейшие подробности в прежнем порядке. Выбор только некоторых эпизодов меняет объём поставленного им вопроса.","The demon returns pains, joys and the smallest details in their previous order. Selecting only some episodes changes the scope of his question."],
    ["small-human","human-overcoming","develops","Преодоление без удаления","Overcoming without deletion","В воображаемой зверями речи Заратустра возвращается, чтобы снова учить сверхчеловеку; малый человек тоже возвращается. Преодоление приходится прочитать вместе с этим соседством.","In the speech imagined by the animals, Zarathustra returns to teach the Overhuman again; the small human returns too. Overcoming must be read beside this concurrence."],
    ["nonlinear","present","interprets","Смотреть из пересечения","Look from the crossing","Вой собаки переносит Заратустру из нынешнего мгновения к детству, затем к невиданному прежде пастуху. Настоящее соединяет воспоминание и появление нового образа.","The dog’s howl carries Zarathustra from the present moment to childhood and then to the unprecedented shepherd. The present connects recollection with a new image’s appearance."],
    ["form-content","proposition-poem","develops","Что теряет пересказ?","What does restatement lose?","Ответ карлика, вопросы у ворот и видение пастуха располагают мысль в разных речевых формах. Пересказ тезиса должен объяснить переходы между ними.","The dwarf’s answer, gateway questions and shepherd’s vision place thought in different forms of speech. A thesis’s paraphrase must account for their transitions."],
    ["task","teach-live","develops","Передача и испытание","Transmission and ordeal","Звери называют задачу учителя после рассказа Заратустры о болезни. Глава связывает передачу мысли с испытанием того, кто должен её нести.","The animals name the teacher’s task after Zarathustra’s illness account. The chapter connects conveying the thought with its bearer’s ordeal."],
    ["open-reading","cosmos-evidence","develops","Развести основания","Distinguish the grounds","Вопросы у ворот обращены к связанности вещей и возвращению; §341 спрашивает также о превращении слушающего. Сравнение уточняет, на какой вопрос отвечает выбранное основание.","The gateway questions concern connected things and recurrence; §341 also asks about the listener’s transformation. Comparison clarifies which question the chosen ground answers."],
    ["recurrence","becoming","questions","Что возвращается?","What returns?","Песня включает распад и новое соединение, а объяснение великого года повторяет их порядок. Вопрос касается отношения изменяющихся состояний к возвращению их хода.","The song includes dissolution and reunion, while the great year’s explanation repeats their order. The question concerns changing states’ relation to their course’s return."],
    ["identity","difference","compares","То же и различающееся","The same and the differing","Звери требуют той же жизни в большом и малом; речной фрагмент Гераклита соединяет те же реки с иными водами. Сравнение уточняет, что должно сохраняться в каждом случае.","The animals require the same life in large and small details; Heraclitus’s river fragment joins the same rivers with different waters. Comparison clarifies what must persist in each case."],
    ["fate","agency","questions","Что остаётся действующему?","What remains for the agent?","На «Блаженных островах» Заратустра поправляет «воля — моя судьба» на хотение такой судьбы. Поправка открывает вопрос о деятельном отношении к уделу.","On “The Happy Isles,” Zarathustra corrects “willing is my fate” into wanting such a fate. The correction opens a question about an active relation to one’s lot."],
    ["necessity","free-necessary","develops","Уточнить смысл несвободы","Clarify unfreedom’s meaning","В определении 7 первой части «Этики» необходимость собственной природы входит в свободу. Различие проходит по источнику определения к действию.","In the “Ethics,” Part I, definition 7, one’s own nature’s necessity belongs within freedom. The distinction concerns determination to act’s source."],
    ["creation","same-new","develops","Какую новизну искать?","Which novelty to seek?","Лев добывает свободу для созидания, ребёнок назван новым началом и самокатящимся колесом. «Три превращения» ставят новизну рядом с образами собственного движения.","The lion wins freedom for creation; the child is named a new beginning and a self-rolling wheel. “The Three Metamorphoses” places novelty beside images of self-movement."],
    ["memory","again-memory","develops","Условие узнавания","A condition of recognition","Нынешний вой узнаётся через детское воспоминание Заратустры. Сцена позволяет спросить, что именно возвращается в акте узнавания.","The present howl is recognised through Zarathustra’s childhood recollection. The scene asks what exactly returns in recognition."],
    ["amor-fati","affirmation","develops","Учиться утверждению","Learning affirmation","В §276 учение видеть необходимое прекрасным ведёт к желанию делать прекрасным и однажды стать только утверждающим. Переход развёрнут как задача изменения взгляда.","In §276, learning to see necessity as beautiful leads toward making beautiful and one day becoming only affirmative. The transition unfolds as a task of changed vision."],
    ["becoming","circle-change","develops","Изменение внутри возврата","Change within return","Великие годы зверей возвращают одинаковый порядок распада и соединения. Изменение состояний и повторение порядка принадлежат одной речи.","The animals’ great years return dissolution and reunion in the same order. Changing states and recurring order belong to one speech."],
    ["present","memory","compares","Пережить и удержать","Experience and retain","Знакомый вой собаки ведёт к видению, названному невиданным прежде. Настоящее объединяет узнавание с появлением нового.","A familiar howl leads to a vision called unprecedented. The present joins recognition with a new appearance."],
    ["affirmation","joy-pain","develops","Радость хочет всего","Joy wants everything","В «Песни опьянения» радость хочет себя, затем вечности всех вещей, включая горе. Вопрос следует за этим расширением желания.","In “The Drunken Song,” joy wants itself, then all things’ eternity, including sorrow. The question follows this expansion of desire."],
    ["task","dossier","interprets","Учиться по нескольким местам","Learn across several passages","Предназначение учителя в речи зверей можно прочитать рядом с собственным делом Заратустры в «Знамении». Подборка следует от названной задачи к своему часу.","The teacher’s vocation in the animals’ speech can be read beside Zarathustra’s own work in “The Sign.” The dossier follows a named task toward one’s own hour."],
    ["cosmological","existential","compares","Мир и отношение к жизни","World and relation to life","Великий год задаёт точный порядок повтора; демон обращает точность к жизни слушающего. Вопросы о составе возвращаемого и желании возвращения встречаются.","The great year specifies recurrence’s exact order; the demon addresses exactness to the hearer’s life. Contents and desire meet in recurrence’s question."],
    ["poetic","cosmological","compares","Образ и гипотеза","Image and hypothesis","Звери объясняют великий год, а «Семь печатей» поют любовь к вечности. Сравнение исследует разницу между объяснением повторения и желанием его.","The animals explain the great year; “The Seven Seals” sings love for eternity. Comparison examines explaining recurrence and desiring it."],
    ["selective","existential","questions","Лёгкость неполной пробы","The ease of an incomplete test","В §341 исключительное мгновение встречается с вопросом, который должен лечь на каждое действие. Испытание расширяется от одного переживания ко всей жизни.","In §341, an exceptional moment meets the question that is to weigh on every action. The trial expands from one experience toward an entire life."],
    ["fatalism","agency","questions","Проверить вывод о бездействии","Test the inference to inaction","Звери воображают речь Заратустры, включающую его самого среди причин возвращения. Участник помещён внутрь порядка, о котором говорит.","The animals imagine Zarathustra’s speech including himself among recurrence’s causes. The participant is placed within the order he describes."],
    ["affirmation","fatalism","contrasts","Необходимость и участие","Necessity and participation","Amor fati в §276 связано с учением и будущим изменением себя; звери включают Заратустру в причины его возвращения. Эти места дают проверить вывод от необходимости к безучастию.","Amor fati in §276 involves learning and a future change in oneself; the animals include Zarathustra among his return’s causes. These passages test the inference from necessity to non-participation."],
    ["same-new","difference","questions","Где возникает отличие?","Where does difference arise?","Звери исключают новую жизнь, Делёз спрашивает о различии как основании возврата. Сопоставление переносит вопрос к роли различий в объяснении.","The animals exclude a new life; Deleuze asks about difference as recurrence’s ground. Comparison shifts the question toward differences’ explanatory role."],
    ["circle-change","wheel","questions","Движение по замкнутому пути","Movement along a closed path","Катящееся колесо соседствует с распадом и новым соединением. Великий год далее уточняет повторяемость самого хода этих перемен.","The rolling wheel stands beside dissolution and reunion. The great year then specifies the recurrence of these changes’ course."],
    ["free-necessary","fate","questions","Полученное и совершённое","What is given and what is done","Заратустра поправляет слово о воле как судьбе: его воля хочет такой судьбы. На «Блаженных островах» эта перемена связана с творчеством и становлением.","Zarathustra corrects willing as fate: his will wants such a fate. On “The Happy Isles,” this change is joined to creation and becoming."],
    ["joy-pain","existential","questions","От мгновения ко всей жизни","From a moment to the whole life","Демон возвращает каждую боль и радость; «Песнь опьянения» движется от радости мгновения к желанию всего. Жизненная проба соединяет точность повтора с расширением желания.","The demon returns every pain and joy; “The Drunken Song” moves from a moment’s joy toward wanting everything. The life trial connects recurrence’s exactness with desire’s expansion."],
    ["teach-live","nausea","questions","Мысль встречает тело","Thought meets the body","Будущая задача учить названа после рассказа о возвращении малого человека. Глава оставляет вопрос, как собственное испытание войдёт в речь учителя.","The future teaching task is named after the small human’s return is recounted. The chapter asks how the teacher’s own ordeal will enter his speech."],
    ["human-overcoming","laughter","questions","Признак перемены","A sign of change","Пастух после укуса назван уже не человеком; смех вызывает неутолимое желание Заратустры. Преодоление дано через смену именования и будущую направленность желания.","After the bite, the shepherd is called no longer human; his laughter arouses Zarathustra’s insatiable longing. Overcoming appears through changed naming and desire directed forward."],
    ["proposition-poem","cosmological","questions","Допустимое извлечение тезиса","When extracting a thesis is justified","Между песней о круге существования и объяснением великого года находится ответ Заратустры. Космологический тезис нужно прочитать через этот поворот разговора.","Zarathustra’s reply intervenes between the song of existence’s circle and the great year’s explanation. The cosmological thesis must be read through this conversational turn."],
    ["character-author","task","questions","Чья задача учить?","Whose task is teaching?","Звери называют Заратустру учителем возвращения; в «Знамении» он сам говорит о своём деле. Различие сцен делает призвание вопросом композиции.","The animals name Zarathustra recurrence’s teacher; in “The Sign” he names his own work. The scenes’ difference makes vocation a compositional question."],
    ["again-memory","identity","questions","Тождество без узнавания","Identity without recognition","Демон задаёт тождество порядком событий; вой собаки узнаётся через память. Повторение и узнавание получают разные основания.","The demon specifies identity through events’ order; the dog’s howl is recognised through memory. Recurrence and recognition receive different grounds."],
    ["whole-part","recurrence","questions","Каков объём возврата?","What is recurrence’s scope?","Паук, лунный свет и сам разговор входят в повтор §341. «Песнь опьянения» связывает желание одного мгновения с желанием всех вещей.","The spider, moonlight and conversation itself enter §341’s recurrence. “The Drunken Song” connects wanting one moment with wanting all things."],
    ["cosmos-evidence","necessity","questions","Как доказана неизбежность?","How is inevitability established?","Вопросы у ворот переходят от вечности дорог к уже случившемуся и связанности всего. Именно эти переходы задают работу обоснования.","The gateway questions move from eternal paths to what has already happened and everything’s connection. These transitions pose the work of justification."],
    ["heraclitus","becoming","compares","Соседняя мысль о перемене","A neighbouring thought of change","В B12 те же реки принимают иные воды; звери поют распад и соединение. Сравнение уточняет сохраняемое целое и меняющийся состав.","In B12, the same rivers receive other waters; the animals sing dissolution and reunion. Comparison specifies a retained whole and changing contents."],
    ["heraclitus","circle-change","questions","Мера изменения и повтор","Measured change and recurrence","В B30 огонь загорается и гаснет мерами; великие годы зверей одинаковы в большом и малом. Соразмерность изменения ещё нужно сопоставить с точным повтором.","In B30, fire kindles and goes out in measures; the animals’ great years match in large and small details. Measured change remains to be compared with exact recurrence."],
    ["stoics","providence","develops","Размышлять о целом","Reflect on the whole","В VI.44 Марк Аврелий проходит условные доводы о божественном попечении и завершает собственной разумной и общественной природой. Порядок мира связан с вопросом о действии.","In VI.44, Marcus Aurelius moves through conditional arguments about divine care and ends with his own rational, social nature. World-order is joined to action’s question."],
    ["stoics","epictetus","develops","Вход через различение","An entry through distinction","«Энхиридион» начинается с двух перечней: собственные суждения и стремления, затем тело, имущество, слава и должности. Различение сразу ведёт к последствиям его смешения.","The “Enchiridion” begins with two lists: one’s judgements and impulses, then body, property, reputation and office. The distinction immediately leads to the consequences of confusing its sides."],
    ["epictetus","agency","develops","Уточнить область ответа","Clarify the scope of response","Эпиктет помещает суждение, желание и отвращение среди подвластного. Описание действия начинается с внутреннего направления, прежде внешнего исхода.","Epictetus places judgement, desire and aversion among what is up to us. Action’s description begins with inward direction before external outcome."],
    ["epictetus","amor-fati","compares","Два отношения к данному","Two relations to what is given","Эпиктет различает своё и чужое; §276 учится видеть необходимое прекрасным. Оба хода меняют отношение к происходящему через разные действия мысли.","Epictetus distinguishes one’s own from what is not; §276 learns to see necessity as beautiful. Both change a relation to events through different acts of thought."],
    ["providence","necessity","compares","Порядок как основание","Order as a ground","Марк Аврелий рассуждает о благе целого, Заратустра — о связанности мгновения и вечных дорог. Основания порядка различаются в самом ходе этих мест.","Marcus Aurelius reasons about the whole’s good, Zarathustra about the moment’s connection with eternal paths. Order’s grounds differ in these passages’ movement."],
    ["providence","cosmological","compares","Порядок не равен повтору","Order is not repetition","В VI.44 вопрос касается личной жизни внутри божественного попечения о целом. Великий год зверей объясняет повторяемую последовательность событий.","VI.44 concerns personal life within divine care for the whole. The animals’ great year explains events’ recurring sequence."],
    ["spinoza","conatus","develops","Стремление сохранять бытие","Striving to persevere","III.6 утверждает стремление каждой вещи сохранять бытие. Доказательство обращается к её действующей силе и противостоянию уничтожению.","III.6 states each thing’s striving to persevere in being. The proof invokes its active power and opposition to destruction."],
    ["spinoza","necessity","compares","Действие в причинных связях","Action within causal connections","Определение 7 первой части «Этики» различает определение собственной природой и другим. Необходимость входит и в определение свободного.","The “Ethics,” Part I, definition 7 distinguishes determination by one’s own nature and by another. Necessity belongs within the definition of the free."],
    ["conatus","affirmation","compares","Существовать и утверждать","Persist and affirm","Conatus описывает деятельное сохранение бытия; §276 — учение взгляда и будущего утверждения. Сравнение спрашивает о переходе от существования к оценке.","Conatus describes active perseverance in being; §276 describes learning to see and affirm. Comparison asks after the passage from existence to evaluation."],
    ["conatus","recurrence","compares","Продолжение и возвращение","Continuation and recurrence","Стремление сохраняться противостоит уничтожению; песня зверей включает смерть и новое возникновение в возвращение. Продолжение вещи и повтор её жизни различаются.","Striving to persevere opposes destruction; the animals’ song includes death and arising anew in recurrence. Continuing a thing and repeating its life differ."],
    ["leibniz","possible-worlds","develops","Почему этот мир?","Why this world?","Множество возможных вселенных в §§53–55 требует основания существования одной. Лейбниц связывает выбор со степенью совершенства.","Many possible universes in §§53–55 require a reason for one’s existence. Leibniz connects selection with degree of perfection."],
    ["possible-worlds","identity","questions","Тот же или другой?","The same or another?","Совершенство у Лейбница объясняет выбор; звери исключают лучшую жизнь из возвращения той же. Улучшение получает разную роль в двух постановках.","Perfection explains selection for Leibniz; the animals exclude a better life from the same life’s return. Improvement plays different roles in these formulations."],
    ["possible-worlds","same-new","compares","Альтернатива и новизна","Alternative and novelty","Лейбниц различает возможные вселенные; демон возвращает эту жизнь без ничего нового. Вопрос «иначе» требует указать, меняется ли целое или подробность повтора.","Leibniz distinguishes possible universes; the demon returns this life without novelty. “Otherwise” requires specifying whether a whole or recurrence’s detail changes."],
    ["possible-worlds","amor-fati","compares","Выбор мира и учение взгляда","World selection and learning to see","Выбор лучшего возможного мира и учение видеть необходимое прекрасным различаются субъектом и предметом выбора. Сопоставление сохраняет эту разницу.","Selecting the best possible world and learning to see necessity as beautiful differ in their chooser and chosen object. Comparison retains this difference."],
    ["kierkegaard","repetition","develops","Литературный эксперимент","A literary experiment","Константин Констанций начинает с ходьбы Диогена как ответа на отрицание движения. Затем повторение получает направление вперёд рядом с воспоминанием назад.","Constantin Constantius begins with Diogenes walking in answer to motion’s denial. Repetition then receives a forward direction beside backward recollection."],
    ["repetition","memory","contrasts","Снова и в воспоминании","Again and in memory","Повторение и воспоминание названы одним движением в противоположных направлениях. Их родство ставит вопрос, как бывшее способно двигаться вперёд.","Repetition and recollection are called one movement in opposed directions. Their kinship asks how what has been can move forward."],
    ["repetition","recurrence","compares","Общий вопрос, разный масштаб","A shared question, different scales","«Повторение» начинает с направления движения, §341 — с полного состава жизни, возвращаемой в прежнем порядке. Общему «снова» нужно уточнить объём.","“Repetition” starts from movement’s direction; §341 from a life’s full contents returning in the previous order. Their shared “again” needs its scope specified."],
    ["kierkegaard","existential","compares","Проверка через жизнь","A test through life","Открытие «Повторения» связывает повтор со счастьем, §341 — с отношением слушающего к своей жизни. Понятие затрагивает того, кто спрашивает.","“Repetition” opens by connecting repetition with happiness; §341 with the hearer’s relation to life. The concept bears upon its questioner."],
    ["camus","sisyphus","interprets","Миф как философский образ","Myth as a philosophical image","Спуск к камню становится у Камю часом сознания. Философский поворот мифа расположен в паузе между повторяемыми усилиями.","For Camus, descending toward the stone becomes consciousness’s hour. The myth’s philosophical turn lies in the pause between repeated efforts."],
    ["sisyphus","wheel","compares","Повторяемая задача","A recurring task","Камень падает снова, колесо существования вновь катится. Сизиф добавляет к повторяемому движению ясное знание своего удела.","The stone falls again, existence’s wheel rolls again. Sisyphus adds lucid knowledge of his lot to repeated movement."],
    ["camus","affirmation","compares","Продолжение без обещания","Continuing without a promise","Человеческое «да» у Камю сопровождает не прекращающееся усилие; в §276 утверждение ещё предстоит выучить. Согласие исследуется как задача отношения к жизни.","Camus’s human yes accompanies unceasing effort; in §276 affirmation remains to be learned. Assent is examined as a task in relating to life."],
    ["sisyphus","teach-live","develops","Знать задачу и нести её","Know the task and carry it","Знание удела Сизифа входит в возвращение к камню; речь учителя возвращения следует за болезнью. Сопоставление спрашивает, что испытание добавляет к знанию.","Sisyphus’s knowledge of his lot enters his return to the stone; recurrence’s teacher speaks after illness. Comparison asks what undergoing adds to knowing."],
    ["deleuze","return-difference","develops","Позднейшее прочтение","A later reading","Делёз ищет то, чего не объясняет механический цикл: различия и их воспроизведение. Возвращение требует различающего основания.","Deleuze seeks what a mechanical cycle leaves unexplained: differences and their reproduction. Recurrence requires a differential ground."],
    ["return-difference","difference","interprets","Различие получает приоритет","Difference gains priority","Воля к власти вводится как различающий и генетический элемент сил. Следующий вопрос Делёза — как это отношение составляет синтез возвращения.","Will to power enters as forces’ differential and genetic element. Deleuze’s next question is how this relation constitutes recurrence’s synthesis."],
    ["return-difference","identity","questions","Проверить первенство того же","Test the priority of the same","Критика готового тождества у Делёза встречается с настойчивой формулой той же жизни у зверей. Интерпретация должна объяснить их отношение.","Deleuze’s critique of given identity meets the animals’ insistent same-life formula. Interpretation must explain their relation."],
    ["deleuze","becoming","compares","Возвращение через становление","Recurrence through becoming","Звери называют чередование состояний; Делёз спрашивает об основании различий сил. Сравнение ведёт от хода становления к его объяснению.","The animals name alternating states; Deleuze asks after forces’ differential ground. Comparison moves from becoming’s course toward its explanation."],
    ["source-neighbor","open-reading","supports","Сравнивать по контексту","Compare through context","Песня, ответ о шарманке и рассказ об отвращении образуют последовательность. Разные прочтения должны объяснить переходы между этими соседними речами.","Song, barrel-organ reply and disgust account form a sequence. Different readings must explain the transitions between these neighbouring speeches."],
    ["poetic","dance","interprets","Ритм вместо одной формулы","Rhythm beyond a single formula","В последних печатях тяжесть делается лёгкой, тело — образом духа-птицы, слова — пением. Танец участвует в движении желания вечности.","In the final seals, heaviness becomes light, the body figures bird-spirit, and words become singing. Dance participates in desire for eternity."],
    ["open-reading","character-author","develops","Сохранить сложность сцены","Preserve the scene’s complexity","Молчание Заратустры следует за воображённой зверями речью. Возможные прочтения молчания дают конкретное место для сравнения авторских атрибуций.","Zarathustra’s silence follows the speech imagined by the animals. Readings of that silence provide a specific place to compare authorial attributions."],
    ["agency","decision","develops","От способности к случаю","From capacity to a case","Лев добывает свободу, ребёнок начинает созидание; §341 обращает вопрос к каждому действию. Решение исследуется между возможностью и её осуществлением.","The lion wins freedom, the child begins creation; §341 addresses every action. Decision is examined between possibility and its enactment."],
    ["decision","counterfactual","develops","Проверить «иначе»","Test “otherwise”","Демон требует повтора без изменения, а воля в «Об избавлении» не может хотеть назад. Вопрос «иначе» встречается с уже совершившимся.","The demon requires recurrence without alteration, while willing in “Redemption” cannot will backward. “Otherwise” meets what has already happened."],
    ["counterfactual","responsibility","develops","От бессилия к вменению","From powerlessness to imputation","Бессилие перед «это было» превращается в месть, вину и наказание. «Об избавлении» позволяет исследовать происхождение обвинения из отношения воли к прошлому.","Powerlessness before “it was” turns into revenge, guilt and punishment. “Redemption” examines accusation’s origin in willing’s relation to the past."],
    ["responsibility","affirmation","questions","После отказа от обвинения","After relinquishing accusation","Месть времени в «Об избавлении» можно сопоставить с желанием не обвинять в §276. Возникает вопрос об ответе прошлому после отказа от обвинения.","Revenge against time in “Redemption” can be compared with §276’s wish not to accuse. The question becomes how to answer the past after accusation is relinquished."],
    ["nausea","body-resistance","develops","Услышать телесный ответ","Hear the bodily response","Вызов глубинной мысли, семь дней болезни и позднее объяснение отвращения связывают тело с ходом понимания. Предмет испытания назван в ходе выздоровления.","Summoning the deepest thought, seven days of illness and the later disgust account connect the body with understanding’s course. Recovery brings the ordeal’s object into words."],
    ["dance","lived-rhythm","develops","Ритм становится опытом","Rhythm becomes experience","Образ танцора вновь подводит к знакомому припеву. Ритм можно исследовать через изменение того, что слышится в повторённых словах.","The dancer’s image leads again to the familiar refrain. Rhythm can be examined through what changes in hearing repeated words."],
    ["lived-rhythm","return-practice","develops","Повторить чтение","Repeat the reading","Один припев возвращается после семи разных строф. Сравнение двух его вхождений даёт тексту самому организовать повторное слушание.","One refrain returns after seven different stanzas. Comparing two occurrences lets the text organise listening again."],
    ["body-resistance","return-practice","develops","Вернуться с новым вопросом","Return with a new question","После слов о малом человеке начало болезни можно прочитать заново. Теперь известен предмет, который первая сцена ещё не называет.","After the words about the small human, the illness’s beginning can be reread. Its object is now known, though the opening scene leaves it unnamed."],
    ["memory","remembered-return","develops","Развести повтор и узнавание","Separate repetition and recognition","Детское воспоминание связывает прежний и нынешний вой. Рассказчик узнаёт прежний вой внутри своей жизни; это узнавание нужно отличить от утверждения о повторении всей жизни.","Childhood memory connects the earlier and present howls. The narrator recognizes the earlier howl within his life; this recognition must be distinguished from asserting the return of an entire life."],
    ["remembered-return","attention","develops","Что замечено теперь?","What is noticed now?","Узнавание воя ведёт к вопросу о том, что увидела собака, затем к пастуху. Память продолжает движение внимания.","Recognising the howl leads to what the dog has seen and then to the shepherd. Memory carries attention onward."],
    ["attention","shared-world","develops","Расширить поле внимания","Widen attention’s field","Собака воет, Заратустра вспоминает и помогает, пастух кусает. Общий мир сцены складывается из разных действий участников.","The dog howls, Zarathustra remembers and helps, the shepherd bites. The scene’s shared world forms through participants’ different acts."],
    ["shared-world","whole-part","questions","Эта жизнь с этими спутниками","This life with these companions","Та же жизнь возвращается с этим солнцем, землёй, орлом и змеёй. Конкретные спутники входят в вопрос о тождестве целого.","The same life returns with this sun, earth, eagle and snake. Particular companions enter the whole’s question of identity."],
    ["camus","fate","interprets","Судьба собирается поступками","Fate gathers through actions","Поступки, соединённые памятью и ограниченные смертью, становятся у Камю личной судьбой. Этот взгляд возникает при вновь катящемся камне.","Actions joined by memory and bounded by death become personal fate for Camus. This view arises while the stone rolls again."],
    ["sisyphus","agency","develops","Участие внутри предела","Participation within a limit","Спуск объединяет сознание своего удела с возвращением к усилию. Участие Сизифа включает и действие, и ясный взгляд на его ход.","The descent joins awareness of one’s lot with returning to effort. Sisyphus’s participation includes action and a lucid view of its course."],
    ["responsibility","creation","develops","От вменения к созиданию","From imputation to creation","«Об избавлении» движется от мести и наказания к вопросу о творящем «я так хотел». Созидание исследуется как изменение ответа тому, что уже было.","“Redemption” moves from revenge and punishment toward a creative “I willed it thus.” Creation is examined as a changed response to what has been."],
    ["creation","fate","develops","Сделанное входит в судьбу","What is made enters fate","Творчество на «Блаженных островах» связано с превращениями и хотением такой судьбы. Созидание переводит вопрос об уделе в вопрос о желании становления.","Creation on “The Happy Isles” involves transformations and wanting such a fate. Creation turns fate’s question toward desiring becoming."],
    ["agency","fate","develops","Действующий внутри судьбы","The agent within fate","Звери включают Заратустру в причины его возвращения; Камю соединяет поступки памятью. Действующий входит в судьбу через разные виды связи.","The animals include Zarathustra among his return’s causes; Camus joins actions through memory. The agent enters fate through different kinds of connection."],
    ["joy-pain","shared-world","develops","От общего «да» к встрече","From a general yes to an encounter","Желание всего в «Песни опьянения» встречается с трудностью помощи в «О сострадательных». Вопрос переходит от всеобщего «да» к конкретному отношению.","Desire for everything in “The Drunken Song” meets help’s difficulty in “The Pitiful.” The question moves from a universal yes to a particular relation."],
    ["shared-world","responsibility","develops","Что делает дар?","What does a gift do?","Помощь может задеть гордость, дар — создать тяжёлую обязанность. «О сострадательных» заставляет спрашивать, что собственный поступок делает в отношении к другому.","Help may touch pride, a gift may create a heavy obligation. “The Pitiful” asks what one’s act does within a relation to another."],
    ["spinoza","leibniz","compares","Необходимость и выбор мира","Necessity and world choice","Спиноза определяет свободу через собственную природу; Лейбниц объясняет выбор вселенной через совершенство возможных. Сравнение уточняет разные задачи основания.","Spinoza defines freedom through one’s own nature; Leibniz explains universe selection through possible worlds’ perfection. Comparison specifies grounding’s different tasks."],
    ["camus","memory","develops","Связать поступки в жизнь","Connect actions into a life","Взгляд памяти соединяет поступки в судьбу, узнаваемую своей. Смерть задаёт предел этого обозрения жизни.","Memory’s gaze joins actions into a fate recognised as one’s own. Death sets this survey of life’s limit."],
  ];
  return rows.map(([from, to, kind, ru, en, ruBody, enBody]) => ({
    id: 'atlas:' + from + ':' + kind + ':' + to,
    from: resolveId(from), to: resolveId(to), kind,
    label: bi(ru, en), body: bi(ruBody, enBody), demo: true,
  }));
}

const extensionDefinitions = [
  ['freedom', 'Возвращение и свобода', 'Recurrence and freedom', 'От способности действовать к решению и ответственности', 'From agency to decision and responsibility', ['decision', 'counterfactual', 'responsibility']],
  ['body', 'Образ и переживание', 'Image and experience', 'От телесного сопротивления к повторному чтению', 'From bodily resistance to rereading', ['lived-rhythm', 'body-resistance', 'return-practice']],
  ['attention', 'Повторение и внимание', 'Repetition and attention', 'Узнавание, изменившийся взгляд и другие жизни', 'Recognition, a changed gaze and other lives', ['remembered-return', 'attention', 'shared-world']],
];

function makeAssemblies(edges) {
  const definitions = [
    ['moment-eternity', 'Один миг и вечность', 'One moment and eternity', 'Ворота, память и встреча двух дорог', 'Gateway, memory and the meeting of two paths', 'Миг разделяет времена или связывает их?', 'Does the moment divide times or connect them?', ['chapter-p3.r2', 'moment', 'gateway', 'two-paths', 'present', 'circle', 'wheel', 'dwarf', 'nonlinear', 'temporal-knot', 'recurrence', 'memory', 'again-memory', 'heraclitus', 'becoming', 'circle-change']],
    ['affirmation-fatalism', 'Принятие или фатализм', 'Affirmation or fatalism', 'Судьба, действие и трудность целой жизни', 'Fate, action and the difficulty of an entire life', 'Как принять жизнь, сохраняя способность действовать?', 'How can life be affirmed while preserving agency?', ['chapter-p3.r13', 'all-things', 'same-life', 'affirmation', 'amor-fati', 'fate', 'agency', 'necessity', 'fatalism', 'free-necessary', 'joy-pain', 'nausea', 'existential', 'epictetus', 'stoics', 'providence', 'camus', 'sisyphus', 'conatus']],
    ['circle-becoming', 'Круг и становление', 'Circle and becoming', 'Тождество, различие и возможность нового', 'Identity, difference and the possibility of novelty', 'Может ли возвращение сохранять становление?', 'Can recurrence preserve becoming?', ['recurrence', 'becoming', 'circle', 'wheel', 'ring', 'identity', 'difference', 'creation', 'same-new', 'circle-change', 'heraclitus', 'deleuze', 'return-difference', 'possible-worlds', 'leibniz', 'same-life']],
    ['several-readings', 'Один текст — несколько прочтений', 'One text, several readings', 'Голоса, образы и основания интерпретаций', 'Voices, images and grounds for interpretation', 'Что каждое прочтение объясняет, а что оставляет трудным?', 'What does each reading explain, and what does it leave difficult?', ['work', 'chapter-p3.r13', 'all-things', 'same-life', 'animals', 'narrated-voices', 'source-neighbor', 'voice-reading', 'cosmological', 'existential', 'poetic', 'open-reading', 'dossier', 'character-author', 'proposition-poem', 'form-content', 'cosmos-evidence', 'ring', 'dance', 'selective', 'whole-part']],
  ];
  return definitions.map(([id, ru, en, ruSub, enSub, ruQuestion, enQuestion, slugs]) => {
    const nodeIds = slugs.map(resolveId);
    const included = new Set(nodeIds);
    return { id, title: bi(ru, en), subtitle: bi(ruSub, enSub), question: bi(ruQuestion, enQuestion), nodeIds, edgeIds: edges.filter((edge) => included.has(edge.from) && included.has(edge.to)).map((edge) => edge.id) };
  });
}

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === 'object') return Object.fromEntries(Object.keys(value).sort().map((key) => [key, canonical(value[key])]));
  return value;
}

/** Preserve the supplied library and add the prepared atlas without mutating it. */
export async function createAtlasLibrary(sourceLibrary) {
  const sourceNodes = sourceLibrary.nodes ?? [];
  const available = new Set(sourceNodes.map((node) => node.id));
  for (const id of sourceIds) {
    if (!available.has(id)) throw new Error('Atlas requires source material: ' + id);
  }
  const clusters = clusterData.map(([id, ru, en, ruSub, enSub, color, center]) => ({ id, title: bi(ru, en), subtitle: bi(ruSub, enSub), color, center: [...center] }));
  const preparedNodes = makeNodes(), preparedEdges = makeEdges();
  const inquiry = bindInquiryLayer([...sourceIds, ...preparedNodes.map(node => node.id)], preparedEdges.map(edge => edge.id));
  const readingFor = id => {
    const reading = NODE_CONTENT[id];
    if (!reading) throw new Error('Missing authored atlas reading: ' + id);
    return { inquiry: inquiry.material(id), perspectives: reading.perspectives, ...(reading.example ? { example: reading.example } : {}), ...(reading.question ? { question: reading.question } : {}) };
  };
  const demoNodes = preparedNodes.map(node => ({ ...node, ...readingFor(node.id), body: NODE_CONTENT[node.id].body }));
  for (const node of demoNodes) {
    if (available.has(node.id)) throw new Error('Atlas material already exists: ' + node.id);
    node.sourceRefs = node.sourceRefs.map((ref) => typeof ref === 'string' ? { label: new URL(ref).hostname.replace(/^www\./, ''), ref } : ref);
  }
  const visibleSources = sourceNodes.filter((node) => sourceIds.includes(node.id)).map((node) => ({ ...node, cluster: 'sources', ...readingFor(node.id), atlasBody: NODE_CONTENT[node.id].body }));
  const positioned = [...visibleSources, ...demoNodes];
  const prominent = new Set(['work','demo:gateway','demo:recurrence','demo:cosmological','demo:fatalism','demo:heraclitus']);
  for (const cluster of clusters) {
    const members = positioned.filter((node) => node.cluster === cluster.id);
    members.forEach((node, index) => {
      node.prominent = prominent.has(node.id);
      const angle = index * Math.PI * (3 - Math.sqrt(5));
      const radius = index === 0 ? 0 : 27 + Math.sqrt(index) * 16;
      node.position = [
        Math.round(cluster.center[0] + Math.cos(angle) * radius),
        Math.round(cluster.center[1] + Math.sin(angle) * radius * 0.86),
        Math.round(cluster.center[2] + Math.sin(index * 1.73) * 22),
      ];
    });
  }
  const byId = new Map(positioned.map((node) => [node.id, node]));
  const nodes = sourceNodes.map((node) => byId.get(node.id) ?? node).concat(demoNodes);
  const edges = preparedEdges.map(edge => ({ ...edge, inquiry: inquiry.relation(edge.id) }));
  const extraIds = new Set(extensionDefinitions.flatMap((entry) => entry[5].map(demoId)));
  const defaultIds = [...sourceIds, ...demoNodes.filter((node) => !extraIds.has(node.id)).map((node) => node.id)];
  const extensions = extensionDefinitions.map(([id, ru, en, ruSub, enSub, slugs]) => {
    const nodeIds = slugs.map(demoId);
    const included = new Set(nodeIds);
    return { id, title: bi(ru, en), subtitle: bi(ruSub, enSub), nodeIds, edgeIds: edges.filter((edge) => included.has(edge.from) || included.has(edge.to)).map((edge) => edge.id) };
  });
  const { fingerprint: _sourceFingerprint, ...sourceFields } = sourceLibrary;
  const library = { ...sourceFields, schema: 'tos_constructor_library_v1', nodes, atlas: { defaultIds, edges, clusters, assemblies: makeAssemblies(edges), extensions, routes: RESEARCH_ROUTES, inquiry: INQUIRY_FOUNDATION, lensInquiry: LENS_INQUIRY, references: PRIMARY_SOURCES } };
  const encoded = new TextEncoder().encode(JSON.stringify(canonical(library)));
  const digest = await globalThis.crypto.subtle.digest('SHA-256', encoded);
  library.fingerprint = Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
  return library;
}
