import {describe,it,expect} from 'vitest';
import {bindResearchRoutes,routeGraphInput,routePath,createJourneyNavigator} from './journey-state.mjs';
const bi = text => ({ru:text,en:text});
const grounds = () => [{ref:'z-vision',focus:bi('Read the gateway questions')}];
const raw = [{id:'a',title:bi('Question'),question:bi('What changes?'),description:bi('Walk between ideas'),conclusion:bi('Keep the question open'),grounds:grounds(),steps:[{nodeId:'first',title:bi('Given'),body:bi('Begin here'),grounds:grounds()},{nodeId:'second',title:bi('Created'),body:bi('A second perspective'),grounds:grounds()}],transitions:[{from:'first',to:'second',edgeId:'b-to-a',body:bi('Follow the relation in reverse')}]}];
const library = {nodes:[{id:'first'},{id:'second'}],atlas:{edges:[{id:'b-to-a',from:'second',to:'first',kind:'questions'}]}};
const make = () => bindResearchRoutes(structuredClone(raw),library);
describe('grounded research routes',()=>{
 it('preserves actual reverse relation direction and binds exact graph identities',()=>{const r=make()[0];expect(r.transitions[0].direction).toBe('reverse');expect(routeGraphInput(r)).toEqual({nodeIds:['first','second'],edgeIds:['b-to-a']});expect(routePath(r)).toEqual({nodeIds:['material:first','material:second'],edgeIds:['atlas:b-to-a'],restrictEdges:true});});
 it('rejects a claimed transition whose relation joins different endpoints',()=>{const wrong=structuredClone(library);wrong.atlas.edges[0].from='third';expect(()=>bindResearchRoutes(raw,wrong)).toThrow(/does not follow/);});
 it('rejects missing steps, gaps and repeated route identities',()=>{const broken=structuredClone(raw);broken[0].steps[1].nodeId='missing';expect(()=>bindResearchRoutes(broken,library)).toThrow(/invalid step/);expect(()=>bindResearchRoutes([{...raw[0],transitions:[]}],library)).toThrow(/complete sequence/);expect(()=>bindResearchRoutes([...raw,...raw],library)).toThrow(/identity/);});
 it('rejects untranslated step guidance',()=>{const broken=structuredClone(raw);delete broken[0].steps[1].body.en;expect(()=>bindResearchRoutes(broken,library)).toThrow(/invalid step/);});
 it('allows routes without extra investigation guidance and rejects a partial translation when supplied',()=>{expect(make()).toHaveLength(1);const extended=structuredClone(raw);extended[0].investigation={startingPoint:bi('A case'),stakes:bi('What matters'),carryForward:bi('Compare the result')};expect(bindResearchRoutes(extended,library)[0].investigation).toEqual(extended[0].investigation);delete extended[0].investigation.stakes.en;expect(()=>bindResearchRoutes(extended,library)).toThrow(/incomplete investigation/);});
});
describe('returning to a walk',()=>{
 it('keeps walking bounds and cannot complete a route before its last step',()=>{const nav=createJourneyNavigator(make());nav.start('a');expect(nav.go(-1)).toBe(false);expect(nav.finish()).toBe(false);expect(nav.go(1)).toBe(true);expect(nav.finish()).toBe(true);expect(nav.getState().finished).toBe(true);expect(nav.go(2)).toBe(false);nav.go(0);expect(nav.getState().finished).toBe(false);});
 it('preserves a return point when leaving the route and restores it across launches',()=>{const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};const nav=createJourneyNavigator(make(),{storage});nav.start('a',1);nav.finish();nav.leave();expect(nav.getState()).toBeNull();expect(nav.savedPoint().index).toBe(1);const next=createJourneyNavigator(make(),{storage});expect(next.savedPoint()).toEqual({routeId:'a',index:1,finished:true});expect(next.getState()).toBeNull();});
 it('does not rewrite invalid saved data while inspecting it',()=>{let writes=0;const nav=createJourneyNavigator(make(),{storage:{getItem:()=>'{bad',setItem:()=>writes++}});expect(nav.savedPoint()).toBeNull();expect(nav.error()).toBeTruthy();expect(writes).toBe(0);});
 it('keeps an in-memory route when browser storage fails',()=>{const nav=createJourneyNavigator(make(),{storage:{getItem:()=>null,setItem:()=>{throw Error('Full');}}});nav.start('a',1);expect(nav.getState().index).toBe(1);expect(nav.error()).toBe('Full');});
 it('returns copies so a caller cannot change a saved step accidentally',()=>{const nav=createJourneyNavigator(make());nav.start('a');nav.getState().index=10;nav.savedPoint().routeId='missing';expect(nav.getState().index).toBe(0);expect(nav.savedPoint().routeId).toBe('a');});
});
