// Exact authored public-synthetic observations; no private payload is embedded.
pub const PUBLIC: &[(&str, &str, &str)] = &[
    (
        "A",
        "P1-no-namespace",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P1-no-namespace.json"
        ),
    ),
    (
        "A",
        "P10-true-tei",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P10-true-tei.json"
        ),
    ),
    (
        "A",
        "P11-tei-lookalike",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P11-tei-lookalike.json"
        ),
    ),
    (
        "A",
        "P12-dynamic-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P12-dynamic-a.json"
        ),
    ),
    (
        "A",
        "P12-dynamic-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P12-dynamic-b.json"
        ),
    ),
    (
        "A",
        "P13-reorder-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P13-reorder-a.json"
        ),
    ),
    (
        "A",
        "P13-reorder-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P13-reorder-b.json"
        ),
    ),
    (
        "A",
        "P14-text-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P14-text-a.json"
        ),
    ),
    (
        "A",
        "P14-text-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P14-text-b.json"
        ),
    ),
    (
        "A",
        "P15-attribute-value-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P15-attribute-value-a.json"
        ),
    ),
    (
        "A",
        "P15-attribute-value-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P15-attribute-value-b.json"
        ),
    ),
    (
        "A",
        "P2-prefix-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P2-prefix-a.json"
        ),
    ),
    (
        "A",
        "P2-prefix-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P2-prefix-b.json"
        ),
    ),
    (
        "A",
        "P3-default-namespace",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P3-default-namespace.json"
        ),
    ),
    (
        "A",
        "P4-duplicate-siblings",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P4-duplicate-siblings.json"
        ),
    ),
    (
        "A",
        "P5-interleaved-siblings",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P5-interleaved-siblings.json"
        ),
    ),
    (
        "A",
        "P6-empty-long",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P6-empty-long.json"
        ),
    ),
    (
        "A",
        "P6-empty-short",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P6-empty-short.json"
        ),
    ),
    (
        "A",
        "P7-attributes-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P7-attributes-a.json"
        ),
    ),
    (
        "A",
        "P7-attributes-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P7-attributes-b.json"
        ),
    ),
    (
        "A",
        "P8-comments-pi-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P8-comments-pi-a.json"
        ),
    ),
    (
        "A",
        "P8-comments-pi-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P8-comments-pi-b.json"
        ),
    ),
    (
        "A",
        "P9-mixed-namespaces",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/P9-mixed-namespaces.json"
        ),
    ),
    (
        "A",
        "PC1-uxlc-shape",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/a/PC1-uxlc-shape.json"
        ),
    ),
    (
        "B",
        "P1-no-namespace",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P1-no-namespace.json"
        ),
    ),
    (
        "B",
        "P10-true-tei",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P10-true-tei.json"
        ),
    ),
    (
        "B",
        "P11-tei-lookalike",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P11-tei-lookalike.json"
        ),
    ),
    (
        "B",
        "P12-dynamic-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P12-dynamic-a.json"
        ),
    ),
    (
        "B",
        "P12-dynamic-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P12-dynamic-b.json"
        ),
    ),
    (
        "B",
        "P13-reorder-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P13-reorder-a.json"
        ),
    ),
    (
        "B",
        "P13-reorder-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P13-reorder-b.json"
        ),
    ),
    (
        "B",
        "P14-text-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P14-text-a.json"
        ),
    ),
    (
        "B",
        "P14-text-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P14-text-b.json"
        ),
    ),
    (
        "B",
        "P15-attribute-value-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P15-attribute-value-a.json"
        ),
    ),
    (
        "B",
        "P15-attribute-value-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P15-attribute-value-b.json"
        ),
    ),
    (
        "B",
        "P2-prefix-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P2-prefix-a.json"
        ),
    ),
    (
        "B",
        "P2-prefix-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P2-prefix-b.json"
        ),
    ),
    (
        "B",
        "P3-default-namespace",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P3-default-namespace.json"
        ),
    ),
    (
        "B",
        "P4-duplicate-siblings",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P4-duplicate-siblings.json"
        ),
    ),
    (
        "B",
        "P5-interleaved-siblings",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P5-interleaved-siblings.json"
        ),
    ),
    (
        "B",
        "P6-empty-long",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P6-empty-long.json"
        ),
    ),
    (
        "B",
        "P6-empty-short",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P6-empty-short.json"
        ),
    ),
    (
        "B",
        "P7-attributes-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P7-attributes-a.json"
        ),
    ),
    (
        "B",
        "P7-attributes-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P7-attributes-b.json"
        ),
    ),
    (
        "B",
        "P8-comments-pi-a",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P8-comments-pi-a.json"
        ),
    ),
    (
        "B",
        "P8-comments-pi-b",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P8-comments-pi-b.json"
        ),
    ),
    (
        "B",
        "P9-mixed-namespaces",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/P9-mixed-namespaces.json"
        ),
    ),
    (
        "B",
        "PC1-uxlc-shape",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/b/PC1-uxlc-shape.json"
        ),
    ),
    (
        "BC",
        "PC1-uxlc-shape",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/bc/PC1-uxlc-shape.json"
        ),
    ),
    (
        "C",
        "PC1-uxlc-shape",
        include_str!(
            "../../../../../ToS/research-packets/foundation-laboratory-2026-07/generic-xml-resource-inventory-uxlc-abc-v1/public-synthetic/run-1/c/PC1-uxlc-shape.json"
        ),
    ),
];
