//! Complete bounded lens execution on one cold-admitted selected carrier.
//! General matching streams candidates; only bounded winners retain payloads.
use crate::{knowledge_lens_spec::*,knowledge_presentation::{knowledge_scene,lens_carrier},search_v2::{SearchV2Error,SearchV2ErrorCode},source_read_projection::{object,text}};
use std::collections::{BTreeMap,BTreeSet};
use tos_foundation::{JsonValue,JsonLimits,CanonicalProfile,canonical_bytes_v1,parse_json,JsonMode};
#[cfg(not(target_arch="wasm32"))]
use crate::{knowledge_binding::BoundCmpKnowledge,knowledge_inspect::{Reader,InspectBudget,InspectCurrentAuthority,DisclosableInspect,execute_selected_carrier_packet},search_v2::SearchKind};
#[cfg(not(target_arch="wasm32"))]
use tos_compiler::VerifiedKnowledgeModel;
pub const LENS_OPERATION:&str="tos.knowledge.lens.query";
pub const LENS_INTENDED_USE:&str="read_only_public_knowledge_lens_v1";
#[cfg(not(target_arch="wasm32"))]
#[derive(Clone,Copy,Debug)]
pub struct LensBudget {pub inspect:InspectBudget,pub max_candidates:usize,pub max_path_steps:usize,pub max_adjacency_rows:usize,pub block_size:usize}
#[derive(Clone,Debug,Default)]
pub struct LensExecutionCounts{pub available_nodes:usize,pub available_relations:usize,pub matched_nodes:usize,pub matched_relations:usize,pub eligible_relations:usize,pub identity_expansion_limited:bool}
#[cfg(not(target_arch="wasm32"))]
struct Plan<'a,'r,'m,A:?Sized>{read:&'a mut Reader<'r,'m,A>,vocabulary:&'a LensVocabulary,sources:Vec<String>,budget:LensBudget,candidates:usize,path_steps:usize,adjacency:usize}
#[cfg(not(target_arch="wasm32"))]
impl<A:InspectCurrentAuthority+?Sized> Plan<'_, '_, '_,A>{
 fn in_scope(&self,item:&JsonValue)->bool{self.sources.iter().any(|s|s==string(get(item,"source_graph")))}
 fn candidate(&mut self)->Result<(),SearchV2Error>{self.candidates=self.candidates.checked_add(1).ok_or_else(budget)?;if self.candidates>self.budget.max_candidates{return Err(budget())}Ok(())}
 fn item(&mut self,kind:SearchKind,id:&str)->Result<Option<JsonValue>,SearchV2Error>{let rows=self.read.items(kind,"id",id,1,true)?;if rows.len()>1{return Err(corrupt("duplicate exact lens carrier"))}Ok(rows.into_iter().next().filter(|v|self.in_scope(v)))}
 fn scope_scan<F>(&mut self,kind:SearchKind,mut callback:F)->Result<(),SearchV2Error>where F:FnMut(&mut Self,JsonValue)->Result<(),SearchV2Error>{let mut after=None;loop{let rows=self.read.candidate_ids(kind,&self.sources,after.as_ref().map(|(s,id):&(String,String)|(s.as_str(),id.as_str())),self.budget.block_size)?;if rows.is_empty(){break}for(source,id)in &rows{self.candidate()?;let value=self.item(kind,id)?.ok_or_else(||corrupt("candidate selected carrier missing from scope"))?;if string(get(&value,"source_graph"))!=source{return Err(corrupt("candidate source mirror differs"))}callback(self,value)?;}after=rows.last().cloned();}Ok(())}
 fn alias_rows(&mut self,field_name:&str,id:&str)->Result<Vec<JsonValue>,SearchV2Error>{let rows=if field_name=="entity_id"{let mut rows=vec![];let mut after=String::new();loop{let ids=self.read.identity_ids(id,&self.sources,&after,self.budget.block_size)?;if ids.is_empty(){break}for id in &ids{self.candidate()?;rows.push(self.item(SearchKind::Nodes,id)?.ok_or_else(||corrupt("identity carrier closure missing"))?);}after=ids.last().unwrap().clone();}rows}else{let values=self.read.items(SearchKind::Nodes,field_name,id,self.budget.max_candidates.saturating_add(1),true)?;if values.len()>self.budget.max_candidates{return Err(budget())}for _ in &values{self.candidate()?;}values.into_iter().filter(|v|self.in_scope(v)).collect()};Ok(rows)}
 fn focus(&mut self,requested:&str)->Result<JsonValue,SearchV2Error>{if let Some(exact)=self.item(SearchKind::Nodes,requested)?{return Ok(exact)}let mut entities=self.alias_rows("entity_id",requested)?;if !entities.is_empty(){entities.sort_by(|a,b|(self.vocabulary.priority(a),string(get(a,"id"))).cmp(&(self.vocabulary.priority(b),string(get(b,"id")))));return Ok(entities.remove(0))}let mut native=self.alias_rows("native_id",requested)?;if native.len()>1{return Err(invalid("ambiguous native lens focus"))}native.pop().ok_or_else(||SearchV2Error{code:SearchV2ErrorCode::UnknownIdentifier,message:"unknown knowledge lens focus"})}
 fn incident(&mut self,node:&str)->Result<Vec<JsonValue>,SearchV2Error>{let mut rows=vec![];let mut after=String::new();loop{let ids=self.read.incident_ids(node,&after,self.budget.block_size)?;if ids.is_empty(){break}for id in &ids{self.adjacency=self.adjacency.checked_add(1).ok_or_else(budget)?;if self.adjacency>self.budget.max_adjacency_rows{return Err(budget())}if let Some(r)=self.item(SearchKind::Relations,id)?{rows.push(r)}}after=ids.last().unwrap().clone();}Ok(rows)}
 fn path(&mut self,start:&str,condition:&JsonValue)->Result<Option<JsonValue>,SearchV2Error>{fn walk<A:InspectCurrentAuthority+?Sized>(p:&mut Plan<'_, '_, '_,A>,current:&str,index:usize,steps:&[JsonValue],nodes:Vec<JsonValue>,relations:Vec<JsonValue>,id:&str)->Result<Option<JsonValue>,SearchV2Error>{if index==steps.len(){return Ok(Some(object(vec![("path_id",text(id)),("node_ids",JsonValue::Array(nodes)),("relation_ids",JsonValue::Array(relations))])))}let step=&steps[index];for relation in p.incident(current)?{p.path_steps=p.path_steps.checked_add(1).ok_or_else(budget)?;if p.path_steps>p.budget.max_path_steps{return Err(budget())}let rg=get(step,"relation_query");if !boolean(get(rg,"enabled"))||!matches_group(&relation,rg){continue}for neighbor in neighbors(&relation,current,string(get(step,"direction"))){let Some(node)=p.item(SearchKind::Nodes,&neighbor)?else{continue};let ng=get(step,"node_query");if !boolean(get(ng,"enabled"))||!matches_group(&node,ng){continue}let mut n=nodes.clone();n.push(text(&neighbor));let mut r=relations.clone();r.push(get(&relation,"id").clone());if let Some(found)=walk(p,&neighbor,index+1,steps,n,r,id)?{return Ok(Some(found))}}}Ok(None)}walk(self,start,0,array(get(condition,"steps")),vec![text(start)],vec![],string(get(condition,"path_id")))}
 fn scan_nodes<F>(&mut self,spec:&JsonValue,mut callback:F)->Result<(),SearchV2Error>where F:FnMut(&mut Self,JsonValue)->Result<(),SearchV2Error>{let group=get(spec,"node_query");if !boolean(get(group,"enabled")){return Ok(())}let seed=array(field(spec,"seed.node_ids"));let filters=array(get(group,"filters"));let selectors:Vec<_>=filters.iter().map(|f|identity_selector(f,true)).collect();let group_plan=if string(get(group,"match"))=="all"{selectors.iter().flatten().next().cloned().map(|s|vec![s])}else if !selectors.is_empty()&&selectors.iter().all(Option::is_some){Some(selectors.into_iter().flatten().collect())}else{None};
 let identities=if !seed.is_empty(){Some(["id","entity_id","native_id"].iter().map(|f|((*f).to_owned(),seed.iter().map(|v|string(v).to_owned()).collect::<Vec<_>>())).collect::<Vec<_>>())}else{group_plan};
 if let Some(selectors)=identities{let mut seen=BTreeSet::new();for(field,values)in selectors{for value in values{for node in self.alias_rows(&field,&value)?{if seen.insert(string(get(&node,"id")).to_owned()){callback(self,node)?}}}}Ok(())}else{self.scope_scan(SearchKind::Nodes,callback)}
 }
}
#[cfg(not(target_arch="wasm32"))]
fn identity_selector(rule:&JsonValue,node:bool)->Option<(String,Vec<String>)>{if rule.object_get("_property_binding").is_some(){return None}let field=string(get(rule,"field"));if !(if node{&["id","entity_id","native_id"][..]}else{&["id","native_id"][..]}).contains(&field)||!matches!(string(get(rule,"op")),"eq"|"in"){return None}let value=get(rule,"value");let values=value.as_array().unwrap_or(std::slice::from_ref(value));if values.iter().any(|v|v.as_str().is_none()){return None}Some((field.to_owned(),values.iter().map(|v|string(v).to_owned()).collect()))}
fn neighbors(r:&JsonValue,node:&str,direction:&str)->Vec<String>{let mut out=vec![];if direction!="incoming"&&string(get(r,"from_id"))==node{out.push(string(get(r,"to_id")).to_owned())}if direction!="outgoing"&&string(get(r,"to_id"))==node{out.push(string(get(r,"from_id")).to_owned())}out.retain(|s|!s.is_empty());out}
fn relation_regime(r:&JsonValue,spec:&JsonValue,vocabulary:&LensVocabulary)->bool{let predicates=array(field(spec,"traversal.predicate_ids"));(predicates.is_empty()||predicates.iter().any(|p|p==get(r,"predicate_id")))&&(string(field(spec,"traversal.profile"))!="overview"||(!vocabulary.overview_excluded_predicates.iter().any(|p|p==string(get(r,"predicate_id")))&&!vocabulary.overview_excluded_relation_types.iter().any(|p|p==string(get(r,"relation_type_id")))))}
fn top_insert(items:&mut Vec<(JsonValue,Vec<JsonValue>)>,item:JsonValue,proofs:Vec<JsonValue>,rules:&JsonValue,limit:usize){let place=items.binary_search_by(|(v,_)|sort_cmp(v,&item,rules)).unwrap_or_else(|i|i);if place<limit{items.insert(place,(item,proofs));if items.len()>limit{items.pop();}}}
#[cfg(not(target_arch="wasm32"))]
pub fn execute_selected_lens<A:InspectCurrentAuthority+?Sized>(model:&mut VerifiedKnowledgeModel<'_>,bound:&BoundCmpKnowledge<'_>,authority:&mut A,value:&JsonValue,budget_value:LensBudget)->Result<DisclosableInspect,SearchV2Error>{
 if budget_value.max_candidates==0||budget_value.max_candidates>=i64::MAX as usize||budget_value.max_path_steps==0||budget_value.max_adjacency_rows==0||budget_value.block_size==0||budget_value.block_size>budget_value.inspect.max_rows as usize{return Err(budget())}
 execute_selected_carrier_packet(model,bound,authority,LENS_OPERATION,LENS_INTENDED_USE,budget_value.inspect,|read|{
 let header=read.header()?;let vocabulary=LensVocabulary::from_selected(bound,&header)?;let public_spec=normalize_lens_spec(value,&vocabulary)?;let spec=bind_properties(&public_spec,&vocabulary)?;let sources=array(get(&spec,"sources")).iter().map(|v|string(v).to_owned()).collect::<Vec<_>>();let available_nodes=read.scope_count(SearchKind::Nodes,&sources)? as usize;let available_relations=read.scope_count(SearchKind::Relations,&sources)? as usize;
 let mut p=Plan{read,vocabulary:&vocabulary,sources,budget:budget_value,candidates:0,path_steps:0,adjacency:0};let focus=if let Some(id)=field(&spec,"seed.focus_node_id").as_str(){Some(p.focus(id)?)}else{None};let node_limit=uint(field(&spec,"limits.nodes"));let relation_limit=uint(field(&spec,"limits.relations"));let mut matched_nodes=0;let mut focus_matched=false;let mut winners=vec![];let mut focus_proofs=vec![];
 p.scan_nodes(&spec,|p,node|{let selected=array(field(&spec,"seed.node_ids"));if !selected.is_empty()&&!selected.iter().any(|s|["id","native_id","entity_id"].iter().any(|k|get(&node,k)==s)){return Ok(())}let q=lower(string(field(&spec,"seed.text_query")));if !q.is_empty(){let compact=canonical_bytes_v1(&node,CanonicalProfile::SourceRecordDigestV1,budget_value.inspect.json).map_err(|_|budget())?;let source=String::from_utf8(compact).map_err(|_|corrupt("lens searchable JSON invalid"))?;if !lower(&json_spaces(&source)).contains(&q){return Ok(())}}if !matches_group(&node,get(&spec,"node_query")){return Ok(())}let mut proofs=vec![];for condition in array(get(&spec,"path_query")){let witness=p.path(string(get(&node,"id")),condition)?;if witness.is_some()!=(string(get(condition,"quantifier"))=="exists"){return Ok(())}proofs.push(witness.unwrap_or_else(||object(vec![("path_id",get(condition,"path_id").clone()),("absence_in_scope",JsonValue::Bool(true))])));}matched_nodes+=1;if focus.as_ref().is_some_and(|f|get(f,"id")==get(&node,"id")){focus_matched=true;focus_proofs=proofs.clone();}top_insert(&mut winners,node,proofs,field(&spec,"composition.sort_nodes"),node_limit);Ok(())})?;
 let mut selected:BTreeMap<String,JsonValue>=BTreeMap::new();let mut inclusion=object(vec![]);let mut selection_order=vec![];
 if let Some(f)=&focus{let id=string(get(f,"id"));selected.insert(id.to_owned(),f.clone());selection_order.push(id.to_owned());set(&mut inclusion,id,object(vec![("kind",text("focus"))]));if !focus_matched{matched_nodes+=1;}let _=focus_proofs;}
 for(node,proofs)in winners{if selected.len()>=node_limit{break}let id=string(get(&node,"id")).to_owned();if !selected.contains_key(&id){selection_order.push(id.clone());selected.insert(id.clone(),node);set(&mut inclusion,&id,object(vec![("kind",text("selector")),("path_witnesses",JsonValue::Array(proofs))]));}}
 // Relations retain only selectors/sort fields while scanning. Full payloads
 // are authenticated again when consulted for traversal or final delivery.
 let mut relation_keys=vec![];if boolean(field(&spec,"relation_query.enabled")){p.scope_scan(SearchKind::Relations,|p,r|{if relation_regime(&r,&spec,p.vocabulary)&&matches_group(&r,get(&spec,"relation_query")){let mut compact=object(vec![("id",get(&r,"id").clone()),("from_id",get(&r,"from_id").clone()),("to_id",get(&r,"to_id").clone())]);let mut keys=vec![];for sort in array(field(&spec,"composition.sort_relations")){keys.push(field(&r,string(get(sort,"field"))).clone());}set(&mut compact,"_sort",JsonValue::Array(keys));relation_keys.push(compact);}Ok(())})?;}
 let sort_rules=field(&spec,"composition.sort_relations");relation_keys.sort_by(|a,b|{for(i,rule)in array(sort_rules).iter().enumerate(){let av=&array(get(a,"_sort"))[i];let bv=&array(get(b,"_sort"))[i];let mut ord=lower(&py_string(if is_truthy(av){av}else{&text("")})).cmp(&lower(&py_string(if is_truthy(bv){bv}else{&text("")})));if string(get(rule,"direction"))=="desc"{ord=ord.reverse()}if ord!=std::cmp::Ordering::Equal{return ord}}string(get(a,"id")).cmp(string(get(b,"id")))});
 let matched_relations=relation_keys.len();let mut frontier=selection_order.clone();let mut traversed=BTreeSet::new();let mut identity_limited=false;
 for depth in 0..uint(field(&spec,"traversal.depth")){let mut origins:BTreeMap<String,String>=BTreeMap::new();for id in frontier.iter().collect::<BTreeSet<_>>(){let entity=string(get(&selected[id],"entity_id"));if string(field(&spec,"traversal.profile"))=="overview"&&vocabulary.declared_entity(entity){origins.entry(entity.to_owned()).or_insert_with(||id.clone());}}
 let mut aliases=BTreeSet::new();for entity in origins.keys(){for node in p.alias_rows("entity_id",entity)?{let id=string(get(&node,"id"));if !selected.contains_key(id){aliases.insert(id.to_owned());}}}
 for id in aliases{if selected.len()>=node_limit{identity_limited=true;break}let n=p.item(SearchKind::Nodes,&id)?.ok_or_else(||corrupt("traversal identity missing"))?;let entity=string(get(&n,"entity_id")).to_owned();selected.insert(id.clone(),n);frontier.push(id.clone());set(&mut inclusion,&id,object(vec![("kind",text("identity-carrier")),("via_node_id",text(&origins[&entity])),("entity_id",text(&entity)),("depth",number(depth))]));}
 let mut next=vec![];let frontier_set:BTreeSet<_>=frontier.iter().cloned().collect();let mut incident_ids=BTreeSet::new();for id in &frontier{for relation in p.incident(id)?{incident_ids.insert(string(get(&relation,"id")).to_owned());}}
 for relation in relation_keys.iter().filter(|r|incident_ids.contains(string(get(r,"id")))){let rid=string(get(relation,"id"));let mut touched=false;for id in &frontier{for neighbor in neighbors(relation,id,string(field(&spec,"traversal.direction"))){touched=true;if !selected.contains_key(&neighbor)&&selected.len()<node_limit{if let Some(node)=p.item(SearchKind::Nodes,&neighbor)?{selected.insert(neighbor.clone(),node);next.push(neighbor.clone());set(&mut inclusion,&neighbor,object(vec![("kind",text("traversal")),("via_node_id",text(id)),("via_relation_id",text(rid)),("depth",number(depth+1))]));}}}}if touched&&traversed.len()<relation_limit{traversed.insert(rid.to_owned());}}
 let _=frontier_set;frontier=next;if frontier.is_empty(){break}}
 let basis:BTreeSet<_>=selected.keys().cloned().collect();let policy=string(field(&spec,"composition.endpoint_policy"));let mut eligible=0;let mut returned_relations=vec![];
 for key in relation_keys{let id=string(get(&key,"id"));let left=string(get(&key,"from_id"));let right=string(get(&key,"to_id"));let allowed=match policy{"both"=>basis.contains(left)&&basis.contains(right),"either"=>basis.contains(left)||basis.contains(right),"independent"=>true,_=>false}||traversed.contains(id);if !allowed{continue}eligible+=1;if returned_relations.len()>=relation_limit{continue}let mut missing=vec![];for endpoint in [left,right]{if !selected.contains_key(endpoint)&&!missing.contains(&endpoint){missing.push(endpoint)}}if selected.len()+missing.len()>node_limit{continue}for endpoint in missing{if let Some(n)=p.item(SearchKind::Nodes,endpoint)?{selected.insert(endpoint.to_owned(),n);set(&mut inclusion,endpoint,object(vec![("kind",text("endpoint")),("via_relation_id",text(id))]));}}if selected.contains_key(left)&&selected.contains_key(right){let relation=p.item(SearchKind::Relations,id)?.ok_or_else(||corrupt("selected relation closure absent"))?;returned_relations.push(relation)}}
 finalize_knowledge_lens(&public_spec,selected.into_values().collect(),returned_relations,bound.source_revision(),get(&header,"authority_boundary"),LensExecutionCounts{available_nodes,available_relations,matched_nodes,matched_relations,eligible_relations:eligible,identity_expansion_limited:identity_limited},focus.as_ref(),&inclusion,&traversed,None,&vocabulary)
 })
}
fn is_truthy(v:&JsonValue)->bool{match v{JsonValue::Null=>false,JsonValue::Bool(b)=>*b,JsonValue::Number(n)=>n.lexeme.parse::<f64>().ok().is_some_and(|n|n!=0.),JsonValue::String(_)=>!string(v).is_empty(),JsonValue::Array(a)=>!a.is_empty(),JsonValue::Object(o)=>!o.is_empty()}}
fn json_spaces(s:&str)->String{let mut out=String::new();let mut quoted=false;let mut escaped=false;for c in s.chars(){out.push(c);if quoted{if escaped{escaped=false}else if c=='\\'{escaped=true}else if c=='"'{quoted=false}}else if c=='"'{quoted=true}else if c==':'||c==','{out.push(' ')}}out}

/// Finalize a bounded, exact selection. Selection/count authority remains with
/// the selected executor; this pure function adds delivery and presentation.
pub fn finalize_knowledge_lens(public:&JsonValue,mut nodes:Vec<JsonValue>,mut relations:Vec<JsonValue>,revision:&str,authority:&JsonValue,counts:LensExecutionCounts,resolved_focus:Option<&JsonValue>,inclusion:&JsonValue,traversed:&BTreeSet<String>,publication:Option<&JsonValue>,vocabulary:&LensVocabulary)->Result<JsonValue,SearchV2Error>{
 sort_items(&mut nodes,field(public,"composition.sort_nodes"));sort_items(&mut relations,field(public,"composition.sort_relations"));let focus=if let Some(requested)=field(public,"seed.focus_node_id").as_str(){let resolved=resolved_focus.ok_or_else(||corrupt("resolved lens focus absent"))?;let n=nodes.iter().find(|n|get(n,"id")==get(resolved,"id")).ok_or_else(||corrupt("resolved lens focus missing from retained nodes"))?;let by=if string(get(n,"id"))==requested{"id"}else if string(get(n,"entity_id"))==requested{"entity_id"}else{"native_id"};let mut out=object(vec![("requested_id",text(requested)),("resolved_by",text(by)),("node_id",get(n,"id").clone())]);for k in ["entity_id","native_id","source_graph","kind_id","type_id","display"]{set(&mut out,k,get(n,k).clone())}out}else{JsonValue::Null};
 let groups=groups(&nodes,&relations,array(field(public,"composition.group_by")),uint(field(public,"limits.groups")));let refs:BTreeSet<_>=nodes.iter().chain(&relations).flat_map(|v|array(get(v,"source_refs")).iter().filter_map(JsonValue::as_str)).filter(|s|!s.is_empty()).collect();
 let missing_summaries=nodes.iter().filter(|n|string(field(n,"display.summary_state"))=="missing").count();let missing_explanations=relations.iter().filter(|n|string(field(n,"display.explanation_state"))=="missing").count();let no_summary=nodes.iter().filter(|n|matches!(field(n,"display.provenance.source_summary_available"),JsonValue::Bool(false))).count();let no_explanation=relations.iter().filter(|n|matches!(field(n,"display.provenance.source_explanation_available"),JsonValue::Bool(false))).count();let truncated_nodes=counts.matched_nodes.saturating_sub(uint(field(public,"limits.nodes")));let truncated_relations=counts.eligible_relations.saturating_sub(relations.len());let mut lens_for_digest=public.clone();remove(&mut lens_for_digest,"pagination");let pairs=|items:&[JsonValue]|JsonValue::Array(items.iter().map(|i|JsonValue::Array(vec![get(i,"id").clone(),get(i,"content_revision").clone()])).collect());let fingerprint=stable_digest(&object(vec![("execution_version",text("tos-lens-execution-v7")),("source_revision",text(revision)),("lens",lens_for_digest),("nodes",pairs(&nodes)),("relations",pairs(&relations)),("groups",JsonValue::Array(groups.clone()))]))?;
 let cursor_fingerprint=if let Some(publication)=publication{if !matches!(get(public,"pagination"),JsonValue::Null){Some(stable_digest(&object(vec![("schema",text("tos_published_lens_cursor_v1")),("publication",publication.clone()),("fingerprint",text(&fingerprint))]))?)}else{None}}else{None};
 let mut warnings=vec![];if counts.identity_expansion_limited{warnings.push(text("identity carrier expansion reached the node budget; use resumable exploration or narrower sources"))}for(n,template)in [(missing_summaries,"nodes expose an explicit missing-summary state"),(missing_explanations,"relations expose an explicit missing-explanation state"),(no_summary,"nodes use transparent metadata synthesis because no source summary is projected"),(no_explanation,"relations use transparent metadata synthesis because no source explanation is projected")]{if n>0{warnings.push(text(&format!("{n} {template}")))}}if truncated_nodes>0{warnings.push(text(&format!("node selector exceeded its bounded result by {truncated_nodes} nodes")))}if truncated_relations>0{warnings.push(text(&format!("relation selector exceeded its bounded result by {truncated_relations} relations")))}
 let lang=string(get(public,"language"));let detail=string(get(public,"detail"));let delivered_nodes=nodes.iter().map(|n|lens_carrier(n,detail,Some(lang))).collect::<Result<Vec<_>,_>>()?;let delivered_relations=relations.iter().map(|r|lens_carrier(r,detail,Some(lang))).collect::<Result<Vec<_>,_>>()?;
 let mut out=object(vec![("schema",text("tos_lens_result_v1")),("source_revision",text(revision)),("lens",public.clone()),("fingerprint",text(&fingerprint)),("presentation",get(public,"presentation").clone()),("focus",focus.clone()),("nodes",JsonValue::Array(delivered_nodes)),("relations",JsonValue::Array(delivered_relations)),("groups",JsonValue::Array(groups.clone())),("facets",object(vec![("node_kinds",counter(&nodes,"kind_id")),("predicates",counter(&relations,"predicate_id")),("sources",counter(&nodes,"source_graph"))])),("counts",object(vec![("available_nodes",number(counts.available_nodes)),("available_relations",number(counts.available_relations)),("matched_nodes",number(counts.matched_nodes)),("matched_relations",number(counts.matched_relations)),("eligible_relations",number(counts.eligible_relations)),("nodes",number(nodes.len())),("relations",number(relations.len())),("groups",number(groups.len())),("truncated_nodes",number(truncated_nodes)),("truncated_relations",number(truncated_relations)),("identity_expansion_limited",JsonValue::Bool(counts.identity_expansion_limited)),("missing_node_summaries",number(missing_summaries)),("missing_relation_explanations",number(missing_explanations)),("nodes_without_source_summary",number(no_summary)),("relations_without_source_explanation",number(no_explanation))])),("source_refs",JsonValue::Array(refs.iter().map(|s|text(s)).collect())),("warnings",JsonValue::Array(warnings)),("authority_boundary",authority.clone()),("agent_summary",object(vec![("lens_id",get(public,"lens_id").clone()),("focus_node_id",get(&focus,"node_id").clone()),("node_count",number(nodes.len())),("relation_count",number(relations.len())),("group_count",number(groups.len())),("source_ref_count",number(refs.len())),("is_source",JsonValue::Bool(false)),("writes_to_tree",JsonValue::Bool(false))]))]);
 if boolean(get(public,"explain")){set(&mut out,"inclusion",object(vec![("nodes",inclusion.clone()),("relations",object(relations.iter().map(|r|(string(get(r,"id")),object(vec![("kind",text(if traversed.contains(string(get(r,"id"))){"traversal"}else{"endpoint-policy"})),("endpoint_policy",field(public,"composition.endpoint_policy").clone())]))).collect())),("authority",text("query-execution-not-semantic-proof"))]));}
 out=paginate_lens(out,cursor_fingerprint.as_deref())?;let scene=knowledge_scene(array(get(&out,"nodes")),array(get(&out,"relations")),get(&focus,"node_id").as_str(),None,vocabulary)?;set(&mut out,"scene",scene);Ok(out)
}
fn counter(items:&[JsonValue],key:&str)->JsonValue{let mut counts=BTreeMap::new();for i in items{*counts.entry(py_string(get(i,key))).or_insert(0usize)+=1;}object(counts.iter().map(|(k,v)|(k.as_str(),number(*v))).collect())}
fn groups(nodes:&[JsonValue],relations:&[JsonValue],fields:&[JsonValue],limit:usize)->Vec<JsonValue>{let mut out=vec![];for f in fields{let f=string(f);let mut values:BTreeMap<String,JsonValue>=BTreeMap::new();let mut ordered_keys=vec![];for (kind,items)in [("node",nodes),("relation",relations)]{for item in items{let raw=field(item,f);for member in raw.as_array().unwrap_or(std::slice::from_ref(raw)){if matches!(member,JsonValue::Null){continue}let key=py_string(member);if !values.contains_key(&key){ordered_keys.push(key.clone());values.insert(key.clone(),object(vec![("field",text(f)),("value",member.clone()),("node_ids",JsonValue::Array(vec![])),("relation_ids",JsonValue::Array(vec![]))]));}let entry=values.get_mut(&key).unwrap();let slot=format!("{kind}_ids");let mut ids=array(get(entry,&slot)).to_vec();ids.push(get(item,"id").clone());set(entry,&slot,JsonValue::Array(ids));}}}ordered_keys.sort_by_key(|s|s.to_lowercase());for key in ordered_keys{let mut entry=values.remove(&key).unwrap();let nc=array(get(&entry,"node_ids")).len();let rc=array(get(&entry,"relation_ids")).len();set(&mut entry,"node_count",number(nc));set(&mut entry,"relation_count",number(rc));out.push(entry);if out.len()>=limit{return out}}}out}
const BASE64:&[u8;64]=b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
fn b64_encode(input:&[u8])->String{let mut out=String::new();let mut bits=0u32;let mut count=0usize;for byte in input{bits=(bits<<8)|*byte as u32;count+=8;while count>=6{count-=6;out.push(BASE64[((bits>>count)&63)as usize]as char)}}if count>0{out.push(BASE64[((bits<<(6-count))&63)as usize]as char)}out}
fn b64_decode(s:&str)->Result<Vec<u8>,SearchV2Error>{if s.len()%4==1{return Err(invalid("invalid lens cursor"))}let mut out=vec![];let mut bits=0u32;let mut count=0usize;for byte in s.bytes(){let v=BASE64.iter().position(|b|*b==byte).ok_or_else(||invalid("invalid lens cursor"))?;bits=(bits<<6)|v as u32;count+=6;if count>=8{count-=8;out.push((bits>>count)as u8)}}Ok(out)}
pub fn paginate_lens(mut result:JsonValue,cursor_fingerprint:Option<&str>)->Result<JsonValue,SearchV2Error>{let options=field(&result,"lens.pagination").clone();if matches!(options,JsonValue::Null){return Ok(result)}let fingerprint=cursor_fingerprint.unwrap_or(string(get(&result,"fingerprint"))).to_owned();let mut no=0;let mut ro=0;let nodes=array(get(&result,"nodes"));let relations=array(get(&result,"relations"));if let Some(cursor)=get(&options,"cursor").as_str(){let bytes=b64_decode(cursor)?;let token=parse_json(&bytes,JsonMode::PublishedStrict,JsonLimits::default()).map_err(|_|invalid("invalid lens cursor"))?.into_root();if token.as_object().is_none_or(|o|o.len()!=4||o.iter().any(|(k,_)|!matches!(k.as_str(),Some("v"|"fingerprint"|"n"|"r"))))||get(&token,"v").as_u64()!=Some(1)||get(&token,"fingerprint").as_str().is_none_or(|s|tos_foundation::Digest256::from_hex(s).is_err()){return Err(invalid("invalid lens cursor"))}let n=get(&token,"n").as_u64().filter(|n|*n<=2000).ok_or_else(||invalid("invalid lens cursor position"))? as usize;let r=get(&token,"r").as_u64().filter(|n|*n<=2000).ok_or_else(||invalid("invalid lens cursor position"))? as usize;if string(get(&token,"fingerprint"))!=fingerprint{return Err(SearchV2Error{code:SearchV2ErrorCode::StaleSelection,message:"lens query or snapshot changed; restart pagination"})}if n>nodes.len()||r>relations.len(){return Err(invalid("invalid lens cursor position"))}no=n;ro=r;}
 let primary=&nodes[no..(no+uint(get(&options,"nodes"))).min(nodes.len())];let rels=relations[ro..(ro+uint(get(&options,"relations"))).min(relations.len())].to_vec();let primary_ids:BTreeSet<_>=primary.iter().map(|n|string(get(n,"id"))).collect();let primary_list=JsonValue::Array(primary.iter().map(|n|get(n,"id").clone()).collect());let mut selected=primary_ids.clone();for relation in &rels{selected.insert(string(get(relation,"from_id")));selected.insert(string(get(relation,"to_id")));}if let Some(f)=field(&result,"focus.node_id").as_str(){selected.insert(f);}let retained_nodes:Vec<_>=nodes.iter().filter(|n|selected.contains(string(get(n,"id")))).cloned().collect();let contexts=JsonValue::Array(retained_nodes.iter().filter(|n|!primary_ids.contains(string(get(n,"id")))).map(|n|get(n,"id").clone()).collect());let nn=no+primary.len();let nr=ro+rels.len();let has_more=nn<nodes.len()||nr<relations.len();let next=if has_more{let bytes=format!("{{\"v\":1,\"fingerprint\":\"{fingerprint}\",\"n\":{nn},\"r\":{nr}}}");text(&b64_encode(bytes.as_bytes()))}else{JsonValue::Null};let relation_ids:BTreeSet<_>=rels.iter().map(|r|string(get(r,"id")))).collect();let selected_owned:BTreeSet<_>=selected.iter().map(|s|(*s).to_owned()).collect();let relation_owned:BTreeSet<_>=relation_ids.iter().map(|s|(*s).to_owned()).collect();let mut new_groups=vec![];for group in array(get(&result,"groups")){let mut group=group.clone();let ns:Vec<_>=array(get(&group,"node_ids")).iter().filter(|id|selected_owned.contains(string(id))).cloned().collect();let rs:Vec<_>=array(get(&group,"relation_ids")).iter().filter(|id|relation_owned.contains(string(id))).cloned().collect();if !ns.is_empty()||!rs.is_empty(){set(&mut group,"node_count",number(ns.len()));set(&mut group,"relation_count",number(rs.len()));set(&mut group,"node_ids",JsonValue::Array(ns));set(&mut group,"relation_ids",JsonValue::Array(rs));new_groups.push(group)}}
 let page=object(vec![("next_cursor",next),("has_more",JsonValue::Bool(has_more)),("primary_node_ids",primary_list),("context_node_ids",contexts),("returned_nodes",number(retained_nodes.len())),("returned_relations",number(rels.len())),("scope",text("bounded-lens-result")),("counts_scope",text("complete-bounded-result"))]);set(&mut result,"nodes",JsonValue::Array(retained_nodes));set(&mut result,"relations",JsonValue::Array(rels));set(&mut result,"groups",JsonValue::Array(new_groups));set(&mut result,"page",page);if let Some(inclusion)=result.object_get("inclusion"){let mut inc=inclusion.clone();for(k,ids)in [("nodes",&selected_owned),("relations",&relation_owned)]{let fields=get(&inc,k).as_object().unwrap_or(&[]).iter().filter(|(key,_)|ids.contains(key.as_str().unwrap_or(""))).map(|(key,v)|(key.clone(),v.clone())).collect();set(&mut inc,k,JsonValue::Object(fields));}set(&mut result,"inclusion",inc);}Ok(result)
}
