#!/usr/bin/env python3
"""Copy the owner-pinned Unicode 16 lower tables into a Rust companion.

This consumes the exact generated Worker table at the frozen source revision;
it does not query host Unicode data or download anything.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

EXPECTED_SHA256 = "e9ab817aef6bf870fc8b855cffe7c06ac46aa6a68e6c259c75920f1bcfbb42e6"
BASE = Path(__file__).resolve().parents[3]
SOURCE = BASE / "access/shared/native-unicode.generated.ts"
OUTPUT = Path(__file__).with_name("src") / "unicode_generated.rs"


def export(text: str, name: str):
    prefix = f"export const {name}"
    for line in text.splitlines():
        if line.startswith(prefix):
            return json.loads(line.split(" = ", 1)[1].removesuffix(";"))
    raise ValueError(f"missing generated table: {name}")


def rust_string(value: str) -> str:
    parts = ['"']
    for char in value:
        point = ord(char)
        if char in {'"', '\\'}:
            parts.append('\\' + char)
        elif point < 0x20 or point == 0x7f:
            parts.append(f"\\u{{{point:x}}}")
        else:
            parts.append(char)
    parts.append('"')
    return "".join(parts)


def build() -> str:
    raw = SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest() != EXPECTED_SHA256:
        raise ValueError("owner Unicode generated table digest differs")
    text = raw.decode("utf-8")
    if export(text, "nativeUnicodeVersion") != "16.0.0":
        raise ValueError("owner Unicode version differs")
    if export(text, "nativeUnicodeAlgorithm") != "tos-python-native-unicode-v1":
        raise ValueError("owner Unicode algorithm differs")
    lower = export(text, "nativeLowerMappings")
    cased = export(text, "nativeCasedRanges")
    ignorable = export(text, "nativeCaseIgnorableRanges")
    lines = [
        "// Generated by generate_unicode.py from owner-pinned native-unicode.generated.ts.",
        "// Source SHA-256: " + EXPECTED_SHA256,
        "// Unicode 16.0.0; algorithm tos-python-native-unicode-v1.",
        "// Unicode data license: access/shared/UNICODE-LICENSE.txt.",
        "const LOWER: &[(u32, &str)] = &[",
    ]
    lines += [f"    ({point}, {rust_string(mapped)})," for point, mapped in lower]
    lines.append("];")
    for name, values in [("CASED", cased), ("CASE_IGNORABLE", ignorable)]:
        lines.append(f"const {name}: &[(u32, u32)] = &[")
        lines += [f"    ({start}, {end})," for start, end in values]
        lines.append("];")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = build()
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("Rust Unicode companion differs")
    else:
        OUTPUT.write_text(generated, encoding="utf-8")
    print(f"Unicode 16.0.0 pinned Rust companion: {len(generated.encode())} bytes")
