// Node Playwright platform host for all former access/e2e/test_webmcp.py cases.
// Browser behavior is real; native fixture packets are served by tos-e2e-fixture.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {readFileSync} from 'node:fs';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {test} from 'node:test';

const HERE=path.dirname(fileURLToPath(import.meta.url));
const ROOT=path.resolve(HERE,'../..');
const WEB=path.join(ROOT,'access/web');
const SOURCE_RECORD=JSON.parse(readFileSync(path.join(ROOT,'ToS/source-witnesses/works/friedrich-nietzsche/jenseits-von-gut-und-boese/work.json'),'utf8'));
const playwrightRoot=process.env.TOS_E2E_NODE_MODULES?path.dirname(process.env.TOS_E2E_NODE_MODULES):ROOT;
const globalRequire=createRequire(path.join(playwrightRoot,'package.json'));
const {chromium}=globalRequire('playwright');
const {createServer}=createRequire(path.join(WEB,'package.json'))('vite');
const FIXTURE_BIN=process.env.TOS_E2E_FIXTURE_BIN??path.join(ROOT,'target/debug/tos-e2e-fixture');
const SITE_EXE=process.env.TOS_E2E_SITE_EXECUTABLE;
const MODEL_CONTEXT_INIT=`(() => {
  const active = new Map(), all = [];
  const names = () => [...active.keys()].sort();
  const first = name => all.find(tool => tool.name === name);
  const invoke = async (name,input={}) => { const tool=active.get(name); if(!tool)throw new Error('missing WebMCP tool: '+name); return tool.execute(input,{signal:new AbortController().signal}); };
  const invokeFirst = async (name,input={}) => { const tool=first(name); if(!tool)throw new Error('missing historical WebMCP tool: '+name); try{return {ok:true,value:await tool.execute(input,{signal:new AbortController().signal})};}catch(error){return {ok:false,name:error?.name,message:error?.message};} };
  const invokeAbort = async (name,input={}) => { const tool=active.get(name); if(!tool)throw new Error('missing WebMCP tool: '+name); const controller=new AbortController(); const pending=tool.execute(input,{signal:controller.signal}); setTimeout(()=>controller.abort(new DOMException('e2e cancellation','AbortError')),0); try{return {ok:true,value:await pending};}catch(error){return {ok:false,name:error?.name,message:error?.message};} };
  window.__TOS_E2E={names,invoke,invokeFirst,invokeAbort,all};
  Object.defineProperty(document,'modelContext',{configurable:true,value:{registerTool:async(tool,options={})=>{active.set(tool.name,tool);all.push(tool);options.signal?.addEventListener('abort',()=>{if(active.get(tool.name)===tool)active.delete(tool.name);},{once:true});}}});
})();`;

// Poll from the Node host: waitForFunction evaluates its predicate inside the
// page timer and conflicts with the installed host's strict CSP.
async function waitFor(page,expression,timeout=30000,arg=null){
  const until=performance.now()+timeout;
  do{
    let timer;
    const matched=await Promise.race([
      page.evaluate(expression,arg),
      new Promise((_,reject)=>{timer=setTimeout(()=>reject(new Error(`Browser condition did not settle within ${timeout}ms`)),Math.max(1,until-performance.now()));}),
    ]).finally(()=>clearTimeout(timer));
    if(matched)return;
    await new Promise(resolve=>setTimeout(resolve,100));
  }while(performance.now()<until);
  throw new Error(`Browser condition did not settle within ${timeout}ms`);
}
function textResult(result){return JSON.parse(result.content[0].text);}
function commandValue(result){const value=textResult(result);return value.value??value;}
function canonicalJson(value){if(Array.isArray(value))return `[${value.map(canonicalJson).join(',')}]`;if(value&&typeof value==='object')return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonicalJson(value[key])}`).join(',')}}`;return JSON.stringify(value);}
function canonicalDigest(value){return createHash('sha256').update(canonicalJson(value),'utf8').digest('hex');}
function invoke(page,name,input={}){return page.evaluate(([tool,args])=>window.__TOS_E2E.invoke(tool,args),[name,input]);}
function readText(page,selector){return page.locator(selector).innerText();}
function q(value){return encodeURIComponent(value);}

async function startNative(scenario='default'){
  if(!SITE_EXE)throw new Error('TOS_E2E_SITE_EXECUTABLE must identify the verified installed native package');
  const child=spawn(FIXTURE_BIN,['serve','--site-executable',SITE_EXE,'--scenario',scenario],{stdio:['ignore','pipe','inherit']});
  const base=await new Promise((resolve,reject)=>{
    let output='';const timer=setTimeout(()=>reject(new Error('native browser fixture did not become ready: '+output)),30000);
    child.once('error',error=>{clearTimeout(timer);reject(error);});
    child.once('exit',(code,signal)=>{clearTimeout(timer);reject(new Error(`native browser fixture exited before ready (${code??signal}): ${output}`));});
    child.stdout.setEncoding('utf8');child.stdout.on('data',chunk=>{output+=chunk;const match=output.match(/ready (http:\/\/\S+)/);if(match){clearTimeout(timer);resolve(match[1]);}});
  });
  return {base,close:async()=>{if(child.exitCode!==null)return;child.kill('SIGTERM');await new Promise(resolve=>{const timer=setTimeout(()=>{child.kill('SIGKILL');resolve();},5000);child.once('exit',()=>{clearTimeout(timer);resolve();});});}};
}
async function startVite(){
  const server=await createServer({configFile:path.join(WEB,'vite.config.ts'),root:WEB,logLevel:'silent',server:{host:'127.0.0.1',port:0,strictPort:false}});
  await server.listen();const address=server.httpServer.address();
  return {base:`http://127.0.0.1:${address.port}`,close:()=>server.close()};
}
async function openBrowserPage(url,{webmcp=true,locale='en-US',viewport}={}){
  const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.TOS_E2E_CHROMIUM?{executablePath:process.env.TOS_E2E_CHROMIUM}:{})});
  const context=await browser.newContext({locale,acceptDownloads:true,...(viewport?{viewport}:{})});
  if(webmcp)await context.addInitScript(MODEL_CONTEXT_INIT);
  const page=await context.newPage();await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});
  return {browser,context,page,close:async()=>{await context.close();await browser.close();}};
}
async function withNative(scenario,fn,{webmcp=true,locale='en-US'}={}){
  const host=await startNative(scenario);let opened;
  try{opened=await openBrowserPage(`${host.base}/?mode=philosophy&view=chronology&graph=nodes&ui=en`,{webmcp,locale});
    await waitFor(opened.page,'Boolean(document.getElementById("current-view-title")?.textContent)');
    if(webmcp){await waitFor(opened.page,"window.__TOS_E2E.names().includes('tos.page.context')");}
    await fn(opened.page,host.base);
  }finally{if(opened)await opened.close();await host.close();}
}
async function withVite(fn){const host=await startVite();try{await fn(host.base);}finally{await host.close();}}
async function idbReadings(page,dbName,store='readings'){
  return page.evaluate(async([name,storeName])=>{const db=await new Promise((resolve,reject)=>{const req=indexedDB.open(name);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});try{return await new Promise((resolve,reject)=>{const req=db.transaction(storeName,'readonly').objectStore(storeName).getAll();req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}finally{db.close();}},[dbName,store]);
}
async function waitForReading(page,dbName,predicate,store='readings',timeout=15000){const until=Date.now()+timeout;while(Date.now()<until){const items=await idbReadings(page,dbName,store);if(items.some(predicate))return items;await page.waitForTimeout(100);}throw new Error(`IndexedDB reading did not settle for ${dbName}`);}
async function firstEdgeAndNode(page){const payload=await page.evaluate(async()=>await(await fetch('/api/philosophy/views/chronology?limit=1000')).json());const edge=payload.edges.find(item=>item.edge_id&&item.from_id&&item.to_id);assert.ok(edge);return [String(edge.edge_id),String(edge.from_id)];}
async function downloadJson(page,button){const [download]=await Promise.all([page.waitForEvent('download'),button.click()]);return JSON.parse(await readFile(await download.path(),'utf8'));}

// 1. WebMCP registration, bounded command output, route staging and stale deixis.
test('test_real_browser_webmcp_loop_and_stale_deixis',async()=>withNative('default',async page=>{
  const names=await page.evaluate('window.__TOS_E2E.names()');
  assert.ok(names.includes('tos.page.context'));assert.ok(names.includes('tos.page.research-workspace'));assert.ok(names.includes('tos.zarathustra.word-analysis.prepare'));
  assert.equal(await page.locator('#agent-surface').getAttribute('data-webmcp-state'),'connected');assert.match(await readText(page,'#agent-surface'),/Codex WebMCP ready/);
  const word=await invoke(page,'tos.zarathustra.word-analysis.prepare',{query:'судьбы',language:'ru',rank:1});assert.ok(word.content[0].text.length<1500);
  const wordPacket=commandValue(word);assert.equal(wordPacket.available,false);assert.equal(wordPacket.publication_posture,'excluded_from_public_bundle');assert.equal(wordPacket.page_updated,true);assert.match(await readText(page,'#detail-list'),/Source-bound word analysis/);
  const [edgeId,nodeId]=await firstEdgeAndNode(page);await invoke(page,'tos.page.select',{item_id:edgeId});await waitFor(page,"window.__TOS_E2E.names().includes('tos.page.add-session-hypothesis')");
  for(const name of ['tos.page.inspect-selection','tos.page.add-note-to-selection','tos.page.compare-readings','tos.page.stage-proposal','tos.page.exclude-selected-edge','tos.page.save-route-comparison'])assert.ok((await page.evaluate('window.__TOS_E2E.names()')).includes(name));
  const selectionResult=await invoke(page,'tos.page.inspect-selection');assert.ok(selectionResult.content[0].text.length<1500);const selected=commandValue(selectionResult);assert.equal(selected.selection.id,edgeId);assert.equal(selected.selection.semantic_kind,'relation');
  const comparisonResult=await invoke(page,'tos.page.compare-readings',{limit:20});assert.ok(comparisonResult.content[0].text.length<1500);const compared=commandValue(comparisonResult);assert.equal(compared.schema,'tos_interpretation_comparison_v1');assert.equal(compared.page_updated,true);assert.match(await readText(page,'#detail-list'),/Interpretation comparison/);
  const proposalResult=await invoke(page,'tos.page.stage-proposal',{kind:'interpretation',statement:'Treat this route as a reviewable alternative.',source_refs:['ToS/philosophy/atlas/atlas.manifest.json'],evidence_refs:[edgeId],confidence:'low'});assert.ok(proposalResult.content[0].text.length<1500);const proposal=commandValue(proposalResult);
  assert.equal(proposal.proposal.status,'pending_review');assert.deepEqual(proposal.authority,{source:false,reviewed:false,canon:false});assert.match(await readText(page,'#research-workspace-body'),/pending_review/);
  const old=await page.evaluate("window.__TOS_E2E.invokeFirst('tos.page.context')");assert.equal(commandValue(old.value).selected.id,edgeId);
  await page.locator('#research-workspace-panel > summary').click();await page.locator('#workspace-note-input').fill('Human note');await page.locator('#workspace-add-note').click();await waitFor(page,"document.getElementById('research-workspace-summary')?.textContent?.includes('1N')");
  const note=commandValue(await invoke(page,'tos.page.add-research-note',{text:'Agent note'}));assert.equal(note.research_workspace.note_count,2);assert.match(await readText(page,'#research-workspace-body'),/Agent note/);
  const hypothesis=commandValue(await invoke(page,'tos.page.add-session-hypothesis',{statement:'Keep this as a local possibility.'}));assert.deepEqual(hypothesis.authority,{source:false,reviewed:false,canon:false});assert.deepEqual(hypothesis.hypothesis.posture,{session_hypothesis:true,source:false,reviewed:false,canon:false});assert.match((await readText(page,'#research-workspace-body')).toLowerCase(),/not source/);
  await invoke(page,'tos.page.save-route-comparison',{label:'Direct'});await invoke(page,'tos.page.save-route-comparison',{label:'Alternative'});const workspace=commandValue(await invoke(page,'tos.page.research-workspace'));assert.equal(workspace.research_workspace.comparison_count,2);assert.equal(workspace.route_preview.length,2);
  await invoke(page,'tos.page.select',{item_id:nodeId});const stale=await page.evaluate("window.__TOS_E2E.invokeFirst('tos.page.add-session-hypothesis',{statement:'stale'})");assert.equal(stale.ok,false);assert.match(stale.message,/stale page context revision/);
}));

// 2. Source gap search remains a reviewable route only.
test('test_real_browser_source_gap_research_stages_reviewable_route',async()=>withNative('default',async page=>{
  assert.ok((await page.evaluate('window.__TOS_E2E.names()')).includes('tos.page.find-source-gaps'));
  const found=textResult(await invoke(page,'tos.page.find-source-gaps',{query:'Nietzsche',limit:20}));assert.ok(found.result_count>=2);assert.match(found.authority_note,/corpus-completeness/);
  const lexical=found.gaps.find(gap=>gap.label.includes('Nietzsche-Wörterbuch'));assert.ok(lexical);assert.match(await readText(page,'#detail-list'),/Nietzsche-Wörterbuch/);
  await invoke(page,'tos.page.select',{item_id:lexical.id});await waitFor(page,"window.__TOS_E2E.names().includes('tos.page.stage-proposal')");assert.ok(!(await page.evaluate('window.__TOS_E2E.names()')).includes('tos.page.inspect-epistemic'));
  const staged=commandValue(await invoke(page,'tos.page.stage-proposal',{kind:'source_route',statement:'Verify a lawful current institutional route to the relevant Nietzsche-Wörterbuch article before source use.',confidence:'unknown'}));assert.equal(staged.proposal.status,'pending_review');assert.deepEqual(staged.authority,{source:false,reviewed:false,canon:false});
}));

// 3. Frozen exact metadata read, source disclosure and export identity.
test('test_real_browser_sources_panel_reads_frozen_metadata_record',async()=>withNative('source',async(page,base)=>{
  const [_,nodeId]=await firstEdgeAndNode(page);const id='philosophy:'+nodeId;await page.goto(`${base}/?focus=${q(id)}&ui=en`,{waitUntil:'domcontentloaded'});await waitFor(page,"window.__TOS_E2E.names().includes('tos.page.context')");
  await invoke(page,'tos.page.select',{item_id:id});await waitFor(page,"window.__TOS_E2E.names().includes('tos.page.inspect-selection')");
  const packet=await page.evaluate(async id=>await(await fetch('/api/knowledge/nodes/'+encodeURIComponent(id)+'?relation_limit=0')).json(),id);const target=packet.source_read_targets[id].target;
  const expectedDigest='sha256:'+canonicalDigest(SOURCE_RECORD);assert.equal(target.layer,'metadata_record');assert.equal(target.record_type,SOURCE_RECORD.record_type);assert.equal(SOURCE_RECORD.record_type,'work');assert.deepEqual(target.record_ref,{id:SOURCE_RECORD.record_id,version:SOURCE_RECORD.record_version,digest:expectedDigest});assert.equal(target.content_revision,expectedDigest);
  await page.getByRole('button',{name:'Открыть источники',exact:true}).click();const response=page.waitForResponse(r=>r.url().endsWith('/api/source/read'));await page.getByRole('button',{name:'Открыть исходную запись',exact:true}).click();const delivery=await response;
  await waitFor(page,"document.querySelector('.sc-exact-source')?.dataset.sourceReadStatus === 'available'");const exact=page.locator('.sc-exact-source');for(let i=0;i<await exact.locator('details').count();i++)await exact.locator('details').nth(i).locator('summary').click();
  const exactText=await exact.innerText();assert.doesNotMatch(exactText,/tos\.work\.friedrich/);assert.match(exactText,/Jenseits von Gut und Böse/);assert.doesNotMatch(exactText,/ToS\/source-witnesses/);assert.equal(await exact.locator('pre').count(),0);
  const exported=await downloadJson(page,exact.getByRole('button',{name:'Скачать запись',exact:true}));const envelope=await delivery.json();delete envelope.handle;const selection=exported.selection;delete exported.selection;
  assert.deepEqual(selection,{kind:'node',id,source_revision:packet.source_revision,content_revision:packet.matches[0].content_revision});assert.deepEqual(exported,envelope);assert.deepEqual(exported.record,SOURCE_RECORD);
}));

// 4. Exact metadata remains readable when optional native-text discovery fails.
for(const failure of ['network','malformed'])test(`test_source_metadata_remains_when_native_discovery_fails_${failure}`,async()=>withNative('source-native-metadata',async(page,base)=>{
  const [_,nodeId]=await firstEdgeAndNode(page);await page.goto(`${base}/static/research.html?focus=${q('philosophy:'+nodeId)}`,{waitUntil:'domcontentloaded'});
  await page.locator('#tree[data-ready="true"] .reading [data-source-record-id]').waitFor({state:'attached'});await page.locator('.reading details').filter({has:page.locator('[data-source-record-id]')}).locator(':scope > summary').click();
  let capabilityCalls=0,pendingRoute;let releasePending;const pending=new Promise(resolve=>{releasePending=resolve;});
  await page.route('**/api/source/capabilities',async route=>{capabilityCalls++;if(capabilityCalls===1)await route.continue();else{pendingRoute=route;releasePending();}});
  await page.locator('.reading [data-source-record-id]').click();const record=page.locator('dialog[data-kind="source-record"] .dialog-content');await record.getByText('Synthetic native metadata',{exact:true}).waitFor({state:'visible'});await record.locator('details > summary').click();
  assert.match(await record.innerText(),/Available exact metadata remains readable/);await pending;assert.equal(capabilityCalls,2);assert.equal(await record.getAttribute('data-source-read-status'),'available');
  if(failure==='network')await pendingRoute.abort('failed');else await pendingRoute.fulfill({status:200,contentType:'application/json',body:'{' });
  await record.getByText('Способы чтения текста сейчас недоступны.',{exact:true}).waitFor({state:'visible'});assert.equal(await record.getAttribute('data-source-read-status'),'available');assert.ok(await record.getByText('Synthetic native metadata',{exact:true}).isVisible());
  assert.match(await record.innerText(),/Available exact metadata remains readable/);assert.equal(await record.locator('.source-native-actions button').count(),0);assert.doesNotMatch(await record.innerText(),/tos\.text-unit\.browser-fixture|ToS\/synthetic\/native-metadata\.json/);assert.equal(await record.locator('pre').count(),0);
  const exported=await downloadJson(page,record.getByRole('button',{name:'Скачать данные',exact:true}));assert.equal(exported.record.record_id,'tos.text-unit.browser-fixture');assert.equal(Object.hasOwn(exported,'handle'),false);assert.match(JSON.stringify(exported),/ToS\/synthetic\/native-metadata\.json/);
}));

// 5. Locale and panel sequence remains deterministic across the real reader UI.
test('test_research_seeded_locale_and_panel_sequence',async()=>withNative('source',async(page,base)=>{
  const [_,nodeId]=await firstEdgeAndNode(page);await page.goto(`${base}/static/research.html?focus=${q('philosophy:'+nodeId)}`);await page.locator('#tree[data-ready="true"] .reading h1').waitFor();
  const names={ru:['Собрать линзу','Читать произведения и издания','Моя полка','Об этой области','Настроить связи','Закрыть'],en:['Build a lens','Read works and editions','My shelf','About this area','Choose relations','Close']};let language='ru';
  const actions=['en','ru','sources','scope','conditions','shelf','library','search'].repeat(3);let seed=915236;for(let i=actions.length-1;i>0;i--){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const j=seed%(i+1);[actions[i],actions[j]]=[actions[j],actions[i]];}
  for(const [step,action] of actions.entries()){
    if(action==='en'||action==='ru'){await page.locator(`[data-live-lang="${action}"]`).click();language=action;}
    else if(action==='sources'){const disclosure=page.locator('.reading details').filter({has:page.locator('[data-source-record-id]')}).locator(':scope > summary');await disclosure.click();assert.ok(await page.locator('.reading [data-source-record-id]').isVisible(),`${step}:${action}`);assert.equal(await page.locator('.reading pre').count(),0);await disclosure.click();}
    else if(action==='search'){await page.locator('.search-trigger').click();await page.locator('[data-search-service]').uncheck();assert.ok(await page.getByLabel(language==='ru'?'Служебные записи':'Service records',{exact:true}).isVisible());await page.locator('.search').fill('fixture');await page.locator('.live-search-form button').click();await page.locator('.material-list [data-result-id]').first().waitFor({state:'visible'});const first=await page.locator('.material-list [data-result-id]').evaluateAll(rows=>rows.map(row=>row.dataset.resultId));await page.locator('.live-more').click();await page.locator('.live-search-previous').waitFor({state:'visible'});await page.locator('.live-search-previous').click();await waitFor(page,expected=>JSON.stringify([...document.querySelectorAll('.material-list [data-result-id]')].map(row=>row.dataset.resultId))===expected,30000,JSON.stringify(first));await page.locator('[data-search-service]').check();await page.keyboard.press('Escape');assert.equal(await page.locator('.materials-panel').isVisible(),false);await page.locator('.search-trigger').click();assert.equal(await page.locator('[data-search-service]').isChecked(),true);assert.equal(await page.locator('.live-more').isDisabled(),false);await page.keyboard.press('Escape');}
    else if(action==='shelf'){await page.getByRole('button',{name:names[language][2],exact:true}).click();const shelf=page.locator('.research-shelf');const labels=language==='ru'?['Исследовательская полка','Тип','Закрыть полку']:['Research shelf','Type','Close shelf'];assert.ok(await shelf.getByRole('heading',{name:labels[0],exact:true}).isVisible());assert.ok(await shelf.getByLabel(labels[1],{exact:true}).isVisible());assert.equal(await shelf.locator('pre').count(),0);await shelf.getByRole('button',{name:labels[2],exact:true}).click();}
    else if(action==='library'){await page.getByRole('button',{name:names[language][1],exact:true}).click();const reader=page.locator('.corpus-reader');const message=language==='ru'?'Источник полных текстов пока не подключён.':'The full-text source is not connected yet.';await reader.getByText(message,{exact:true}).waitFor({state:'visible'});assert.equal(await reader.getByText(message,{exact:true}).count(),1);assert.equal(await reader.locator('.cr-library,.cr-save').count(),0);await reader.getByRole('button',{name:language==='ru'?'Вернуться к Древу':'Return to the tree',exact:true}).click();}
    else{await page.getByRole('button',{name:names[language][action==='scope'?3:4],exact:true}).click();const dialog=page.getByRole('dialog');assert.ok(await dialog.isVisible(),`${step}:${action}`);assert.equal(await dialog.locator('pre').count(),0);await dialog.getByRole('button',{name:names[language][5],exact:true}).click();}
    for(const name of names[language].slice(0,3))assert.ok(await page.getByRole('button',{name,exact:true}).isVisible(),`${step}:${action}:${name}`);
  }assert.ok(await page.locator('.reading h1').isVisible());
}));

// 6. Cancellation, local workspace persistence, reload and URL state.
test('test_real_browser_cancellation_reload_and_deep_link',async()=>withNative('default',async page=>{
  const [edgeId,nodeId]=await firstEdgeAndNode(page);await invoke(page,'tos.page.select',{item_id:edgeId});await waitFor(page,"!window.__TOS_E2E.names().includes('tos.page.show-neighborhood')");await invoke(page,'tos.page.select',{item_id:nodeId});await waitFor(page,"window.__TOS_E2E.names().includes('tos.page.show-neighborhood')");
  const cancelled=await page.evaluate("window.__TOS_E2E.invokeAbort('tos.page.show-neighborhood',{})");assert.equal(cancelled.ok,false);assert.equal(cancelled.name,'AbortError');
  await invoke(page,'tos.page.add-research-note',{text:'Survives reload'});await page.reload({waitUntil:'domcontentloaded'});await waitFor(page,"Boolean(document.getElementById('current-view-title')?.textContent)");await waitFor(page,"document.getElementById('research-workspace-body')?.textContent?.includes('Survives reload')");
  assert.match(await page.locator('#research-workspace-body').textContent(),/Survives reload/);assert.match(page.url(),/mode=philosophy/);assert.match(page.url(),/view=chronology/);assert.match(page.url(),/graph=nodes/);
}));

// 7. Prepared search keeps its engine, exact selection and independent cursor.
test('test_real_browser_prepared_search_preserves_engine_and_selection',async()=>withNative('prepared',async page=>{
  const first=commandValue(await invoke(page,'tos.page.knowledge-search',{query:'philosophy',limit:1}));assert.equal(first.schema,'tos_knowledge_search_compressed_v3');assert.equal(first.search_mode,'compressed');assert.equal(first.nodes.length,1);
  await page.locator('#detail-list [data-result]').first().click();const selected=commandValue(await invoke(page,'tos.page.inspect-selection'));assert.equal(selected.selection.id,first.nodes[0].id);assert.ok((await readText(page,'#detail-list')).trim());
  await assert.rejects(()=>invoke(page,'tos.page.knowledge-search',{query:'philosophy',search_mode:'indexed'}),/mode unavailable: indexed/);assert.deepEqual(commandValue(await invoke(page,'tos.page.inspect-selection')).selection,selected.selection);assert.ok(first.next_cursor);
  const second=commandValue(await invoke(page,'tos.page.knowledge-search',{query:'philosophy',cursor:first.next_cursor,search_mode:first.search_mode,limit:1}));assert.equal(second.schema,first.schema);assert.equal(second.search_mode,first.search_mode);assert.equal(second.source_revision,first.source_revision);assert.equal(new Set([...first.nodes.map(n=>n.id),...second.nodes.map(n=>n.id)]).size,first.nodes.length+second.nodes.length);
}));

// 8. Human search and agent continuation share the selected native engine.
test('test_observatory_prepared_human_agent_search_and_continuation',async()=>withNative('prepared',async(page,base)=>{
  const initial=commandValue(await invoke(page,'tos.page.knowledge-search',{query:'fixture',limit:1}));await page.goto(`${base}/?focus=${q(initial.nodes[0].id)}`);await waitFor(page,"window.__TOS_E2E.names().includes('tos.page.knowledge-search')");
  const first=commandValue(await invoke(page,'tos.page.knowledge-search',{query:'fixture',limit:1}));assert.equal(first.search_mode,'compressed');assert.ok(first.nodes[0].label);await page.locator('.sc-search-results .sc-result').first().click();await waitFor(page,"window.__TOS_E2E.names().includes('tos.page.inspect-selection')");assert.equal(commandValue(await invoke(page,'tos.page.inspect-selection')).selection.id,first.nodes[0].id);assert.ok(first.next_cursor);
  const second=commandValue(await invoke(page,'tos.page.knowledge-search',{query:'fixture',limit:1,search_mode:first.search_mode,cursor:first.next_cursor}));assert.equal(second.source_revision,first.source_revision);assert.equal(new Set([...first.nodes.map(n=>n.id),...second.nodes.map(n=>n.id)]).size,first.nodes.length+second.nodes.length);
  await page.locator('#sc-query').fill('fixture ');await page.locator('.sc-search-pager').getByRole('button',{name:'Далее',exact:true}).waitFor({state:'visible'});const firstPage=await page.locator('.sc-search-results .sc-result').allTextContents();await page.locator('.sc-search-pager').getByRole('button',{name:'Далее',exact:true}).click();await page.locator('.sc-search-pager').getByRole('button',{name:'Ранее',exact:true}).click();await page.locator('.sc-search-results .sc-result').first().waitFor({state:'visible'});assert.deepEqual(await page.locator('.sc-search-results .sc-result').allTextContents(),firstPage);
}));

// 9. Projection changes refresh links while retaining reading and disclosure.
test('test_research_visibility_refreshes_links_and_preserves_source_disclosure',async()=>withNative('source',async(page,base)=>{
  const hits=commandValue(await invoke(page,'tos.page.knowledge-search',{query:'Alpha',limit:10}));const materialId=hits.nodes.find(row=>row.id==='philosophy:a').id;
  await page.route('**/api/knowledge/catalog',async route=>{const response=await route.fetch();const catalog=await response.json();let changed=0;for(const entry of catalog.semantic_registries.entity_types.entries){if(entry.source_mappings.some(m=>m.source_graph==='philosophy'&&['work','source'].includes(m.source_kind_id))){entry.object_role='projection';changed++;}}assert.ok(changed);await route.fulfill({response,json:catalog});});
  await page.goto(`${base}/static/research.html?focus=${q(materialId)}`);const reading=page.locator('#tree[data-ready="true"] .reading');await reading.locator('h1').waitFor();await reading.getByText('Источники',{exact:true}).click();const opened=reading.locator('details[open]').first();assert.ok(await opened.isVisible());await page.locator('[data-show-service-objects]').click();await reading.locator('.related-materials [data-related-node-id]').first().waitFor({state:'visible'});assert.ok(await opened.isVisible());assert.equal(await page.getByText('Не удалось выполнить действие. Повторите попытку.',{exact:true}).count(),0);
  await reading.locator('.related-relation').first().click();await reading.locator('.relation-participants').waitFor({state:'visible'});const selection=await page.locator('#tree').getAttribute('data-selection');await page.locator('[data-live-projection="compact"]').click();assert.equal(await page.locator('#tree').getAttribute('data-selection'),selection);assert.equal(await reading.locator('.relation-participants [data-related-node-id]').count(),2);await reading.locator('.relation-participants [data-related-node-id]').first().click();await reading.locator('h1').waitFor();await page.locator('[data-live-projection="grouped"]').click();await reading.locator('.related-materials [data-related-node-id]').first().waitFor({state:'visible'});
}));

// 10. Shipped entry persists exact shelf and camera pose through IndexedDB.
test('test_built_research_entry_persists_exact_shelf_and_camera',async()=>withNative('source',async(page,base)=>{
  const hits=commandValue(await invoke(page,'tos.page.knowledge-search',{query:'fixture',limit:1}));const materialId=hits.nodes[0].id;await page.goto(`${base}/static/research.html?focus=${q(materialId)}`);const reading=page.locator('#tree[data-ready="true"] .reading');await reading.getByRole('button',{name:'Сохранить материал',exact:true}).click();
  const neighbor=reading.locator('.related-materials [data-related-node-id]').first();await neighbor.waitFor({state:'visible'});const neighborId=await neighbor.getAttribute('data-related-node-id');await neighbor.click();await waitFor(page,`document.querySelector('#tree').dataset.selection === ${JSON.stringify(neighborId)}`);await reading.locator('.related-relation').first().click();const endpoint=reading.locator('.relation-participants [data-related-node-id]').first();await endpoint.waitFor({state:'visible'});const endpointId=await endpoint.getAttribute('data-related-node-id');await endpoint.click();await waitFor(page,`document.querySelector('#tree').dataset.selection === ${JSON.stringify(endpointId)}`);
  await reading.getByRole('button',{name:'Сравнить',exact:true}).click();assert.ok(await reading.getByRole('button',{name:'Добавлено к сравнению',exact:true}).isDisabled());assert.equal(await page.locator('[data-live-action="compare"]').innerText(),'Сопоставить (1/2)');
  const title=await reading.locator('h1').innerText();await page.locator('[data-live-action="compare"]').click();await page.locator('dialog[open]').waitFor({state:'visible'});await page.keyboard.press('Escape');await page.locator('dialog[open]').waitFor({state:'hidden'});assert.equal(await reading.isVisible(),true);assert.equal(await reading.locator('h1').innerText(),title);await page.locator('.search-trigger').click();await page.locator('.search').fill('fixture');await page.keyboard.press('Escape');assert.equal(await page.locator('.materials-panel').isVisible(),false);assert.equal(await reading.isVisible(),true);assert.equal(await reading.locator('h1').innerText(),title);
  await page.locator('[data-research-shelf="true"]').click();const card=page.locator('.research-shelf-card').first();await card.waitFor({state:'visible'});const recordId=await card.getAttribute('data-record-id');assert.ok(recordId);assert.doesNotMatch(await page.locator('.research-shelf').innerText(),/работает в памяти/);await page.reload();await page.locator('[data-research-shelf="true"]').click();await page.locator(`.research-shelf-card[data-record-id="${recordId}"]`).waitFor({state:'visible'});await page.getByRole('button',{name:'Закрыть полку',exact:true}).click();await page.locator('.reading').getByRole('button',{name:'Закрыть',exact:true}).click();
  await page.locator('[data-live-action="motion"]').click();const before=await page.locator('#tree').getAttribute('data-camera');await page.mouse.move(600,380);await page.mouse.wheel(0,220);await waitFor(page,`document.querySelector('#tree').dataset.camera !== ${JSON.stringify(before)}`);await page.waitForTimeout(750);
  const pose=await page.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const req=indexedDB.open('tos-real-ui-view-v1');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const saved=await new Promise((resolve,reject)=>{const req=db.transaction('views','readonly').objectStore('views').get('constructor-live');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});db.close();return saved.presentation.pose;});assert.notEqual(pose.zoom,Number(before.split(',')[2]));await page.reload();await page.locator('#tree[data-ready="true"] .reading').getByRole('button',{name:'Сохранить материал',exact:true}).waitFor({state:'visible'});const restored=(await page.locator('#tree').getAttribute('data-camera')).split(',').map(Number);assert.ok(restored.every((v,i)=>Math.abs(v-[pose.yaw,pose.pitch,pose.zoom,...pose.pan][i])<=.002));
  await page.setViewportSize({width:390,height:844});await page.locator('.research-shelf-narrow').click();assert.ok(await page.evaluate('document.documentElement.scrollWidth <= innerWidth'));await page.locator(`.research-shelf-card[data-record-id="${recordId}"]`).waitFor({state:'visible'});await page.getByRole('button',{name:'Закрыть полку',exact:true}).click();assert.equal(await page.locator('.research-shelf-narrow').evaluate(node=>node===document.activeElement),true);
}));

// 11. Catalog response limit remains actionable and can be retried.
test('test_research_catalog_limit_explains_failed_connection_and_can_retry',async()=>withNative('source',async(page,base)=>{
  let unavailable=true;await page.route('**/api/knowledge/catalog',route=>unavailable?route.fulfill({status:413,contentType:'application/json',body:'{}'}):route.continue());await page.goto(base+'/static/research.html',{waitUntil:'domcontentloaded'});
  const connection=page.locator('dialog[open][data-kind="connection"]');await connection.getByText('Словарь данных слишком велик для загрузки. Обратитесь к оператору сервиса.',{exact:true}).waitFor({state:'visible'});assert.doesNotMatch(await connection.innerText(),/Выберите более узкий центр/);unavailable=false;await connection.getByRole('button',{name:'Повторить подключение',exact:true}).click();await page.locator('#tree[data-ready="true"]').waitFor({state:'visible'});await page.locator('dialog[data-kind="connection"]').waitFor({state:'hidden'});
}));

// 12. Ordinary navigation and saved shelf route use the installed static entry.
test('test_observatory_research_and_saved_route_links_use_packaged_entry',async()=>withNative('source',async(page,base)=>{
  const hits=commandValue(await invoke(page,'tos.page.knowledge-search',{query:'fixture',limit:1}));const id=hits.nodes[0].id;const observatory=`${base}/?focus=${q(id)}`;await page.goto(observatory,{waitUntil:'domcontentloaded'});await page.locator('#sophia-gestures[data-data-state="ready"]').waitFor({state:'visible'});
  const [entry]=await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),page.getByRole('link',{name:'Пространство исследования',exact:true}).click()]);assert.equal(entry.status(),200);assert.equal(new URL(page.url()).pathname,'/static/research.html');await page.locator('#tree[data-ready="true"]').waitFor({state:'visible'});
  await page.goto(`${base}/static/research.html?focus=${q(id)}`);await page.locator('#tree[data-ready="true"] .reading [data-source-record-id]').waitFor({state:'attached'});await page.locator('[data-live-action="scope"]').click();await page.getByRole('button',{name:'Сохранить эту область',exact:true}).click();await page.getByText('Область сохранена на вашей полке.',{exact:true}).waitFor({state:'visible'});await page.locator('dialog[data-kind="scope"]').getByRole('button',{name:'Закрыть',exact:true}).click();await page.locator('[data-research-shelf="true"]').click();const card=page.locator('.research-shelf-card').first();await card.waitFor({state:'visible'});const recordId=await card.getAttribute('data-record-id');assert.ok(recordId);await page.getByRole('button',{name:'Закрыть полку',exact:true}).click();
  await page.goto(observatory,{waitUntil:'domcontentloaded'});await page.locator('#sophia-gestures[data-data-state="ready"]').waitFor({state:'visible'});await page.locator('[data-research-shelf="true"]').click();const stored=page.locator(`.research-shelf-card[data-record-id="${recordId}"]`);const [route]=await Promise.all([page.waitForNavigation({waitUntil:'domcontentloaded'}),stored.getByRole('button',{name:'Открыть',exact:true}).click()]);assert.equal(route.status(),200);assert.equal(new URL(page.url()).pathname,'/static/research.html');assert.deepEqual(new URL(page.url()).searchParams.getAll('shelfRoute'),[recordId]);await page.locator('#tree[data-ready="true"] .reading [data-source-record-id]').waitFor({state:'attached'});assert.equal(await page.locator('#tree').getAttribute('data-selection'),id);
}));

// 13. Lens preview/save/apply/back/reopen uses a new catalog binding on reload.
test('test_research_lens_preview_save_apply_and_return',async()=>withNative('source',async(page,base)=>{
  const hits=commandValue(await invoke(page,'tos.page.knowledge-search',{query:'fixture',limit:1}));const id=hits.nodes[0].id;const discovery=[];page.on('request',req=>{const p=new URL(req.url()).pathname;if(['/api/knowledge/catalog','/api/knowledge/contracts'].includes(p))discovery.push(p);});await page.goto(`${base}/static/research.html?focus=${q(id)}`);const tree=page.locator('#tree[data-ready="true"][data-loading="false"]');await tree.waitFor({state:'visible'});await waitFor(page,`document.querySelector('#tree').dataset.selection === ${JSON.stringify(id)}`);const selection=await tree.getAttribute('data-selection'),camera=await tree.getAttribute('data-camera');assert.deepEqual(discovery,['/api/knowledge/catalog']);
  await page.getByRole('button',{name:'Собрать линзу',exact:true}).click();const builder=page.locator('.lens-builder');await page.locator('.lens-builder[data-state="ready"]').waitFor({state:'visible'});for(let i=0;i<2;i++){await builder.locator('.lens-builder-header .lens-builder-close').click();await page.getByRole('button',{name:'Собрать линзу',exact:true}).click();await page.locator('.lens-builder[data-state="ready"]').waitFor({state:'visible'});}assert.deepEqual(discovery,['/api/knowledge/catalog','/api/knowledge/contracts']);
  await builder.getByLabel('Название линзы',{exact:true}).fill('Fixture saved lens');await builder.getByRole('button',{name:'Предпросмотр',exact:true}).click();await page.locator('.lens-builder[data-state="preview"]').waitFor({state:'visible'});assert.ok(await builder.getByRole('button',{name:'Открыть область',exact:true}).isEnabled());assert.equal(await tree.getAttribute('data-selection'),selection);assert.equal(await tree.getAttribute('data-camera'),camera);
  await builder.getByRole('button',{name:'Сохранить линзу',exact:true}).click();await builder.locator('[data-state="saved"]').waitFor({state:'visible'});await builder.getByRole('button',{name:'Открыть область',exact:true}).click();await page.locator('#tree[data-history="1"]').waitFor({state:'visible'});await page.locator('[data-live-action="back"]').click();await page.locator('#tree[data-history="0"][data-loading="false"]').waitFor({state:'visible'});assert.equal(await tree.getAttribute('data-selection'),selection);assert.equal(await tree.getAttribute('data-camera'),camera);
  await page.reload();await page.locator('#tree[data-ready="true"][data-loading="false"]').waitFor({state:'visible'});assert.equal(await tree.getAttribute('data-selection'),selection);await page.getByRole('button',{name:'Моя полка',exact:true}).click();const card=page.locator('.research-shelf-card').filter({hasText:'Fixture saved lens'});await card.getByRole('button',{name:'Открыть',exact:true}).click();await page.locator('.lens-builder[data-state="ready"]').waitFor({state:'visible'});assert.deepEqual(discovery,['/api/knowledge/catalog','/api/knowledge/contracts','/api/knowledge/catalog','/api/knowledge/contracts']);assert.equal(await builder.getByLabel('Название линзы',{exact:true}).inputValue(),'Fixture saved lens');assert.equal(await builder.getByRole('button',{name:'Открыть область',exact:true}).isEnabled(),false);await builder.getByRole('button',{name:'Предпросмотр',exact:true}).click();await page.locator('.lens-builder[data-state="preview"]').waitFor({state:'visible'});assert.ok(await builder.getByRole('button',{name:'Открыть область',exact:true}).isEnabled());
}));

// 14. Graceful fallback without a WebMCP host.
test('test_real_browser_graceful_without_webmcp',async()=>withNative('default',async(page)=>{
  await page.waitForTimeout(500);assert.equal(await page.evaluate('document.modelContext === undefined'),true);assert.equal(await page.locator('#app').count(),1);assert.equal(await page.locator('#agent-surface').getAttribute('data-webmcp-state'),'unavailable');const fallback=await readText(page,'#agent-surface');assert.match(fallback,/Codex WebMCP unavailable/);assert.match(fallback,/no API key or model API is required/);assert.match(fallback,/Optional off-page access/);assert.match(await readText(page,'body'),/Tree of Sophia/);
},{webmcp:false}));

// 15. Pagehide and interrupted IndexedDB writes recover exactly one draft.
test('test_corpus_note_exit_recovers_exact_draft',async()=>withVite(async base=>{
  const url=base+'/static/fixtures/corpus-reader.html';const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.TOS_E2E_CHROMIUM?{executablePath:process.env.TOS_E2E_CHROMIUM}:{})});
  try{for(const interrupted of [false,true]){const context=await browser.newContext({locale:'ru-RU'});const page=await context.newPage();page.on('dialog',d=>d.accept());await page.goto(url,{waitUntil:'domcontentloaded'});await page.waitForSelector('#tree[data-fixture-ready="true"]');await page.locator('[data-corpus-open]').click();await page.locator('.cr-unit:not(.cr-heading) .cr-unit-marker').first().click();await page.locator('.cr-note-editor').waitFor();const unitId=await page.locator('.cr-unit:not(.cr-heading)').first().getAttribute('data-unit-id');const value='Незавершённая заметка 😀 α — '+interrupted;
    if(interrupted){const nav=page.waitForNavigation({waitUntil:'domcontentloaded'});await page.evaluate(text=>{const transaction=IDBDatabase.prototype.transaction;IDBDatabase.prototype.transaction=function(names,mode,...rest){if(mode==='readwrite')throw new DOMException('Interrupted test write','AbortError');return transaction.call(this,names,mode,...rest);};const editor=document.querySelector('.cr-note-editor');editor.value=text;editor.dispatchEvent(new Event('input',{bubbles:true}));location.reload();},value);await nav;}
    else await page.evaluate(text=>{const editor=document.querySelector('.cr-note-editor');editor.value=text;editor.dispatchEvent(new Event('input',{bubbles:true}));window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false}));},value);
    await waitFor(page,async text=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('tos-corpus-reader-fixture-v1');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise((resolve,reject)=>{const r=db.transaction('notes','readonly').objectStore('notes').getAll();r.onsuccess=()=>resolve(r.result.some(n=>n.text===text));r.onerror=()=>reject(r.error);});}finally{db.close();}},15000,value);
    const notes=await idbReadings(page,'tos-corpus-reader-fixture-v1','notes');assert.equal(notes.length,1);assert.equal(notes[0].reference.unitId,unitId);if(interrupted){assert.ok(notes[0].id.startsWith('recovered-'));await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('#tree[data-fixture-ready="true"]');assert.equal((await idbReadings(page,'tos-corpus-reader-fixture-v1','notes')).length,1);assert.equal(await page.evaluate("sessionStorage.getItem('tos.corpus.note-draft.v1:tos-corpus-reader-fixture-v1')"),null);}await context.close();}
  }finally{await browser.close();}
}));

// 16. Two-connection collection deletion remains atomic.
test('test_research_shelf_collection_delete_is_atomic',async()=>withVite(async base=>{
  const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.TOS_E2E_CHROMIUM?{executablePath:process.env.TOS_E2E_CHROMIUM}:{})});try{const page=await browser.newPage({locale:'ru-RU'});await page.goto(base+'/static/fixtures/research-shelf.html',{waitUntil:'domcontentloaded'});const proof=page.locator('#research-shelf-proof[data-state]');await proof.waitFor({state:'visible'});const value=JSON.parse(await proof.innerText());assert.equal(await proof.getAttribute('data-state'),'passed');assert.ok(value.tests.collectionDetach.ok);assert.ok(value.tests.collectionDeleteRollback.ok);assert.ok(Object.values(value.tests).every(item=>item.ok));}finally{await browser.close();}
}));

// 17. A large relation area requires explicit all-tree scope confirmation.
test('test_lens_large_relation_area_requires_scope_confirmation',async()=>withVite(async base=>{
  const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.TOS_E2E_CHROMIUM?{executablePath:process.env.TOS_E2E_CHROMIUM}:{})});try{const page=await browser.newPage({locale:'ru-RU'});await page.route('**/lens-scope-check',route=>route.fulfill({status:200,contentType:'text/html',body:'<html lang="ru"><body><main id="scope-check"></main></body></html>'}));await page.goto(base+'/lens-scope-check');await page.evaluate(async()=>{await import('/static/fixtures/reader-rules.mjs');const {mountLensBuilder}=await import('/static/src/observatory/lens-builder.mjs');const {lensContext,boundary}=await import('/static/fixtures/lens-scenarios.mjs');const context=lensContext(),nodes=Array.from({length:41},(_,i)=>({id:'fixture:'+i}));const selection={kind:'relation',id:'fixture:relation'};const packet={schema:'tos_browser_exploration_view_v1',source_revision:context.catalog.source_revision,authority_boundary:boundary,nodes,relations:[{id:selection.id,from_id:nodes[0].id,to_id:nodes[1].id}],selection};window.scopeCheck={packet,compiles:0};window.scopeCheck.builder=mountLensBuilder({host:document.querySelector('#scope-check'),getArea:()=>({packet,selection}),client:{request:async path=>path==='/catalog'?context.catalog:{schema:'tos_knowledge_contract_bundle_v1',authority_boundary:boundary,contracts:{lens_spec:context.schema}},compile:async()=>{window.scopeCheck.compiles++;throw Error('Preview must stay explicit');}}});await window.scopeCheck.builder.open();});
  const builder=page.locator('#scope-check .lens-builder'),choice=builder.locator('.lens-builder-area-choice');assert.equal(await choice.locator('option').count(),1);assert.equal(await choice.locator('select').inputValue(),'all');assert.equal(await page.evaluate('scopeCheck.builder.state().areaChoice.required'),true);assert.ok(await builder.getByRole('button',{name:'Предпросмотр',exact:true}).isDisabled());await choice.getByRole('button',{name:'Открыть область',exact:true}).click();await choice.waitFor({state:'hidden'});assert.equal(await page.evaluate('scopeCheck.builder.state().areaChoice.required'),false);assert.equal(await page.evaluate('scopeCheck.compiles'),0);assert.equal(await page.evaluate('scopeCheck.packet.nodes.length'),41);assert.ok(await builder.getByRole('button',{name:'Предпросмотр',exact:true}).isEnabled());assert.ok(await builder.getByRole('button',{name:'Сохранить линзу',exact:true}).isEnabled());
  await page.evaluate(async()=>{scopeCheck.builder.close();scopeCheck.packet.selection.kind='node';scopeCheck.packet.selection.id='fixture:0';scopeCheck.packet.nodes[0].display={title:{ru:'Выбранный центр'}};await scopeCheck.builder.open();});assert.equal(await choice.locator('select').inputValue(),'focus');await choice.getByRole('button',{name:'Открыть область',exact:true}).click();assert.match(await builder.innerText(),/Выбранный центр/);assert.ok(await builder.getByRole('button',{name:'Предпросмотр',exact:true}).isEnabled());
  await page.evaluate(async()=>{scopeCheck.builder.close();scopeCheck.packet.nodes.splice(2);await scopeCheck.builder.open();});await builder.locator('.lens-builder-field').filter({has:page.getByText('Отправная точка',{exact:true})}).locator('select').selectOption('focus');assert.match(await builder.locator('.lens-builder-focus').innerText(),/Выбранный центр/);assert.equal(await builder.getByRole('button',{name:'Взять выбранную звезду',exact:true}).count(),0);
  }finally{await browser.close();}
}));

// 18. Native delivery export preserves identity and expires with its owner.
test('test_native_delivery_export_preserves_identity_and_respects_expiry',async()=>withVite(async base=>{
  const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.TOS_E2E_CHROMIUM?{executablePath:process.env.TOS_E2E_CHROMIUM}:{})});try{const page=await browser.newPage({locale:'ru-RU'});await page.goto(base+'/static/fixtures/native-reader.html');await page.getByRole('button',{name:'Открыть текст',exact:true}).click();let reader=page.locator('.native-reader[data-native-state="available"]');await reader.waitFor();await reader.getByText('Об источнике',{exact:true}).click();const exported=await downloadJson(page,reader.getByRole('button',{name:'Скачать данные',exact:true}));assert.equal(Object.hasOwn(exported,'handle'),false);assert.equal(exported.record_ref.id,'tos.text-unit.fixture');assert.equal(exported.native_unit.packet.version,1);assert.ok(exported.native_unit.spans[0].text.startsWith('A😀é'));assert.equal(exported.text_access.scope,'public-native-unit');assert.equal(exported.selection.id,'source-claims:identity:tos.text-unit.fixture');
  await page.evaluate(()=>{window.oldExport=document.querySelector('.nr-exact .sc-data-download');window.exportAttempts=0;URL.createObjectURL=()=>{window.exportAttempts++;return 'blob:blocked';};});await reader.getByRole('button',{name:'К Древу',exact:true}).click();await page.locator('.native-reader').waitFor({state:'hidden'});assert.equal(await page.evaluate('oldExport.click();exportAttempts'),0);await page.getByRole('button',{name:'Локальные условия',exact:true}).click();await page.clock.install();await page.getByRole('button',{name:'Открыть текст',exact:true}).click();reader=page.locator('.native-reader[data-native-state="available"]');await reader.waitFor();assert.equal(await page.evaluate('oldExport.click();exportAttempts'),0);await page.evaluate(()=>window.localExport=document.querySelector('.nr-exact .sc-data-download'));const now=await page.evaluate('Date.now()');await page.clock.setFixedTime(now+91000);assert.equal(await page.evaluate('localExport.click();exportAttempts'),0);await page.clock.fastForward(91000);await page.locator('.native-reader[data-native-state="expired"]').waitFor();assert.equal(await page.locator('.nr-exact .sc-data-download').count(),0);assert.equal(await page.evaluate('localExport.click();exportAttempts'),0);
  }finally{await browser.close();}
}));

// 19. pagehide flush preserves corpus and native reader position before debounce.
test('test_reader_positions_survive_pagehide_before_debounce',async()=>withVite(async base=>{
  const corpusUrl=base+'/static/fixtures/corpus-reader.html',nativeUrl=base+'/static/fixtures/native-reader.html';const browser=await chromium.launch({headless:true,args:['--no-sandbox'],...(process.env.TOS_E2E_CHROMIUM?{executablePath:process.env.TOS_E2E_CHROMIUM}:{})});try{const context=await browser.newContext({locale:'ru-RU'});const corpus=await context.newPage();await corpus.goto(corpusUrl,{waitUntil:'domcontentloaded'});await corpus.waitForSelector('#tree[data-fixture-ready="true"]');await corpus.locator('[data-corpus-open]').click();await corpus.locator('.cr-pane').waitFor();const pos=await corpus.evaluate(()=>{const pane=document.querySelector('.cr-pane'),maximum=pane.scrollHeight-pane.clientHeight,requested=Math.min(maximum,Math.max(640,Math.floor(maximum*.45)));pane.scrollTop=requested;pane.dispatchEvent(new Event('scroll'));const rect=pane.getBoundingClientRect(),row=[...pane.querySelectorAll('.cr-unit')].find(item=>item.getBoundingClientRect().bottom>rect.top+18);window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false}));history.replaceState(history.state,'',location.pathname+location.search);return {top:pane.scrollTop,unitId:row?.dataset.unitId,versionId:pane.dataset.versionId};});assert.ok(pos.top>0);assert.ok(pos.unitId);const readings=await waitForReading(corpus,'tos-corpus-reader-fixture-v1',item=>item.reference?.unitId===pos.unitId);const saved=readings.find(item=>item.reference?.unitId===pos.unitId);assert.equal(saved.versionId,pos.versionId);assert.ok(saved.reference.target.workId);
  await corpus.reload({waitUntil:'domcontentloaded'});await corpus.waitForSelector('#tree[data-fixture-ready="true"]');await corpus.locator('[data-corpus-open]').click();await corpus.locator('.cr-pane').waitFor();await waitFor(corpus,unitId=>{const pane=document.querySelector('.cr-pane'),row=pane?.querySelector(`.cr-unit[data-unit-id="${CSS.escape(unitId)}"]`);if(!row||!pane)return false;const pr=pane.getBoundingClientRect(),rr=row.getBoundingClientRect();return rr.bottom>pr.top+18&&rr.top<=pr.top+28;},30000,pos.unitId);
  const native=await context.newPage();await native.goto(nativeUrl,{waitUntil:'domcontentloaded'});await native.getByRole('button',{name:'Открыть текст',exact:true}).click();await native.locator('.native-reader:not([hidden])').waitFor();await native.locator('.native-reader[data-native-state="available"]').waitFor();await native.locator('.nr-article').waitFor();const nativePos=await native.evaluate(()=>{const article=document.querySelector('.nr-article');article.scrollTop=Math.min(420,article.scrollHeight-article.clientHeight);article.dispatchEvent(new Event('scroll'));window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:false}));return {top:article.scrollTop};});assert.ok(nativePos.top>0);const nativeReads=await waitForReading(native,'tos-native-reader-validation-v1',item=>item.offset===nativePos.top);const nativeSaved=nativeReads.find(item=>item.offset===nativePos.top);assert.equal(nativeSaved.reference.schemaVersion,'tos.corpus.reader.native-reference.v1');await native.evaluate("history.replaceState(history.state,'',location.pathname+location.search)");await native.reload({waitUntil:'domcontentloaded'});await native.getByRole('button',{name:'Открыть текст',exact:true}).click();await native.locator('.native-reader[data-native-state="available"]').waitFor();await waitFor(native,expected=>Math.abs(document.querySelector('.nr-article').scrollTop-expected)<1,30000,nativePos.top);await context.close();
  }finally{await browser.close();}
}));
